##
## Test:
## curl -s -X POST -H "Content-Type: application/json" http://localhost:7100/dev/hello | jq
##

functions:
  - id: 'dxos.org/function/chat'
    path: 'chat'
    handler: 'chat'
    description: 'AI Chat'

  - id: 'dxos.org/function/chess'
    path: 'chess'
    handler: 'chess'
    description: 'Chess'

  - id: 'dxos.org/function/email'
    path: 'email'
    handler: 'email'
    description: 'Email Sync'

  - id: 'dxos.org/function/hello'
    path: 'hello'
    handler: 'hello'
    description: 'Hello world'

  - id: 'dxos.org/function/github'
    path: 'github'
    handler: 'github'
    description: 'Github Sync'

triggers:
  - function: 'dxos.org/function/chat'
    subscription:
      type: 'braneframe.Message'

  - function: 'dxos.org/function/chess'
    subscription:
      type: 'dxos.experimental.chess.Game'

  - function: 'dxos.org/function/email'
    schedule: '*/30 * * * * *'
    subscription:
      type: 'braneframe.Mailbox'

  - function: 'dxos.org/function/github'
    subscription:
      type: 'example.com/schema/project'
