##
## Test:
## curl -s -X POST -H "Content-Type: application/json" http://localhost:7100/dev/hello | jq
##

functions:
  - id: 'dxos.org/function/chat'
    name: 'chat'
    handler: 'chat'
    description: 'AI Chat'

  - id: 'dxos.org/function/chess'
    name: 'chess'
    handler: 'chess'
    description: 'Chess'

  - id: 'dxos.org/function/email'
    name: 'email'
    handler: 'email'
    description: 'Email Sync'

  - id: 'dxos.org/function/embedding'
    name: 'embedding'
    handler: 'embedding'
    description: 'Text embedding'

  - id: 'dxos.org/function/hello'
    name: 'hello'
    handler: 'hello'
    description: 'Hello world'

  - id: 'dxos.org/function/github'
    name: 'github'
    handler: 'github'
    description: 'Github Sync'

triggers:
  - function: 'dxos.org/function/chat'
    subscription:
      type: 'braneframe.Message'

  - function: 'dxos.org/function/chess'
    subscription:
      type: 'dxos.experimental.chess.Game'

#  - function: 'dxos.org/function/email'
#    schedule: '*/30 * * * * *'
#    subscription:
#      type: 'braneframe.Mailbox'

  - function: 'dxos.org/function/embedding'
    subscription:
      type: 'braneframe.Document'
      delay: 10

#  - function: 'dxos.org/function/github'
#    subscription:
#      type: 'example.com/schema/project'
