functions:
  chess:
    description: "Chess bot."

  chatgpt:
    description: "Chat GPT."

  hello:
    description: "Test function."

triggers:
  - function: chess
    subscription:
      type: dxos.experimental.chess.Game

  - function: chatgpt
    subscription:
      type: braneframe.Thread.Block
