##
## Test:
## curl -s -X POST -H "Content-Type: application/json" http://localhost:7001/dev/hello | jq
##

functions:
  - id: 'chat'
    description: 'AI Chat'

  - id: 'chess'
    description: 'Chess'

  - id: 'hello'
    description: 'Test'

  - id: 'email'
    description: 'Protonmail Sync'

triggers:
  - function: 'chat'
    subscription:
      type: 'braneframe.Thread.Block'

  - function: 'chess'
    subscription:
      type: 'dxos.experimental.chess.Game'
