##
## Test:
## curl -s -X POST -H "Content-Type: application/json" http://localhost:7001/dev/hello | jq
##

functions:
  - id: 'dxos.org/function/chat'
    path: 'chat'
    handler: 'chat'
    description: 'AI Chat'

  - id: 'dxos.org/function/chess'
    path: 'chess'
    handler: 'chess'
    description: 'Chess'

  - id: 'dxos.org/function/hello'
    path: 'hello'
    handler: 'hello'
    description: 'Test'

  - id: 'dxos.org/function/email'
    path: 'email'
    handler: 'email'
    description: 'Protonmail Sync'

triggers:
  - function: 'dxos.org/function/chat'
    subscription:
      type: 'braneframe.Thread.Block'

  - function: 'dxos.org/function/chess'
    subscription:
      type: 'dxos.experimental.chess.Game'
