functions:
  - id: 'chat'
    description: 'AI Chat'

  - id: 'chess'
    description: 'Chess'

  - id: 'hello'
    description: 'Test'

triggers:
  - function: 'chat'
    subscription:
      type: 'braneframe.Thread.Block'

  - function: 'chess'
    subscription:
      type: 'dxos.experimental.chess.Game'
