functions:
  chatgpt:
    description: "Chat GPT"

  chess:
    description: "Chess"

  hello:
    description: "Test"

triggers:
  - function: chatgpt
    subscription:
      type: braneframe.Thread.Block

  - function: chess
    subscription:
      type: dxos.experimental.chess.Game
