##
## Test:
## curl -s -X POST -H "Content-Type: application/json" http://localhost:7100/dev/hello | jq
##

functions:
  - id: 'dxos.org/function/calendar'
    name: 'calendar'
    handler: 'calendar'
    description: 'Calendar Sync.'

  - id: 'dxos.org/function/chat'
    name: 'chat'
    handler: 'chat'
    description: 'GPT Chat.'

  - id: 'dxos.org/function/chess'
    name: 'chess'
    handler: 'chess'
    description: 'Chess.'

  - id: 'dxos.org/function/email'
    name: 'email'
    handler: 'email'
    description: 'Email Sync.'

  - id: 'dxos.org/function/email-extractor'
    name: 'email-extractor'
    handler: 'email-extractor'
    description: 'Email Extractor.'

  - id: 'dxos.org/function/embedding'
    name: 'embedding'
    handler: 'embedding'
    description: 'Text embedding.'

  - id: 'dxos.org/function/hello'
    name: 'hello'
    handler: 'hello'
    description: 'Hello world.'

  - id: 'dxos.org/function/github'
    name: 'github'
    handler: 'github'
    description: 'Github Sync.'

triggers:
#  - function: 'dxos.org/function/calendar'
#    schedule: '*/30 * * * * *'
#    subscription:
#     - type: 'braneframe.Calendar'

#  - function: 'dxos.org/function/email'
#    trigger: 'https://hub.dxos.network/api/mailbox/hello@dxos.network'

  - function: 'dxos.org/function/chat'
    subscription:
      - type: 'braneframe.Message'

  - function: 'dxos.org/function/chess'
    subscription:
      - type: 'dxos.experimental.chess.Game'

  # - function: 'dxos.org/function/email'
  #   schedule: '*/30 * * * * *'
  #   subscription:
  #    - type: 'braneframe.Mailbox'

#  - function: 'dxos.org/function/email-extractor'
#    subscription:
#      - type: 'braneframe.Message'
#        delay: 5
#        props:
#          type: 'email'

  - function: 'dxos.org/function/embedding'
    subscription:
      - type: 'braneframe.Document'
        deep: true
        delay: 5
      - type: 'braneframe.File'

#  - function: 'dxos.org/function/github'
#    subscription:
#      - type: 'example.com/schema/project'
