//
// Copyright 2026 DXOS.org
//

import { describe, test } from 'vitest';

import { parseArtifactLink, parsePullRequestBody } from './pull-request-body.ts';
import { PULL_REQUEST_13348_BODY } from './testing/pull-request-13348.ts';

const BASE = 'https://pub-39066a86073446d7b77b1c157b660bb5.r2.dev/demos/2026-09-23-artifact';

describe('parsePullRequestBody', () => {
  test('a real body: footers out of the prose, into fields', ({ expect }) => {
    const { markdown, claudeCode, previewUrl, artifacts } = parsePullRequestBody(PULL_REQUEST_13348_BODY);
    expect(claudeCode).toEqual({ sessionUrl: 'https://claude.ai/code/session_016GM9fXXzbrr6JGNeeQBCmj' });
    expect(previewUrl).toEqual('https://pr-13348-composer-dev.dxos.workers.dev');
    expect(markdown).not.toContain('Generated with');
    expect(markdown).not.toContain('Generated by');
    expect(markdown).not.toContain('claude.ai/code');
    expect(markdown).not.toContain('Composer preview');
    expect(markdown).not.toContain('composer-preview');
    expect(markdown.endsWith('`DescriptionLinks` still passes.')).toBe(true);
    expect(artifacts).toEqual([
      { url: `${BASE}/pr-pill-hover-card.webm`, kind: 'video', name: 'pr-pill-hover-card.webm' },
      { url: `${BASE}/before.png`, kind: 'image', name: 'before.png', label: 'before' },
      { url: `${BASE}/after.png`, kind: 'image', name: 'after.png', label: 'after' },
    ]);
  });

  test('a body with no footers is left as written', ({ expect }) => {
    const body = 'Fixes the thing.\n\n---\n\nMore.';
    expect(parsePullRequestBody(body)).toEqual({ markdown: body, artifacts: [] });
  });

  test('the bare preview line, without the CI block', ({ expect }) => {
    const { markdown, previewUrl, claudeCode } = parsePullRequestBody(
      'Body.\n\n🤖 Generated with Claude Code\n\n🚀 Composer preview: https://pr-1-composer-dev.dxos.workers.dev\n',
    );
    expect(markdown).toEqual('Body.');
    expect(previewUrl).toEqual('https://pr-1-composer-dev.dxos.workers.dev');
    expect(claudeCode).toEqual({});
  });

  test('an artifact linked twice is listed once', ({ expect }) => {
    const { artifacts } = parsePullRequestBody(`[demo](${BASE}/a.webm) and again ${BASE}/a.webm`);
    expect(artifacts).toHaveLength(1);
  });

  test('handles an empty body', ({ expect }) => {
    expect(parsePullRequestBody(undefined)).toEqual({ markdown: '', artifacts: [] });
  });
});

describe('parseArtifactLink', () => {
  test('only the artifacts bucket', ({ expect }) => {
    expect(parseArtifactLink(`${BASE}/clip.MP4`)?.kind).toEqual('video');
    expect(parseArtifactLink(`${BASE}/logs.ndjson`)?.kind).toEqual('file');
    expect(parseArtifactLink('https://example.com/clip.webm')).toBeUndefined();
    expect(parseArtifactLink('not a url')).toBeUndefined();
  });
});
