//
// Copyright 2026 DXOS.org
//

/** Public host of the `agent-artifacts` R2 bucket that demo videos and screenshots are linked from. */
export const ARTIFACTS_HOST = 'pub-39066a86073446d7b77b1c157b660bb5.r2.dev';

export type ArtifactKind = 'video' | 'image' | 'file';

/** A file in the artifacts bucket that a pull request body links to. */
export type ArtifactLink = {
  url: string;
  kind: ArtifactKind;
  /** The file name, the last path segment. */
  name: string;
  /** The link's own text, when it was written as `[label](url)` rather than bare. */
  label?: string;
};

/** What a pull request body says beyond its prose: the footers the harness and CI append, and the media it links. */
export type PullRequestBody = {
  /** The prose, with the footers taken out. */
  markdown: string;
  /** Present when the body carries the Claude Code footer. */
  claudeCode?: {
    /** The session that wrote the pull request. */
    sessionUrl?: string;
  };
  /** The Composer deployment built from the pull request's head. */
  previewUrl?: string;
  /** Artifacts in first-mention order, each once. */
  artifacts: ArtifactLink[];
};

const VIDEO_EXTENSIONS = ['webm', 'mp4', 'mov', 'm4v', 'ogv'];
const IMAGE_EXTENSIONS = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'avif'];

/** The artifact a URL names, or undefined when it is not in the artifacts bucket. */
export const parseArtifactLink = (url: string): Omit<ArtifactLink, 'label'> | undefined => {
  let parsed: URL;
  try {
    parsed = new URL(url);
  } catch {
    return undefined;
  }
  if (parsed.protocol !== 'https:' || parsed.hostname !== ARTIFACTS_HOST) {
    return undefined;
  }
  const segment = parsed.pathname.split('/').at(-1) ?? '';
  if (!segment) {
    return undefined;
  }
  const name = safeDecode(segment);
  const extension = name.split('.').at(-1)?.toLowerCase() ?? '';
  const kind: ArtifactKind = VIDEO_EXTENSIONS.includes(extension)
    ? 'video'
    : IMAGE_EXTENSIONS.includes(extension)
      ? 'image'
      : 'file';
  return { url, kind, name };
};

const CLAUDE_SESSION = /https:\/\/claude\.ai\/code\/session_[A-Za-z0-9]+/;
const PREVIEW_BLOCK = /<!--\s*composer-preview:begin\s*-->([\s\S]*?)<!--\s*composer-preview:end\s*-->/;
const PREVIEW_LINE = /^\s*🚀\s*Composer preview:\s*(https?:\/\/\S+)\s*$/m;
// Each footer line is removed whole; they are recognised by their text, not their position.
const FOOTER_LINES: RegExp[] = [
  /^\s*🤖\s*Generated with \[?Claude Code\]?(\([^)]*\))?\s*$/,
  /^\s*_?Generated by \[Claude Code\]\([^)]*\)_?\s*$/,
  new RegExp(`^\\s*<?${CLAUDE_SESSION.source}>?\\s*$`),
];
// `[label](url)` first so a labelled link is not also counted bare.
const MARKDOWN_LINK = /!?\[([^\]]*)\]\((https?:\/\/[^\s)]+)\)/g;
const BARE_URL = /https?:\/\/[^\s)<>\]|]+/g;

/**
 * Splits a pull request body into its prose and what the footers and links say.
 *
 * The footers are the harness's (`🤖 Generated with Claude Code` and the session URL) and CI's
 * (the Composer preview block); the article shows them as cards, so they are taken out of the prose
 * rather than rendered twice.
 */
export const parsePullRequestBody = (body: string | undefined): PullRequestBody => {
  let text = (body ?? '').replace(/\r\n/g, '\n');

  const sessionUrl = text.match(CLAUDE_SESSION)?.[0];
  const hasClaudeFooter = FOOTER_LINES.slice(0, 2).some((pattern) =>
    text.split('\n').some((line) => pattern.test(line)),
  );

  let previewUrl: string | undefined;
  const block = text.match(PREVIEW_BLOCK);
  if (block) {
    previewUrl = block[1].match(PREVIEW_LINE)?.[1];
    text = text.replace(PREVIEW_BLOCK, '');
  }
  const line = text.match(PREVIEW_LINE);
  if (line) {
    previewUrl ??= line[1];
    text = text.replace(PREVIEW_LINE, '');
  }

  const lines = text.split('\n').filter((line) => !FOOTER_LINES.some((pattern) => pattern.test(line)));
  // The footers leave their `---` rules and blank lines behind at the end.
  while (lines.length > 0 && /^\s*(---+|\*\*\*+|___+)?\s*$/.test(lines[lines.length - 1])) {
    lines.pop();
  }
  const markdown = lines.join('\n').trim();

  return {
    markdown,
    ...(hasClaudeFooter || sessionUrl ? { claudeCode: sessionUrl ? { sessionUrl } : {} } : {}),
    ...(previewUrl ? { previewUrl } : {}),
    artifacts: findArtifacts(markdown),
  };
};

/** Every artifact the prose links, in order of first mention. */
const findArtifacts = (markdown: string): ArtifactLink[] => {
  const found = new Map<string, ArtifactLink>();
  const add = (url: string, label?: string) => {
    const artifact = found.has(url) ? undefined : parseArtifactLink(url);
    if (artifact) {
      found.set(url, { ...artifact, ...(label && label !== url ? { label } : {}) });
    }
  };
  for (const [, label, url] of markdown.matchAll(MARKDOWN_LINK)) {
    add(url, label);
  }
  for (const [url] of markdown.replace(MARKDOWN_LINK, '').matchAll(BARE_URL)) {
    add(url);
  }

  // Order by where each first appears, since labelled links were collected before bare ones.
  return [...found.values()].sort((a, b) => markdown.indexOf(a.url) - markdown.indexOf(b.url));
};

const safeDecode = (segment: string): string => {
  try {
    return decodeURIComponent(segment);
  } catch {
    return segment;
  }
};
