//
// Copyright 2025 DXOS.org
//

import { pipe } from 'effect';

import { Capabilities, chain, contributes, createIntent, type PromiseIntentDispatcher } from '@dxos/app-framework';
import { defineArtifact, defineTool, ToolResult } from '@dxos/artifact';
import { createArtifactElement } from '@dxos/assistant';
import { isInstanceOf, ObjectId, S } from '@dxos/echo-schema';
import { invariant } from '@dxos/invariant';
import { SpaceAction } from '@dxos/plugin-space/types';
import { Filter, type Space } from '@dxos/react-client/echo';
import { TableType } from '@dxos/react-ui-table';

import { TableAction } from '../types';

// TODO(burdon): Factor out.
declare global {
  interface ToolContextExtensions {
    space?: Space;
    dispatch?: PromiseIntentDispatcher;
  }
}

export default () => {
  const definition = defineArtifact({
    id: 'plugin-table',
    // TODO(ZaymonFC): See if we need instructions beyond what the tools define.
    instructions: '',
    schema: TableType,
    tools: [
      defineTool({
        name: 'table_new',
        description: 'Create a new table. Returns the artifact definition for the table',
        schema: S.Struct({}),
        execute: async (_input, { extensions }) => {
          invariant(extensions?.space, 'No space');
          invariant(extensions?.dispatch, 'No intent dispatcher');
          const intent = pipe(
            // TODO(ZaymonFC): Configure the starting table.
            createIntent(TableAction.Create, { space: extensions.space }),
            chain(SpaceAction.AddObject, { target: extensions.space }),
          );
          const { data, error } = await extensions.dispatch(intent);
          if (!data || error) {
            return ToolResult.Error(error?.message ?? 'Failed to create table');
          }

          return ToolResult.Success(createArtifactElement(data.id));
        },
      }),
      defineTool({
        name: 'table_inspect',
        description: 'Get the current schema of the table.',
        schema: S.Struct({ id: ObjectId }),
        execute: async ({ id }, { extensions }) => {
          invariant(extensions?.space, 'No space');
          const space = extensions.space;

          const { objects: tables } = await space.db.query(Filter.schema(TableType)).run();
          const table = tables.find((table) => table.id === id);
          invariant(isInstanceOf(TableType, table));


          const view = await table.view?.load();
          invariant(view);
          const typename = view?.query.type;
          const schema = await space.db.schemaRegistry.query({ typename }).firstOrUndefined();
          invariant(schema);
          return ToolResult.Success(schema);
        },
      }),
      defineTool({
        name: 'table_add_row',
        description: 'Add a new row to an existing table. Use table_inspect first to understand the schema. Note: row ID is autogenerated.',
        schema: S.Struct({
          id: ObjectId,
          data: S.Any.annotations({ description: 'The data payload' }),
        }),
        execute: async ({ id, data }, { extensions }) => {
          invariant(extensions?.space, 'No space');
          invariant(extensions?.dispatch, 'No intent dispatcher');

          const space = extensions.space;
          const { objects: tables } = await space.db.query(Filter.schema(TableType)).run();
          const table = tables.find((table) => table.id === id);
          invariant(isInstanceOf(TableType, table));

          const intent = createIntent(TableAction.AddRow, {
            table,
            data,
          });

          const { error } = await extensions.dispatch(intent);
          if (error) {
            return ToolResult.Error(error?.message ?? 'Failed to add row to table');
          }

          return ToolResult.Success('Row added successfully');
        },
      }),
    ],
  });

  return contributes(Capabilities.ArtifactDefinition, definition);
};
