@startuml
!theme superhero
skinparam backgroundColor black

actor       Alice                         as alice
entity      "Alice's kube"                as akube
queue       "Pub/Sub network"             as psn
entity      "Bob & Charlie's family kube" as fkube
actor       Bob                           as bob
actor       Charlie                       as charlie
autonumber 1.1

activate psn
== Bob joins ==
bob <-> fkube:        <i>connect</i>
activate fkube
bob -> fkube:         ReceiveMessages(key:bob)
fkube -[#green]> psn: Sub(topic:peer/bob)
bob -> fkube:         Join(swarm:s0 peer:bob)
fkube -[#green]> psn: Sub(topic:host/fkube)
fkube -[#green]> psn: Sub(topic:swarm/s0)
fkube -[#blue]> psn:  Pub(topic:swarm/s0 peer_available:bob timeout:600 announceBackTo:fkube)
...later on...
autonumber inc A
== Alice joins ==
alice <-> akube:<i>connect</i>
activate akube
alice -> akube:       ReceiveMessages(key:alice)
akube -[#green]> psn: Sub(topic:peer/alice)
alice -> akube:       Join(swarm:0 peer:alice timeout:600 announceBackTo:akube)
akube -[#green]> psn: Sub(topic:host/akube)
akube -[#green]> psn: Sub(topic:swarm/s0)
fkube -[#blue]> psn:  Pub(topic:host/akube peer:bob)
psn -[#blue]> akube:  Pub(topic:host/akube peer:bob)
akube -> alice:       Join(s:s0 p:alice).PeerAvailable(peer:bob)
akube -[#blue]> psn:  Pub(topic:swarm/s0 peer_available:alice timeout:600)
psn   -[#blue]> fkube:Pub(topic:swarm/s0 peer_available:alice timeout:600)
fkube -> bob:         Join(s:s0 p:bob).PeerAvailable(peer:alice)

== Alice messages Bob to connect ==
autonumber inc A
alice -> akube:       SendMessage(sender:alice receiver:bob payload:…)
akube -[#blue]> psn:  Pub(topic:peer/bob sender:alice payload:…)
psn -[#blue]> fkube:  Pub(topic:peer/bob sender:alice payload:…)
fkube -> bob:         Message(from:alice to:bob payload:…)

group Roundtrips
bob -> fkube:         SendMessage(sender:bob receiver:alice payload:…)
fkube -[#blue]> psn:  Pub(topic:peer/alice sender:bob payload:…)
psn -[#blue]> akube:  Pub(topic:peer/alice sender:bob payload:…)
akube -> alice:       Message(from:bob to:alice payload:…)

alice -> akube:       SendMessage(sender:alice receiver:bob payload:…)
akube -[#blue]> psn:  Pub(topic:peer/bob sender:alice payload:…)
psn -[#blue]> fkube:  Pub(topic:peer/bob sender:alice payload:…)
fkube -> bob:         Message(from:alice to:bob payload:…)
end

...eventually...
== Alice leaves smoothly ==
autonumber inc A
alice -> akube:       Join(s:s0 p:alice).close()
akube -[#red]> psn:   Unsub(topic:swarm/s0)
akube -[#red]> psn:   Unsub(topic:host/akube)
akube -[#blue]> psn:  Pub(topic:swarm/s0 peer_left:alice)
psn -[#blue]> fkube:  Pub(topic:swarm/s0 peer_left:alice)
fkube -> bob:         Join(s:s0 p:bob).PeerLeft(peer:alice)
alice -> akube:       Subscribe(p:alice).close()
akube -[#red]> psn:   Unsub(topic:peer/alice)
deactivate akube
...eventually...
== Charlie joins ==
autonumber inc A
charlie -> fkube:     ReceiveMessages(key:charlie)
fkube -[#green]> psn: Sub(topic:peer/charlie)
charlie -> fkube:     Join(swarm:s0 peer:charlie)
fkube -[#blue]> psn:  Pub(topic:swarm/s0 peer_available:charlie timeout:600 announceBackTo:fkube)
fkube -> bob:         Join(s:s0 p:bob).PeerAvailable(peer:charlie)
...eventually...
== The family's kube reannounces Bob ==
autonumber inc A
fkube -> fkube:       <i>previous announcement times out</i>
fkube -[#blue]> psn:  Pub(topic:swarm/s0 peer_available:bob timeout:600)
...eventually...
== Bob leaves unexpectedly ==
autonumber inc A
bob X-X fkube:       <i>disconnect</i>
fkube -> fkube:      <i>timeout waiting for return</i>
fkube -[#red]> psn:  Unsub(topic:peer/bob)
fkube -[#blue]> psn: Pub(topic:swarm/s0 peer_left:bob)
fkube -> charlie:    Join(s:s0 p:charlie).PeerLeft(peer:bob)
...eventually...
== The family's kube shuts down ==
autonumber inc A
fkube -> charlie:    Join(s:s0 p:charlie).Close()
fkube -[#red]> psn:  Unsub(topic:swarm/s0)
fkube -[#blue]> psn: Pub(topic:swarm/s0 peer_left:charlie)
fkube -> charlie:    ReceiveMessages(key:charlie).Close()
fkube -[#red]> psn:  Unsub(topic:peer/charlie)
fkube X-X charlie:   <i>disconnect</i>
fkube -[#red]> psn:  Unsub(topic:host/fkube)
deactivate fkube
@enduml
