//
// Copyright 2025 DXOS.org
//

import { type AiError, AiLanguageModel, type AiResponse, type AiTool, AiToolkit } from '@effect/ai';
import { Array, Chunk, Context, Effect, Option, Queue, type Schema, Stream, String, pipe } from 'effect';

import {
  type AiInputPreprocessingError,
  AiParser,
  AiPreprocessor,
  type AiToolNotFoundError,
  ToolExecutionService,
  ToolResolverService,
  callTools,
  getToolCalls,
} from '@dxos/ai';
import { type Blueprint } from '@dxos/blueprints';
import { todo } from '@dxos/debug';
import { Obj } from '@dxos/echo';
import { ObjectVersion } from '@dxos/echo-db';
import { type ObjectId } from '@dxos/echo-schema';
import { DatabaseService } from '@dxos/functions';
import { log } from '@dxos/log';
import { type ContentBlock, DataType } from '@dxos/schema';
import { isNotFalsy, trim } from '@dxos/util';

import { AiAssistantError } from '../errors';

export type AiSessionOptions = {};

export type SessionRunParams<Tools extends AiTool.Any> = {
  prompt: string;
  system?: string;
  history?: DataType.Message[];
  objects?: Obj.Any[]; // TODO(burdon): Meta only (typename and id -- write to binder).
  blueprints?: Blueprint.Blueprint[];
  toolkit?: AiToolkit.AiToolkit<Tools>;
};

/**
 * Contains message history, tools, current context.
 * Current context means the state of the app, time of day, and other contextual information.
 * It makes requests to the model, its a state machine.
 * It keeps track of the current goal.
 * It manages the context window.
 * Tracks the success criteria of reaching the goal, exposing metrics (stretch).
 * Could be run locally in the app or remotely.
 * Could be personal or shared.
 */
export class AiSession {
  // TODO(burdon): Review this.
  private readonly _semaphore = Effect.runSync(Effect.makeSemaphore(1));

  /** Blocks streaming from the model during the session. */
  public readonly blockQueue = Effect.runSync(Queue.unbounded<Option.Option<ContentBlock.Any>>());

  /** Complete messages fired during the session, both from the model and from the user. */
  public readonly messageQueue = Effect.runSync(Queue.unbounded<DataType.Message>());

  /** Unparsed events from the underlying generation stream. */
  public readonly eventQueue = Effect.runSync(Queue.unbounded<AiResponse.Part>());

  /** Pending messages (incl. the current user request). */
  private _pending: DataType.Message[] = [];

  /** Prior history from queue. */
  private _history: DataType.Message[] = [];

  constructor(private readonly _options: AiSessionOptions = {}) {}

  /**
   * Runs the AI model loop interacting with tools and artifacts.
   * @returns The messages generated by the session, including the user's prompt.
   */
  // TODO(dmaretskyi): Toolkit context doesn't get added to the effect type.
  run = <Tools extends AiTool.Any>(
    params: SessionRunParams<Tools>,
  ): Effect.Effect<
    DataType.Message[],
    AiAssistantError | AiInputPreprocessingError | AiToolNotFoundError | AiError.AiError,
    AiLanguageModel.AiLanguageModel | ToolResolverService | ToolExecutionService | AiTool.ToHandler<Tools>
  > =>
    Effect.gen(this, function* () {
      // Create toolkit.
      const toolkitWithHandlers = yield* createToolkit(params);

      // Generate system prompt.
      // TODO(budon): Dynamically fill variables.
      const system = yield* formatSystemPrompt(params);

      // Generate user prompt.
      const promptMessages = yield* formatUserPrompt(params);
      yield* this.messageQueue.offer(promptMessages);

      this._history = [...(params.history ?? [])];
      this._pending = [promptMessages];

      // Potential tool-use loop.
      do {
        log.info('request', {
          prompt: promptMessages,
          system: { snippet: [system.slice(0, 32), '...', system.slice(-32)].join(''), length: system.length },
          pending: this._pending.length,
          history: this._history.length,
          objects: params.objects?.length ?? 0,
          toolkit: Object.values(toolkitWithHandlers.tools).map((tool: AiTool.Any) => tool.name),
        });

        // Generate the prompt and make request.
        const prompt = yield* AiPreprocessor.preprocessAiInput([...this._history, ...this._pending]);
        const blocks = yield* AiLanguageModel.streamText({
          prompt,
          system,
          toolkit: toolkitWithHandlers,
          disableToolCallResolution: true,
        }).pipe(
          AiParser.parseResponse({
            onBlock: (block) => this.blockQueue.offer(Option.some(block)),
            onPart: (part) => this.eventQueue.offer(part),
          }),
          Stream.runCollect,
          Effect.map(Chunk.toArray),
        );

        // TODO(burdon): Comment.
        yield* this.blockQueue.offer(Option.none());

        // TODO(burdon): Comment.
        const response = Obj.make(DataType.Message, {
          created: new Date().toISOString(),
          sender: { role: 'assistant' },
          blocks,
        });
        this._pending.push(response);
        yield* this.messageQueue.offer(response);

        // TODO(burdon): Comment.
        const toolCalls = getToolCalls(response);
        if (toolCalls.length === 0) {
          break;
        }

        // TODO(burdon): Comment.
        // TODO(burdon): Error handling.
        const toolResults = yield* callTools(toolCalls, toolkitWithHandlers as any);
        const toolResultMessage = Obj.make(DataType.Message, {
          created: new Date().toISOString(),
          sender: { role: 'user' },
          blocks: toolResults,
        });
        this._pending.push(toolResultMessage);
        yield* this.messageQueue.offer(toolResultMessage);
      } while (true);

      // The queues shutting down signals to stream consumers that the session has completed and no more messages are coming.
      yield* Queue.shutdown(this.eventQueue);
      yield* Queue.shutdown(this.blockQueue);
      yield* Queue.shutdown(this.messageQueue);

      log.info('done', { pending: this._pending.length });
      return this._pending;
    }).pipe(this._semaphore.withPermits(1), Effect.withSpan('AiSession.run'));

  // TODO(burdon): Implement.
  async runStructured<S extends Schema.Schema.AnyNoContext>(
    _schema: S,
    _options: SessionRunParams<AiTool.Any>,
  ): Promise<Schema.Schema.Type<S>> {
    return todo();
    // const parser = structuredOutputParser(schema);
    // const result = await this.run({
    //   ...options,
    //   executableTools: [...(options.executableTools ?? []), parser.tool],
    // });
    // return parser.getResult(result);
  }
}

// TODO(burdon): Convert util below to `Effect.fn` (to preserve stack info).

/**
 * Build a combined toolkit from the blueprint tools and the provided toolkit.
 */
const createToolkit = <Tools extends AiTool.Any>({
  blueprints = [],
  toolkit,
}: Pick<SessionRunParams<Tools>, 'blueprints' | 'toolkit'>) =>
  Effect.gen(function* () {
    const blueprintToolkit = yield* ToolResolverService.resolveToolkit(blueprints.flatMap(({ tools }) => tools));
    const blueprintToolkitHandler: Context.Context<AiTool.ToHandler<AiTool.Any>> = yield* blueprintToolkit.toContext(
      ToolExecutionService.handlersFor(blueprintToolkit),
    );

    return yield* AiToolkit.merge(...[toolkit, blueprintToolkit].filter(isNotFalsy)).pipe(
      Effect.provide(blueprintToolkitHandler),
    ) as Effect.Effect<AiToolkit.ToHandler<any>, never, AiTool.ToHandler<Tools>>;
  });

/**
 * Formats the system prompt.
 */
// TODO(burdon): Move to AiPreprocessor.
const formatSystemPrompt = ({
  system,
  blueprints,
  objects = [],
}: Pick<SessionRunParams<any>, 'system' | 'blueprints' | 'objects'>) =>
  Effect.gen(function* () {
    const blueprintDefs = yield* pipe(
      blueprints ?? [],
      Effect.forEach((blueprint) => Effect.succeed(blueprint.instructions)),
      Effect.flatMap(Effect.forEach((template) => DatabaseService.load(template.source))),
      Effect.map(
        Array.map(
          (template) => trim`
            <blueprint>
              ${template.content.trim()}
            </blueprint>
          `,
        ),
      ),
      Effect.map((blueprints) => (blueprints.length > 0 ? `## Blueprints:\n\n${blueprints}\n` : '')),
    );

    const objectDefs = yield* pipe(
      objects,
      Effect.forEach((object) =>
        Effect.succeed(trim`
          <object>
            <dxn>${Obj.getDXN(object)}</dxn>
            <typename>${Obj.getTypename(object)}</typename>
          </object>
        `),
      ),
      Effect.map(Array.reduce('', String.concat)),
      Effect.map((context) => (context.length > 0 ? `## Context objects:\n\n${context}\n` : '')),
    );

    return yield* pipe(
      Effect.succeed([blueprintDefs, objectDefs]),
      Effect.map(Array.reduce(system ?? '', String.concat)),
    );
  });

/**
 * Formats the user prompt.
 */
// TODO(burdon): Move to AiPreprocessor.
const formatUserPrompt = ({ prompt, history = [] }: Pick<SessionRunParams<any>, 'prompt' | 'history'>) =>
  Effect.gen(function* () {
    const prelude: ContentBlock.Any[] = [];

    // TODO(dmaretskyi): Evaluate other approaches as `serviceOption` isn't represented in the type system.
    const artifactDiffResolver = yield* Effect.serviceOption(ArtifactDiffResolver);
    if (Option.isSome(artifactDiffResolver)) {
      const versions = gatherObjectVersions(history);

      const artifactDiff = yield* Effect.tryPromise({
        try: () =>
          artifactDiffResolver.value.resolve(
            [...versions.entries()].map(([id, version]) => ({ id, lastVersion: version })),
          ),
        catch: AiAssistantError.wrap('Artifact diff resolution error'),
      });

      log.info('version', { artifactDiff, versions });
      for (const [id, { version }] of [...artifactDiff.entries()]) {
        if (ObjectVersion.equals(version, versions.get(id)!)) {
          artifactDiff.delete(id);
          continue;
        }

        prelude.push({ _tag: 'anchor', objectId: id, version });
      }
      if (artifactDiff.size > 0) {
        prelude.push(createArtifactUpdateBlock(artifactDiff));
      }
    }

    return Obj.make(DataType.Message, {
      created: new Date().toISOString(),
      sender: { role: 'user' },
      blocks: [...prelude, { _tag: 'text', text: prompt }],
    });
  });

const gatherObjectVersions = (messages: DataType.Message[]): Map<ObjectId, ObjectVersion> => {
  const artifactIds = new Map<ObjectId, ObjectVersion>();
  for (const message of messages) {
    for (const block of message.blocks) {
      if (block._tag === 'anchor') {
        artifactIds.set(block.objectId, block.version as ObjectVersion);
      }
    }
  }

  return artifactIds;
};

const createArtifactUpdateBlock = (
  artifactDiff: Map<ObjectId, { version: ObjectVersion; diff?: string }>,
): ContentBlock.Any => {
  return {
    _tag: 'text',
    // TODO(dmaretskyi): Does this need to be a special content-block?
    disposition: 'artifact-update',
    text: `
      The following artifacts have been updated since the last message:
      ${[...artifactDiff.entries()]
        .map(([id, { diff }]) => `<changed-artifact id="${id}">${diff ? `\n${diff}` : ''}</changed-artifact>`)
        .join('\n')}
    `,
  };
};

/**
 * Resolves artifact ids to their versions.
 * Used to give the model a sense of the changes to the artifacts made by users during the conversation.
 * The artifacts versions are pinned in the history, and whenever the artifact changes in-between assistant's steps,
 * a diff is inserted into the conversation.
 *
 * Can be optionally provided to the session run call.
 */
// TODO(dmaretskyi): Convert to Context.Reference
export class ArtifactDiffResolver extends Context.Tag('@dxos/assistant/ArtifactDiffResolver')<
  ArtifactDiffResolver,
  ArtifactDiffResolver.Service
>() {}

export namespace ArtifactDiffResolver {
  export type Service = {
    resolve: (artifacts: { id: ObjectId; lastVersion: ObjectVersion }[]) => Promise<
      Map<
        ObjectId,
        {
          version: ObjectVersion;
          diff?: string;
        }
      >
    >;
  };
}
