//
// Copyright 2025 DXOS.org
//

import { type AiError, AiLanguageModel, type AiResponse, type AiTool, AiToolkit } from '@effect/ai';
import { Chunk, Context, Effect, Option, type Schema, Stream, pipe } from 'effect';
import { Array, String } from 'effect';

import {
  AiParser,
  AiPreprocessor,
  type AiToolNotFoundError,
  type GenerationStream,
  ToolExecutionService,
  ToolResolverService,
  callTool,
  getToolCalls,
  runTool,
  runTools,
  ToolExecutionService,
  ToolResolverService,
  type AgentStatus,
  type AiInputPreprocessingError,
  type AiToolNotFoundError,
  type GenerationStream,
} from '@dxos/ai';
import { Event } from '@dxos/async';
import { type Blueprint } from '@dxos/blueprints';
import { todo } from '@dxos/debug';
import { Obj } from '@dxos/echo';
import { ObjectVersion } from '@dxos/echo-db';
import { type ObjectId } from '@dxos/echo-schema';
import { DatabaseService } from '@dxos/functions';
import { log } from '@dxos/log';
import { type ContentBlock, DataType } from '@dxos/schema';

import { AiAssistantError } from '../errors';

export type AiSessionOptions = {};

export type SessionRunOptions<Tools extends AiTool.Any> = {
  prompt: string;
  history: DataType.Message[];
  systemPrompt?: string;
  toolkit?: AiToolkit.AiToolkit<Tools>;
  blueprints?: Blueprint.Blueprint[];
};

/**
 * Contains message history, tools, current context.
 * Current context means the state of the app, time of day, and other contextual information.
 * It makes requests to the model, its a state machine.
 * It keeps track of the current goal.
 * It manages the context window.
 * Tracks the success criteria of reaching the goal, exposing metrics (stretch).
 * Could be run locally in the app or remotely.
 * Could be personal or shared.
 */
// TODO(burdon): Rename module.
export class AiSession {
  // TODO(burdon): Move to conversation.
  private readonly _semaphore = Effect.runSync(Effect.makeSemaphore(1));

  /** Pending messages (incl. the current user request). */
  private _pending: DataType.Message[] = [];

  /** Current streaming response. */
  private _stream: GenerationStream | undefined;

  /** Prior history from queue. */
  private _history: DataType.Message[] = [];

  /**
   * New message.
   */
  public readonly message = new Event<DataType.Message>();

  /**
   * Complete block added to Message.
   */
  public readonly block = new Event<ContentBlock.Any>();

  /**
   * Update partial block (while streaming).
   */
  public readonly update = new Event<ContentBlock.Any>();

  /**
   * Unparsed events from the underlying generation stream.
   */
  public readonly streamEvent = new Event<AiResponse.Part>();

  /**
   * User prompt or tool result.
   */
  public readonly userMessage = new Event<DataType.Message>();

  /**
   * Agent self-reporting its status.
   * Triggered by the model.
   */
  public readonly statusReport = new Event<AgentStatus>();

  /**
   * Emits when the session is done.
   */
  public readonly done = new Event<void>();

  constructor(private readonly _options: AiSessionOptions = {}) {}

  /**
   * Runs the AI model loop interacting with tools and artifacts.
   * @param options - The session options.
   * @returns The messages generated by the session, including the user's prompt.
   */
  // TODO(dmaretskyi): Toolkit context doesn't get added to the effect type.
  run = <Tools extends AiTool.Any>(
    options: SessionRunOptions<Tools>,
  ): Effect.Effect<
    DataType.Message[],
    AiAssistantError | AiInputPreprocessingError | AiToolNotFoundError | AiError.AiError,
    AiLanguageModel.AiLanguageModel | ToolResolverService | ToolExecutionService | AiTool.ToHandler<Tools>
  > =>
    Effect.gen(this, function* () {
      this._history = [...options.history];

      const promptMessages = yield* this._formatUserPrompt(options.prompt, options.history);
      this._pending = [promptMessages];
      this.userMessage.emit(promptMessages);

      // Potential tool use loop.
      do {
        log.info('request', {
          pending: this._pending.length,
          history: this._history.length,
          tools: (Object.values(options.toolkit?.tools ?? {}) as AiTool.Any[]).map((tool: AiTool.Any) => tool.name),
        });

        const prompt = yield* AiPreprocessor.preprocessAiInput([...this._history, ...this._pending]);

        // Build system prompt from blueprint templates.
        // TODO(dmaretskyi): Loading BP from the Database should be done at the higher level. We need a type for the resolved blueprint.
        const blueprints = options.blueprints ?? [];
        const systemPrompt = yield* pipe(
          blueprints,
          Effect.forEach((blueprint) => Effect.succeed(blueprint.instructions)),
          Effect.flatMap(Effect.forEach((template) => DatabaseService.load(template.source))),
          Effect.map(Array.map((template) => `\n\n<blueprint>${template.content}</blueprint>`)),
          Effect.map(Array.reduce(options.systemPrompt ?? '', String.concat)),
        );

        // Build a combined toolkit from the blueprint tools and the provided toolkit.
        const blueprintToolkit = yield* ToolResolverService.resolveToolkit(blueprints.flatMap(({ tools }) => tools));
        const blueprintToolkitHandler: Context.Context<AiTool.ToHandler<AiTool.Any>> =
          yield* blueprintToolkit.toContext(yield* ToolExecutionService.handlersFor(blueprintToolkit));
        const toolkit = options.toolkit != null ? AiToolkit.merge(options.toolkit, blueprintToolkit) : blueprintToolkit;
        const toolkitWithBlueprintHandlers = yield* toolkit.pipe(
          Effect.provide(blueprintToolkitHandler) as any,
        ) as Effect.Effect<AiToolkit.ToHandler<any>, never, AiTool.ToHandler<Tools>>;

        log.info('run', {
          systemPrompt: [systemPrompt.slice(0, 32), '...', systemPrompt.slice(-32)].join(''),
          length: systemPrompt.length,
          tools: Object.keys(blueprintToolkit.tools),
        });

        const blocks = yield* AiLanguageModel.streamText({
          prompt,
          system: systemPrompt,
          toolkit: toolkitWithBlueprintHandlers,
          disableToolCallResolution: true,
        }).pipe(
          AiParser.parseResponse({
            onBlock: (block) =>
              Effect.gen(this, function* () {
                if (block.pending) {
                  this.update.emit(block);
                } else {
                  this.block.emit(block);
                }
              }),
            onPart: (part) =>
              Effect.gen(this, function* () {
                this.streamEvent.emit(part);
              }),
          }),
          Stream.runCollect,
          Effect.map(Chunk.toArray),
        );

        // console.log(JSON.stringify(blocks, null, 2));
        const response = Obj.make(DataType.Message, {
          created: new Date().toISOString(),
          sender: { role: 'assistant' },
          blocks,
        });
        this._pending.push(response);
        this.message.emit(response);

        const toolCalls = getToolCalls(response);
        if (toolCalls.length === 0) {
          break;
        }

        const toolResults = yield* callTools(toolCalls, toolkitWithBlueprintHandlers as any);
        this._pending.push(
          Obj.make(DataType.Message, {
            created: new Date().toISOString(),
            sender: { role: 'user' },
            blocks: toolResults,
          }),
        );
      } while (true);

      log.info('done', { pending: this._pending.length });
      return this._pending;
    }).pipe(this._semaphore.withPermits(1), Effect.withSpan('AiSession.run'));

  async runStructured<S extends Schema.Schema.AnyNoContext>(
    _schema: S,
    _options: SessionRunOptions<AiTool.Any>,
  ): Promise<Schema.Schema.Type<S>> {
    return todo();
    // const parser = structuredOutputParser(schema);
    // const result = await this.run({
    //   ...options,
    //   executableTools: [...(options.executableTools ?? []), parser.tool],
    // });
    // return parser.getResult(result);
  }

  private _formatUserPrompt = (prompt: string, history: DataType.Message[]) =>
    Effect.gen(function* () {
      const prelude: ContentBlock.Any[] = [];

      // TODO(dmaretskyi): Evaluate other approaches as `serviceOption` isn't represented in the type system.
      const artifactDiffResolver = yield* Effect.serviceOption(ArtifactDiffResolver);
      if (Option.isSome(artifactDiffResolver)) {
        const versions = gatherObjectVersions(history);

        const artifactDiff = yield* Effect.tryPromise({
          try: () =>
            artifactDiffResolver.value.resolve(
              [...versions.entries()].map(([id, version]) => ({ id, lastVersion: version })),
            ),
          catch: AiAssistantError.wrap('Artifact diff resolution error'),
        });

        log.info('vision', {
          artifactDiff,
          versions,
        });

        for (const [id, { version }] of [...artifactDiff.entries()]) {
          if (ObjectVersion.equals(version, versions.get(id)!)) {
            artifactDiff.delete(id);
            continue;
          }

          prelude.push({ _tag: 'anchor', objectId: id, version });
        }
        if (artifactDiff.size > 0) {
          prelude.push(createArtifactUpdateBlock(artifactDiff));
        }
      }

      return Obj.make(DataType.Message, {
        created: new Date().toISOString(),
        sender: { role: 'user' },
        blocks: [...prelude, { _tag: 'text', text: prompt }],
      });
    });

  abort(): void {
    this._stream?.abort();
  }
}

const gatherObjectVersions = (messages: DataType.Message[]): Map<ObjectId, ObjectVersion> => {
  const artifactIds = new Map<ObjectId, ObjectVersion>();
  for (const message of messages) {
    for (const block of message.blocks) {
      if (block._tag === 'anchor') {
        artifactIds.set(block.objectId, block.version as ObjectVersion);
      }
    }
  }

  return artifactIds;
};

const createArtifactUpdateBlock = (
  artifactDiff: Map<ObjectId, { version: ObjectVersion; diff?: string }>,
): ContentBlock.Any => {
  return {
    _tag: 'text',
    // TODO(dmaretskyi): Does this need to be a special content-block?
    disposition: 'artifact-update',
    text: `
      The following artifacts have been updated since the last message:
      ${[...artifactDiff.entries()]
        .map(([id, { diff }]) => `<changed-artifact id="${id}">${diff ? `\n${diff}` : ''}</changed-artifact>`)
        .join('\n')}
    `,
  };
};

/**
 * Resolves artifact ids to their versions.
 * Used to give the model a sense of the changes to the artifacts made by users during the conversation.
 * The artifacts versions are pinned in the history, and whenever the artifact changes in-between assistant's steps,
 * a diff is inserted into the conversation.
 *
 * Can be optionally provided to the session run call.
 */
// TODO(dmaretskyi): Convert to Context.Reference
export class ArtifactDiffResolver extends Context.Tag('@dxos/assistant/ArtifactDiffResolver')<
  ArtifactDiffResolver,
  ArtifactDiffResolver.Service
>() {}

export namespace ArtifactDiffResolver {
  export type Service = {
    resolve: (artifacts: { id: ObjectId; lastVersion: ObjectVersion }[]) => Promise<
      Map<
        ObjectId,
        {
          version: ObjectVersion;
          diff?: string;
        }
      >
    >;
  };
}

