version: 1

runtime:
  client:
    storage:
      persistent: true
      dataRoot: /tmp/dx/run
    useReactiveObjectApi: true

  services:
    ipfs:
      server: https://dx.dev.kube.dxos.org/ipfs/api
      gateway: https://dx.dev.kube.dxos.org/ipfs/gateway
    signaling:
      - server: wss://dx.dev.kube.dxos.org/.well-known/dx/signal
      - server: wss://staging.kube.dxos.org/.well-known/dx/signal
    ice:
      - urls: stun:dx.dev.kube.dxos.org:3478
      - urls: turn:dx.dev.kube.dxos.org:3478
        username: dxos
        credential: dxos
    publisher:
      server: wss://dx.dev.kube.dxos.org/.well-known/dx/deploy
    supervisor:
      server: wss://dx.dev.kube.dxos.org/.well-known/dx/supervisor
    tunneling:
      server: wss://dx.dev.kube.dxos.org/.well-known/dx/tunnel
