//
// Copyright 2026 DXOS.org
//

import React from 'react';

import { type VariantContent } from '#surfaces';

import { useVariantSource } from '../../hooks';
import { toEmbedUrl } from './embed-url-parsers';

export type VideoVariantProps = {
  variant: VariantContent;
};

/**
 * Default `VariantRenderer` for `video/*`. Materialized content (uploaded/generated `File`, resolved
 * to a `blob:`/`data:` URL) plays in a `<video>` element; an external provider/source URL is embedded
 * via an iframe (YouTube/Vimeo/direct), reusing {@link toEmbedUrl}.
 */
export const VideoVariant = ({ variant }: VideoVariantProps) => {
  const src = useVariantSource(variant);
  if (!src) {
    return null;
  }

  // Uploaded/generated bytes resolve to a blob:/data: URL — play directly.
  if (src.startsWith('blob:') || src.startsWith('data:')) {
    return <video src={src} controls className='block max-is-full bs-auto mli-auto rounded' />;
  }

  // External URL — derive an embeddable iframe src (provider-aware, falls back to the raw URL).
  const embedUrl = toEmbedUrl(src);
  if (!embedUrl) {
    return null;
  }
  return (
    <div className='is-full aspect-video'>
      <iframe
        className='is-full bs-full rounded'
        src={embedUrl}
        title={variant.generation?.prompt ?? 'video'}
        allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture'
        allowFullScreen
      />
    </div>
  );
};

VideoVariant.displayName = 'VideoVariant';
