//
// Copyright 2026 DXOS.org
//

import { type Page } from '@playwright/test';

import { type NetworkMetrics } from '../types.ts';

/** Extensions that are the app itself arriving, whatever the request's declared type. */
const CODE_EXTENSIONS = /\.(m?js|cjs|ts|tsx|css|wasm|woff2?|ttf|map|html)(\?|$)/i;

/** Playwright resource types that are the app being loaded rather than used. */
const CODE_RESOURCE_TYPES: ReadonlySet<string> = new Set([
  'document',
  'script',
  'stylesheet',
  'font',
  'image',
  'manifest',
  'other',
]);

/** Resource types that are traffic generated by using the app. */
const API_RESOURCE_TYPES: ReadonlySet<string> = new Set(['fetch', 'xhr', 'websocket', 'eventsource']);

/**
 * The subset of {@link API_RESOURCE_TYPES} that is a REQUEST rather than a stream.
 *
 * A socket and an eventsource each produce one `response` — the handshake — and then carry their
 * traffic outside it, so counting either as an edge request would report a connection as a call
 * and double-count traffic `edgeSocketFrames` already has.
 */
export const EDGE_REQUEST_RESOURCE_TYPES: ReadonlySet<string> = new Set(['fetch', 'xhr']);

type Bucket = 'code' | 'api' | 'other';

/**
 * Hosts that are the app's own backend. Suffix-matched, so `dxos.network` covers
 * `dev.dxos.network` and `preview.dxos.network` without listing every deployment.
 *
 * The default is the `runtime.services.edge.url` host of `dx.yml`, which is what a `vite preview`
 * build over the production config actually talks to. Overridable because a run against a local
 * worker is a different host and would otherwise classify as third party.
 */
const DEFAULT_EDGE_HOSTS: readonly string[] = ['dxos.network', 'dxos.workers.dev'];

/**
 * Telemetry endpoints, kept OUT of the edge columns.
 *
 * Analytics rides the same `fetch` resource type as a real API call, so without this the backend
 * columns silently include however much PostHog happened to flush during a stage — which is both
 * noise and not the app's cost.
 */
const ANALYTICS_HOSTS: readonly string[] = [
  'posthog.com',
  'i.posthog.com',
  'sentry.io',
  'ingest.sentry.io',
  'segment.io',
  'segment.com',
  'google-analytics.com',
  'googletagmanager.com',
  'doubleclick.net',
];

export type NetworkOrigin = 'edge' | 'analytics' | 'other';

const hostOf = (url: string): string => {
  try {
    return new URL(url).hostname.toLowerCase();
  } catch {
    return '';
  }
};

const matchesSuffix = (host: string, suffixes: readonly string[]): boolean =>
  suffixes.some((suffix) => host === suffix || host.endsWith(`.${suffix}`));

/**
 * Which party a URL belongs to.
 *
 * Analytics is tested FIRST: an analytics endpoint hosted on an edge subdomain would otherwise
 * count as backend traffic, and a reverse proxy for telemetry is a normal arrangement.
 */
export const classifyOrigin = (url: string, edgeHosts: readonly string[] = DEFAULT_EDGE_HOSTS): NetworkOrigin => {
  const host = hostOf(url);
  if (!host) {
    return 'other';
  }
  if (matchesSuffix(host, ANALYTICS_HOSTS)) {
    return 'analytics';
  }
  return matchesSuffix(host, edgeHosts) ? 'edge' : 'other';
};

/** Byte length of a frame payload, which Playwright gives as text or binary. */
const frameBytes = (payload: string | Buffer): number =>
  typeof payload === 'string' ? Buffer.byteLength(payload, 'utf8') : payload.byteLength;

/**
 * Which half of the budget a response belongs to.
 *
 * Resource type first and extension second, because the classification that matters is intent:
 * a `fetch` for a `.wasm` chunk is still the app loading, while a `fetch` to the edge worker is
 * the app running. A bare `other` with no code extension is left unclassified rather than guessed
 * into one of the two columns the trend is read from.
 */
export const classify = (url: string, resourceType: string): Bucket => {
  if (CODE_EXTENSIONS.test(url)) {
    return 'code';
  }
  if (API_RESOURCE_TYPES.has(resourceType)) {
    return 'api';
  }
  if (CODE_RESOURCE_TYPES.has(resourceType)) {
    return resourceType === 'other' ? 'other' : 'code';
  }
  return 'other';
};

const EMPTY: NetworkMetrics = {
  codeBytes: 0,
  apiBytes: 0,
  otherBytes: 0,
  requests: 0,
  apiRequests: 0,
  edgeApiBytes: 0,
  edgeApiRequests: 0,
  edgeSocketBytes: 0,
  edgeSocketFrames: 0,
  analyticsBytes: 0,
};

export type TrackNetworkOptions = {
  /** Suffix-matched hosts treated as the app's backend; defaults to the `dx.yml` edge host. */
  edgeHosts?: readonly string[];
};

/**
 * Accumulates classified network traffic for the page's lifetime, readable as a running total.
 *
 * Two listeners, because one cannot see the whole picture:
 *
 * - `response` gives bytes per request, taken from `content-length` where the header is present
 *   and from the body otherwise — the resource-timing buffer caps out on a graph this size, so the
 *   response event is the only complete accounting.
 * - `websocket` gives FRAME bytes in both directions, which no `response` reports: a socket
 *   produces exactly one response, the 101 with an empty body.
 *
 * `options.edgeHosts` names the app's own backend, suffix-matched; it defaults to the `dx.yml`
 * edge host and is worth overriding for a run against a local worker. The returned function is a
 * snapshot, so a caller can diff two of them across a stage boundary.
 */
export const trackNetwork = (page: Page, options: TrackNetworkOptions = {}): (() => NetworkMetrics) => {
  const totals: NetworkMetrics = { ...EMPTY };
  const edgeHosts = options.edgeHosts ?? DEFAULT_EDGE_HOSTS;

  // Frame-level, because a socket fires exactly one `response` — the 101, with an empty body — so
  // every byte ECHO replicates is invisible to the handler below. Frames are counted in both
  // directions: a sync is a conversation, and an upload regression is as real as a download one.
  page.on('websocket', (socket) => {
    if (classifyOrigin(socket.url(), edgeHosts) !== 'edge') {
      return;
    }
    const count = (payload: string | Buffer) => {
      totals.edgeSocketBytes += frameBytes(payload);
      totals.edgeSocketFrames += 1;
    };
    socket.on('framesent', (frame) => count(frame.payload));
    socket.on('framereceived', (frame) => count(frame.payload));
  });

  page.on('response', async (response) => {
    const request = response.request();
    const bucket = classify(response.url(), request.resourceType());
    const origin = classifyOrigin(response.url(), edgeHosts);
    const resourceType = request.resourceType();
    totals.requests += 1;
    if (bucket === 'api') {
      totals.apiRequests += 1;
      // A socket handshake is in the `api` bucket but is NOT a request: counting it here would
      // report a connection as a call, and its traffic is already in `edgeSocketFrames`.
      if (origin === 'edge' && EDGE_REQUEST_RESOURCE_TYPES.has(resourceType)) {
        totals.edgeApiRequests += 1;
      }
    }
    try {
      const header = response.headers()['content-length'];
      let bytes = header ? parseInt(header, 10) || 0 : 0;
      if (!header) {
        const body = await response.body().catch(() => null);
        bytes = body?.byteLength ?? 0;
      }
      if (bucket === 'code') {
        totals.codeBytes += bytes;
      } else if (bucket === 'api') {
        totals.apiBytes += bytes;
      } else {
        totals.otherBytes += bytes;
      }
      // Origin is orthogonal to the code/API split, so it accumulates separately rather than
      // partitioning the columns above — the bundle is served from the same host as the API in a
      // deployed build, and `codeBytes` must keep meaning the whole bundle.
      if (origin === 'analytics') {
        totals.analyticsBytes += bytes;
      } else if (origin === 'edge' && bucket === 'api' && EDGE_REQUEST_RESOURCE_TYPES.has(resourceType)) {
        // Gated on the same set as the counter above, so bytes and requests describe the same
        // population. A handshake body is empty, so this changes no number today — it stops the
        // two columns diverging the day a socket upgrade starts carrying one.
        totals.edgeApiBytes += bytes;
      }
    } catch {
      // Redirects and preflights have no readable body; the request is still counted above.
    }
    // Reading a body is async, so a response that arrives just before a stage boundary can be
    // counted against the next stage. Bounded to responses without `content-length` — in a
    // `vite preview` run that is API traffic, not the bundle.
  });

  return () => ({ ...totals });
};

/** Difference of two running totals — the bytes and requests a single stage accounted for. */
export const diffNetwork = (before: NetworkMetrics, after: NetworkMetrics): NetworkMetrics => ({
  codeBytes: after.codeBytes - before.codeBytes,
  apiBytes: after.apiBytes - before.apiBytes,
  otherBytes: after.otherBytes - before.otherBytes,
  requests: after.requests - before.requests,
  apiRequests: after.apiRequests - before.apiRequests,
  edgeApiBytes: after.edgeApiBytes - before.edgeApiBytes,
  edgeApiRequests: after.edgeApiRequests - before.edgeApiRequests,
  edgeSocketBytes: after.edgeSocketBytes - before.edgeSocketBytes,
  edgeSocketFrames: after.edgeSocketFrames - before.edgeSocketFrames,
  analyticsBytes: after.analyticsBytes - before.analyticsBytes,
});
