//
// Copyright 2026 DXOS.org
//

import { type Page } from '@playwright/test';

import { type NetworkMetrics } from '../types.ts';

/** Extensions that are the app itself arriving, whatever the request's declared type. */
const CODE_EXTENSIONS = /\.(m?js|cjs|ts|tsx|css|wasm|woff2?|ttf|map|html)(\?|$)/i;

/** Playwright resource types that are the app being loaded rather than used. */
const CODE_RESOURCE_TYPES: ReadonlySet<string> = new Set([
  'document',
  'script',
  'stylesheet',
  'font',
  'image',
  'manifest',
  'other',
]);

/** Resource types that are traffic generated by using the app. */
const API_RESOURCE_TYPES: ReadonlySet<string> = new Set(['fetch', 'xhr', 'websocket', 'eventsource']);

type Bucket = 'code' | 'api' | 'other';

/**
 * Which half of the budget a response belongs to.
 *
 * Resource type first and extension second, because the classification that matters is intent:
 * a `fetch` for a `.wasm` chunk is still the app loading, while a `fetch` to the edge worker is
 * the app running. A bare `other` with no code extension is left unclassified rather than guessed
 * into one of the two columns the trend is read from.
 */
export const classify = (url: string, resourceType: string): Bucket => {
  if (CODE_EXTENSIONS.test(url)) {
    return 'code';
  }
  if (API_RESOURCE_TYPES.has(resourceType)) {
    return 'api';
  }
  if (CODE_RESOURCE_TYPES.has(resourceType)) {
    return resourceType === 'other' ? 'other' : 'code';
  }
  return 'other';
};

const EMPTY: NetworkMetrics = { codeBytes: 0, apiBytes: 0, otherBytes: 0, requests: 0, apiRequests: 0 };

/**
 * Accumulates classified response bytes for the page's lifetime, readable as a running total.
 *
 * Content-length where the header is present and the body otherwise, matching
 * `harness-helpers.trackNetwork` — the resource-timing buffer caps out on a graph this size, so
 * the response event is the only complete accounting.
 */
export const trackNetwork = (page: Page): (() => NetworkMetrics) => {
  const totals: NetworkMetrics = { ...EMPTY };

  page.on('response', async (response) => {
    const request = response.request();
    const bucket = classify(response.url(), request.resourceType());
    totals.requests += 1;
    if (bucket === 'api') {
      totals.apiRequests += 1;
    }
    try {
      const header = response.headers()['content-length'];
      let bytes = header ? parseInt(header, 10) || 0 : 0;
      if (!header) {
        const body = await response.body().catch(() => null);
        bytes = body?.byteLength ?? 0;
      }
      if (bucket === 'code') {
        totals.codeBytes += bytes;
      } else if (bucket === 'api') {
        totals.apiBytes += bytes;
      } else {
        totals.otherBytes += bytes;
      }
    } catch {
      // Redirects and preflights have no readable body; the request is still counted above.
    }
    // Reading a body is async, so a response that arrives just before a stage boundary can be
    // counted against the next stage. Bounded to responses without `content-length` — in a
    // `vite preview` run that is API traffic, not the bundle.
  });

  return () => ({ ...totals });
};

/** Difference of two running totals — the bytes and requests a single stage accounted for. */
export const diffNetwork = (before: NetworkMetrics, after: NetworkMetrics): NetworkMetrics => ({
  codeBytes: after.codeBytes - before.codeBytes,
  apiBytes: after.apiBytes - before.apiBytes,
  otherBytes: after.otherBytes - before.otherBytes,
  requests: after.requests - before.requests,
  apiRequests: after.apiRequests - before.apiRequests,
});
