version: 1

runtime:
  services:
    ipfs:
      server: "http://testing.kube.dxos.org:5001/"
      gateway: "http://testing.kube.dxos.org:8888/ipfs"
    signaling:
      - server: 'wss://testing.kube.dxos.org/.well-known/dx/signal'
    ice:
      - urls: 'stun:testing.kube.dxos.org:3478'
      - urls: 'turn:testing.kube.dxos.org:3478'
        username: 'dxos'
        credential: 'dxos'
    publisher:
      server: 'wss://testing.kube.dxos.org/.well-known/dx/deploy'
