name: Setup
description: Setup the environment for the other workflows

runs:
  using: 'composite'
  steps:
    # TODO(wittjosiah): This shouldn't be necessary, but it is when running in BuildJet.
    #   It's not clear why, the Docker image is setup for the user to own the workspace.
    #   The checkout action also already runs this internally as a step as well.
    - name: Mark workspace as safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      shell: bash

    # TODO(wittjosiah): Install moon in docker image?
    - uses: moonrepo/setup-toolchain@v0

    - name: Log out debug info
      run: |
        node --version
        pnpm --version
        bun --version
      shell: bash

    - name: PNPM Store Path
      id: pnpm-store
      run: echo "pnpm-store=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get Node version
      id: node-version
      run: echo "version=$(node --version)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store.outputs.pnpm-store }}
        key: ${{ runner.os }}-node-${{ steps.node-version.outputs.version }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.node-version.outputs.version }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm set verify-store-integrity false
        pnpm install --prefer-offline
      shell: bash

    # Native Node.js modules (like better-sqlite3) contain compiled C++ code
    # that is tied to a specific Node.js ABI version (NODE_MODULE_VERSION).
    # When a native module doesn't have prebuilt binaries for a particular
    # Node.js version (e.g., better-sqlite3 lacks Node 24.x prebuilts as of
    # January 2026), pnpm install may restore a cached binary compiled for
    # a different Node version, causing "NODE_MODULE_VERSION mismatch" errors.
    #
    # This rebuild step recompiles native modules from source for the current
    # Node.js version, ensuring ABI compatibility. It's safe to run even when
    # not strictly needed (it no-ops if binaries are already correct).
    #
    # Remove this step once all native dependencies ship prebuilts for all
    # Node versions in the test matrix.
    - name: Rebuild native modules
      run: pnpm rebuild better-sqlite3
      shell: bash
