name: Setup
description: Setup the environment for the other workflows

runs:
  using: 'composite'
  steps:
    - name: Log out debug info
      run: |
        node --version
        pnpm --version
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm set verify-store-integrity false
        pnpm install --prefer-offline
      shell: bash

    - uses: nrwl/nx-set-shas@v4
      if: ${{ !env.ACT }}

    - name: Configure nx for Act
      if: ${{ env.ACT }}
      run: |
        echo "NX_BASE=main" >> $GITHUB_ENV
        echo "NX_HEAD=HEAD" >> $GITHUB_ENV
      shell: bash
