name: Setup
description: Setup the environment for the other workflows

runs:
  using: 'composite'
  steps:
    # TODO(wittjosiah): This shouldn't be necessary, but it is when running in BuildJet.
    #   It's not clear why, the Docker image is setup for the user to own the workspace.
    #   The checkout action also already runs this internally as a step as well.
    - name: Mark workspace as safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      shell: bash

    # TODO(wittjosiah): Install moon in docker image?
    - uses: moonrepo/setup-toolchain@v0

    - name: Log out debug info
      run: |
        node --version
        pnpm --version
        bun --version
      shell: bash

    - name: PNPM Store Path
      id: pnpm-store
      run: echo "pnpm-store=$(pnpm store path)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store.outputs.pnpm-store }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm set verify-store-integrity false
        pnpm install --prefer-offline
      shell: bash
