name: Setup
description: Setup the environment for the other workflows

runs:
  using: 'composite'
  steps:
    # TODO(wittjosiah): This shouldn't be necessary, but it is when running in BuildJet.
    #   It's not clear why, the Docker image is setup for the user to own the workspace.
    - name: Mark workspace as safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      shell: bash

    - name: Log out debug info
      run: |
        node --version
        pnpm --version
        pnpm store path
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ env.PNPM_HOME }}/store
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm set verify-store-integrity false
        pnpm install --prefer-offline
      shell: bash

    - uses: nrwl/nx-set-shas@v4
      if: ${{ !env.ACT }}

    - name: Configure nx for Act
      if: ${{ env.ACT }}
      run: |
        echo "NX_BASE=main" >> $GITHUB_ENV
        echo "NX_HEAD=HEAD" >> $GITHUB_ENV
      shell: bash
