//
// Copyright 2026 DXOS.org
//

import * as Effect from 'effect/Effect';

/**
 * Common English words a model's tokenizer encodes as one token each, so a skill token costs the
 * caller one token to carry. Any edit, even an appended word, changes the modulus and so retires
 * every token already handed out.
 */
export const WORDS: readonly string[] = [
  'apple',
  'arrow',
  'badge',
  'baker',
  'beach',
  'bell',
  'berry',
  'bird',
  'blade',
  'block',
  'board',
  'boat',
  'bone',
  'book',
  'boot',
  'bottle',
  'brain',
  'branch',
  'bread',
  'brick',
  'bridge',
  'brush',
  'bucket',
  'butter',
  'cabin',
  'cable',
  'cake',
  'camera',
  'camp',
  'candle',
  'canvas',
  'card',
  'carpet',
  'castle',
  'chain',
  'chair',
  'chalk',
  'cheese',
  'cherry',
  'chest',
  'circle',
  'cloud',
  'clock',
  'coast',
  'coat',
  'coffee',
  'coin',
  'copper',
  'corner',
  'cotton',
  'cream',
  'crown',
  'desert',
  'desk',
  'diamond',
  'dinner',
  'dog',
  'door',
  'dragon',
  'drum',
  'eagle',
  'earth',
  'engine',
  'feather',
  'fence',
  'field',
  'finger',
  'fire',
  'flag',
  'flower',
  'forest',
  'fork',
  'fountain',
  'frame',
  'garden',
  'gate',
  'glass',
  'glove',
  'gold',
  'grape',
  'grass',
  'guitar',
  'hammer',
  'harbor',
  'hat',
  'heart',
  'helmet',
  'hill',
  'honey',
  'horse',
  'house',
  'island',
  'jacket',
  'jungle',
  'kettle',
  'key',
  'kitchen',
  'kite',
  'knife',
  'ladder',
  'lake',
  'lamp',
  'leaf',
  'lemon',
  'letter',
  'library',
  'light',
  'lion',
  'map',
  'marble',
  'market',
  'meadow',
  'metal',
  'mirror',
  'monkey',
  'moon',
  'mountain',
  'mouse',
  'needle',
  'nest',
  'ocean',
  'orange',
  'oven',
  'paint',
  'palace',
  'paper',
  'parrot',
  'pencil',
  'pepper',
  'piano',
  'picture',
  'pillow',
  'pilot',
  'planet',
  'plate',
  'pocket',
  'pond',
  'potato',
  'pumpkin',
  'puzzle',
  'queen',
  'rabbit',
  'radio',
  'rain',
  'river',
  'road',
  'robot',
  'rocket',
  'roof',
  'rope',
  'rose',
  'saddle',
  'sail',
  'salt',
  'sand',
  'school',
  'shadow',
  'sheep',
  'shell',
  'ship',
  'shirt',
  'shoe',
  'silver',
  'sky',
  'snake',
  'snow',
  'soap',
  'sock',
  'spider',
  'spoon',
  'spring',
  'square',
  'star',
  'station',
  'stone',
  'storm',
  'street',
  'sugar',
  'summer',
  'sun',
  'table',
  'tail',
  'teacher',
  'tent',
  'thread',
  'thunder',
  'tiger',
  'toast',
  'tomato',
  'tower',
  'tractor',
  'train',
  'tree',
  'truck',
  'tunnel',
  'turtle',
  'umbrella',
  'valley',
  'violin',
  'wagon',
  'wall',
  'wallet',
  'water',
  'whale',
  'wheel',
  'window',
  'winter',
  'wolf',
  'wood',
  'yellow',
  'zebra',
  'anchor',
  'basket',
  'beard',
  'blanket',
  'button',
  'carrot',
  'cave',
  'cloth',
  'compass',
  'cookie',
  'cup',
  'dolphin',
  'feast',
  'film',
  'fish',
  'fox',
  'frog',
  'hawk',
  'iron',
  'jar',
  'jewel',
  'lantern',
  'mask',
  'milk',
  'nail',
  'net',
  'owl',
  'pearl',
  'pine',
  'plant',
  'rice',
  'ring',
  'sword',
  'tea',
  'tile',
  'wire',
  'wing',
];

/**
 * Domain-separation label: the host's secret may be a credential with another job (EDGE passes its
 * service keypair), so the HMAC key is derived from it rather than used directly.
 */
const KEY_DERIVATION_LABEL = 'dxos-mcp-skill-token-v1';

const encoder = new TextEncoder();

/**
 * The word for one skill: `WORDS[HMAC(secret, skillKey) mod WORDS.length]`. Proof that the caller
 * read the skill, not a credential: one word in a few hundred is guessable, and that is acceptable.
 *
 * Computed per call rather than memoized, since a cached promise outlives the request that made it
 * on Workers.
 */
export const derive = (secret: string, skillKey: string): Effect.Effect<string> =>
  Effect.promise(async () => {
    const digest = await crypto.subtle.digest('SHA-256', encoder.encode(`${KEY_DERIVATION_LABEL}:${secret}`));
    const key = await crypto.subtle.importKey('raw', digest, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
    const signature = new DataView(await crypto.subtle.sign('HMAC', key, encoder.encode(skillKey)));
    return WORDS[signature.getUint32(0) % WORDS.length];
  });

/** Read leniently: a model may echo the word capitalized or padded. */
export const normalize = (token: string): string => token.trim().toLowerCase();

/** A secret for a host that keeps none, valid for as long as this process runs. */
export const randomSecret = (): string =>
  Array.from(crypto.getRandomValues(new Uint8Array(32)), (byte) => byte.toString(16).padStart(2, '0')).join('');
