# https://jamiemason.github.io/syncpack/config
peer: false
workspace: false
#source:
#  - 'packages/**/package.json'
semverGroups:
  - range: ^
    packages:
      - '**'
    dependencies:
      - '**'
  - range: ~
    packages:
      - '**'
    dependencies:
      - esbuild
      - '@swc-node/register'
versionGroups:
  - packages:
      - '@dxos/log-hook'
    dependencies:
      - '@swc/core'
  - packages:
      - '@dxos/*-monitor'
      - 'dxos-example-template'
    dependencies:
      - '@dxos/*'
  - packages:
      - '@dxos/cf-labs'
    dependencies:
      - '@vitest/*'
      - 'vitest'
sortFirst:
  - name
  - version
  - private
  - description
  - license
  - author
  - keywords
  - homepage
  - bugs
  - repository
  - type
  - bin
  - main
  - types
  - browser
  - files
  - exports
  - scripts
  - dependencies
  - devDependencies
  - peerDependencies
