peer: false
workspace: false
semverGroups:
  - range: ^
    packages:
      - '**'
    dependencies:
      - '**'
  - range: ~
    packages:
      - esbuild
      - '@swc-node/register'
    dependencies:
      - '**'
  - range: ''
    packages:
      - '**'
    dependencies:
      - nx
      - '@nwrl/*'
versionGroups:
  - packages:
      - '@dxos/docs'
    dependencies:
      - '@mdx-js/react'
sortFirst:
  - name
  - version
  - private
  - description
  - license
  - author
  - keywords
  - homepage
  - bugs
  - repository
  - type
  - bin
  - main
  - types
  - browser
  - files
  - exports
  - scripts
  - dependencies
  - devDependencies
  - peerDependencies
