#
# CodeCov Configuration
# https://docs.codecov.com/docs/codecovyml-reference
#

# Disable PR status checks for code coverage.
# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    project: off
    patch: off

flags:
  nodejs:
    paths:
      - '.*'
    # Assume coverage has not changed if a file is not touched.
    # https://docs.codecov.com/docs/carryforward-flags
    carryforward: true
