packages:
  - apps/experimental/*
  - apps/*
  - e2e/*
  - packages/bot/*
  - packages/common/*
  - packages/devtools/*
  - packages/echo/*
  - packages/gem/*
  - packages/gravity/*
  - packages/halo/*
  - packages/mesh/*
  - packages/sdk/*
  - tools/deprecated/*
  - tools/executors/*
  - tools/*
