packages:
  - docs
  - packages/**/*
  - tools/**/*
  - '!packages/experimental/kai-functions/**'
  - '!docs/src/templates/**'
  - '!tools/monitors/**'
  # TODO(wittjosiah): Stop builds from copying package.json into dist (i.e., kodama).
  - '!**/dist/**'
  - '!**/out/**'
