packages:
  - docs
  - packages/**/*
  - tools/**/*
  - '!packages/deprecated/**'
  - '!packages/experimental/plexus/**'
  - '!packages/sdk/examples/src/template'
  - '!**/build/**'
  - '!**/dist/**'
  - '!**/out/**'
