packages:
  - docs
  - packages/**/*
  - tools/**/*
  - vendor/**/*
  - '!packages/deprecated/**'
  - '!packages/sdk/examples/src/template'
  - '!**/build/**'
  - '!**/dist/**'
  - '!**/out/**'

# Do not disable.
strictPeerDependencies: true
