apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: gravity
  annotations:
    co.elastic.logs/enabled: "true"
    co.elastic.logs/fileset: access
    co.elastic.logs/json.overwrite_keys: "true" 
    co.elastic.logs/json.add_error_key: "true" 
    co.elastic.logs/json.expand_keys: "true"
spec:
  volumes:
    - name: gravity-pv-storage
      persistentVolumeClaim:
        claimName: gravity-pv-claim
  containers:
  - name: dxos-agent-host
    image: dxos-agent
    terminationMessagePath: "/tmp/dxos-agent-host"
    imagePullPolicy: Never
    resources:
      limits:
        memory: "2048Mi"
        cpu: "500m"
    env:
    - name: GRAVITY_TEST_SCENARIO
      value: "host"
    command: ["/dxos/dxos/packages/gravity/gravity-agent/run_agent.sh"]
    ports:
      - containerPort: 43430
    volumeMounts:
      - mountPath: "/tmp/gravity-results"
        name: gravity-pv-storage
  - name: dxos-agent-guest
    image: dxos-agent
    terminationMessagePath: "/tmp/dxos-agent-guest"
    imagePullPolicy: Never
    resources:
      limits:
        memory: "2048Mi"
        cpu: "500m"
    env:
    - name: GRAVITY_TEST_SCENARIO
      value: "guest"
    command: ["/dxos/dxos/packages/gravity/gravity-agent/run_agent.sh"]
    volumeMounts:
      - mountPath: "/tmp/gravity-results"
        name: gravity-pv-storage
  restartPolicy: Always


