//
// Copyright 2026 DXOS.org
//

/**
 * Class recipes shared by every binding (decision 8): plain functions fixed at build time, so a React and a Solid part
 * emit identical classes. Geometry and colour live in `theme/*.css`; recipes only name the rules.
 */

const FOCUS_RING = 'nx-focus-ring';

export const recipes = {
  container: () => 'nx-grid',
  scrollRoot: () => 'nx-scroll-root',
  scrollViewport: () => 'nx-scroll-viewport',
  block: () => 'nx-block',
  icon: () => 'nx-icon',
  typography: () => 'nx-typography',
  toolbar: () => 'nx-toolbar',
  toolbarScroll: () => 'nx-toolbar-scroll',
  toolbarText: () => 'nx-toolbar-text',
  toolbarLink: () => `nx-toolbar-link ${FOCUS_RING}`,
  group: () => 'nx-group',
  label: () => 'nx-label',
  input: () => `nx-control nx-input ${FOCUS_RING}`,
  inputRow: () => 'nx-control nx-input nx-input-row',
  inputField: () => 'nx-input-field',
  inputAdornment: () => 'nx-input-adornment',
  button: () => `nx-control nx-button ${FOCUS_RING}`,
  field: () => 'nx-field',
  fieldHeader: () => 'nx-field-header',
  fieldHelper: () => 'nx-field-helper',
  fieldError: () => 'nx-field-error',
  checkbox: () => 'nx-checkbox',
  checkboxControl: () => 'nx-checkbox-control',
  selectTrigger: () => `nx-control nx-select-trigger ${FOCUS_RING}`,
  popup: () => 'nx-popup',
  arrow: () => 'nx-arrow',
  arrowTip: () => 'nx-arrow-tip',
  selectItem: () => 'nx-select-item',
  dialogBackdrop: () => 'nx-dialog-backdrop',
  dialogPositioner: () => 'nx-dialog-positioner',
  dialogContent: () => 'nx-dialog',
  dialogHeader: () => 'nx-dialog-header',
  dialogTitle: () => 'nx-dialog-title',
  dialogDescription: () => 'nx-dialog-description',
  dialogBody: () => 'nx-dialog-body',
  dialogFooter: () => 'nx-dialog-footer',
  switch: () => 'nx-switch',
  switchControl: () => 'nx-switch-control',
  switchThumb: () => 'nx-switch-thumb',
  fieldsetRoot: () => 'nx-fieldset',
  fieldsetLegend: () => 'nx-fieldset-legend',
  image: () => 'nx-image',
  imageClickable: () => 'nx-image-clickable',
  cardRoot: () => 'nx-card',
  cardPoster: () => 'nx-card-poster',
  cardHeader: () => 'nx-card-header',
  cardTitle: () => 'nx-card-title',
  cardDescription: () => 'nx-card-description',
  cardClickable: () => `nx-card-clickable ${FOCUS_RING}`,
  cardSectionTitle: () => 'nx-card-section-title',
  cardRow: () => 'nx-card-row',
  cardRowContent: () => 'nx-card-row-content',
  cardRowTrailing: () => 'nx-card-row-trailing',
  cardLink: () => `nx-card-link ${FOCUS_RING}`,
  collapsible: () => 'nx-collapsible',
  collapsibleTrigger: () => `nx-collapsible-trigger ${FOCUS_RING}`,
  collapsibleIndicator: () => 'nx-collapsible-indicator',
  collapsibleContent: () => 'nx-collapsible-content',
  menuContent: () => 'nx-menu',
  submenuContent: () => 'nx-submenu',
  menuItem: () => 'nx-menu-item',
  menuItemText: () => 'nx-menu-item-text',
  menuShortcut: () => 'nx-menu-shortcut',
  menuIndicator: () => 'nx-menu-indicator',
  menuIndicatorCell: () => 'nx-menu-indicator-cell',
  popupGroupLabel: () => 'nx-popup-group-label',
  tooltipContent: () => 'nx-tooltip',
  textTooltip: () => 'nx-text-tooltip',
  textarea: () => `nx-control nx-input nx-textarea ${FOCUS_RING}`,
  dateField: () => 'nx-date-field',
  dateInput: () => 'nx-control nx-input nx-input-row nx-date-input',
  dateInputSegments: () => 'nx-date-input-segments',
  dateInputSegmentGroup: () => 'nx-date-input-segment-group',
  dateInputSegment: () => 'nx-date-input-segment',
  dateCalendar: () => 'nx-date-calendar',
  dateCalendarView: () => 'nx-date-calendar-view',
  dateCalendarHeader: () => 'nx-date-calendar-header',
  dateCalendarTitle: () => 'nx-date-calendar-title',
  dateCalendarTable: () => 'nx-date-calendar-table',
  dateCalendarCell: () => `nx-date-calendar-cell ${FOCUS_RING}`,
  popoverContent: () => 'nx-popover',
  popoverHeader: () => 'nx-popover-header',
  popoverTitle: () => 'nx-popover-title',
  popoverDescription: () => 'nx-popover-description',
  popoverBody: () => 'nx-popover-body',
  combobox: () => 'nx-combobox',
  comboboxControl: () => 'nx-control nx-combobox-control',
  comboboxInput: () => 'nx-combobox-input',
  comboboxTrigger: () => 'nx-combobox-trigger',
  comboboxEmpty: () => 'nx-combobox-empty',
  tag: () => 'nx-tag',
  separator: () => 'nx-separator',
  toggleGroup: () => 'nx-toggle-group',
} as const;
