//
// Copyright 2024 DXOS.org
//

// Direct subtle entry: the barrel also exports the sodium-backed key helpers.
import { subtleCrypto } from '@dxos/crypto/subtle';
import { PublicKey, SpaceId } from '@dxos/keys';
import { ComplexMap } from '@dxos/util';

const SPACE_IDS_CACHE = new ComplexMap<PublicKey, SpaceId>(PublicKey.hash);

const SPACE_IDS_FROM_DOCUMENT_CACHE = new Map<string, SpaceId>();

/**
 * Space keys are generated by creating a keypair, and then taking the first 20 bytes of the SHA-256 hash of the public key and encoding them to multibase RFC4648 base-32 format (prefixed with B, see Multibase Table).
 * Inspired by how ethereum addresses are derived.
 */
export const createIdFromSpaceKey = async (spaceKey: PublicKey): Promise<SpaceId> => {
  const cachedValue = SPACE_IDS_CACHE.get(spaceKey);
  if (cachedValue !== undefined) {
    return cachedValue;
  }

  const digest = await subtleCrypto.digest('SHA-256', spaceKey.asUint8Array() as Uint8Array<ArrayBuffer>);

  const bytes = new Uint8Array(digest).slice(0, SpaceId.byteLength);
  const spaceId = SpaceId.encode(bytes);
  SPACE_IDS_CACHE.set(spaceKey, spaceId);
  return spaceId;
};

/**
 * Derives a space id from the id of its space root document.
 *
 * Mirrors {@link createIdFromSpaceKey} so both derivations produce the same shape: SHA-256 over the
 * document id, truncated to `SpaceId.byteLength`, multibase RFC4648 base-32 encoded. The root
 * document is immutable, so the id it mints is stable for the life of the space.
 */
export const createIdFromRootDocumentId = async (documentId: string): Promise<SpaceId> => {
  const cachedValue = SPACE_IDS_FROM_DOCUMENT_CACHE.get(documentId);
  if (cachedValue !== undefined) {
    return cachedValue;
  }

  const digest = await subtleCrypto.digest('SHA-256', new TextEncoder().encode(documentId) as Uint8Array<ArrayBuffer>);

  const bytes = new Uint8Array(digest).slice(0, SpaceId.byteLength);
  const spaceId = SpaceId.encode(bytes);
  SPACE_IDS_FROM_DOCUMENT_CACHE.set(documentId, spaceId);
  return spaceId;
};
