//
// Copyright 2026 DXOS.org
//

import { defineConfig } from '../../../vite.base.config.ts';

export default defineConfig({
  entry: {
    'ns/AppSurface': 'src/AppSurface.ts',
    'ns/SettingsScope': 'src/SettingsScope.ts',
    'ns/PluginRegistryButton': 'src/PluginRegistryButton.ts',
    'ns/NotFoundArticle': 'src/NotFoundArticle.ts',
    'ns/ObjectCard': 'src/ObjectCard.ts',
    'ns/Hooks': 'src/Hooks.ts',
    'ns/HomeSection': 'src/HomeSection.ts',
    'ns/NamePopover': 'src/NamePopover.ts',
    'ns/CardSlot': 'src/CardSlot.ts',
    'ns/AttentionSigil': 'src/AttentionSigil.ts',
    'AppSurface': 'src/ui/components/app-surface.ts',
    'AttentionSigil': 'src/ui/components/AttentionSigil.tsx',
    'CardIconSlot': 'src/ui/components/CardIconSlot.tsx',
    'CardMenuSlot': 'src/ui/components/CardMenuSlot.tsx',
    'Hooks': 'src/ui/hooks/index.ts',
    'HomeSection': 'src/ui/components/HomeSection.tsx',
    'NamePopover': 'src/ui/components/NamePopover.tsx',
    'NotFoundArticle': 'src/ui/components/NotFoundArticle.tsx',
    'PluginRegistryButton': 'src/ui/components/PluginRegistryButton.tsx',
    'SettingsScope': 'src/ui/components/SettingsScope.tsx',
    'index': 'src/index.ts',
    'account/Account': 'src/account/Account.ts',
    'app-framework/AppCapabilities': 'src/app-framework/AppCapabilities.ts',
    'app-framework/Progress': 'src/app-framework/Progress.ts',
    'app-framework/ObservabilityMapping': 'src/app-framework/ObservabilityMapping.ts',
    'app-framework/AppCapability': 'src/app-framework/AppCapability.ts',
    'app-framework/Tour': 'src/app-framework/Tour.ts',
    'app-graph/AppNode': 'src/app-graph/AppNode.ts',
    'app-graph/AppNodeMatcher': 'src/app-graph/AppNodeMatcher.ts',
    'app-graph/TypeSection': 'src/app-graph/TypeSection.ts',
    'app/AppUpdate': 'src/app/AppUpdate.ts',
    'app/GraphPath': 'src/app/GraphPath.ts',
    'app/NativeOAuth': 'src/app/NativeOAuth.ts',
    'app/NativePasskey': 'src/app/NativePasskey.ts',
    'app/NavigationResolver': 'src/app/NavigationResolver.ts',
    'app/NotFound': 'src/app/NotFound.ts',
    'app/Translations': 'src/app/Translations.ts',
    'app/UrlPath': 'src/app/UrlPath.ts',
    'app/UrlResolution': 'src/app/UrlResolution.ts',
    'echo/AppAnnotation': 'src/echo/AppAnnotation.ts',
    'echo/AppMigrations': 'src/echo/AppMigrations.ts',
    'echo/AppSpace': 'src/echo/AppSpace.ts',
    'echo/TypeOptions': 'src/echo/TypeOptions.ts',
    'operations/CollaborationOperation': 'src/operations/CollaborationOperation.ts',
    'operations/CollectionOperation': 'src/operations/CollectionOperation.ts',
    'operations/LayoutOperation': 'src/operations/LayoutOperation.ts',
    'operations/NavigationOperation': 'src/operations/NavigationOperation.ts',
    'operations/SettingsOperation': 'src/operations/SettingsOperation.ts',
    'operations/SpaceInvitationOperation': 'src/operations/SpaceInvitationOperation.ts',
    'types/AppSettings': 'src/types/AppSettings.ts',
    'types/ConnectorSync': 'src/types/ConnectorSync.ts',
    'types/ContainerModel': 'src/types/ContainerModel.ts',
    'types/DefaultParent': 'src/types/DefaultParent.ts',
    'app-framework/AppActivationEvents': 'src/app-framework/AppActivationEvents.ts',
    'echo/Query': 'src/echo/Query.ts',
    'sample/SampleSpace': 'src/sample/SampleSpace.ts',
    'types': 'src/types/index.ts',
    'testing': 'src/testing/index.ts',
  },
  jsx: 'react',
  test: { node: true, storybook: true },
});
