//
// Copyright 2026 DXOS.org
//

import { type GitHubOperation } from '#types';

// Kept out of the story modules: react-refresh only fast-refreshes a module whose exports are all
// components.

/** The body of dxos/dxos#13348 as GitHub returned it: R2 demo media, the Claude Code footer and the preview block. */
export const PULL_REQUEST_13348_BODY = [
  "Hovering a PR pill in a task body showed no card when the PR could not be fetched. Now the card opens, titled with the pill's short name (`#1145`), and says **No preview available.**",
  '',
  '**Demo (before → after):** https://pub-39066a86073446d7b77b1c157b660bb5.r2.dev/demos/2026-09-23-artifact/pr-pill-hover-card.webm',
  '',
  '| Before | After |',
  '| --- | --- |',
  '| [before](https://pub-39066a86073446d7b77b1c157b660bb5.r2.dev/demos/2026-09-23-artifact/before.png) | [after](https://pub-39066a86073446d7b77b1c157b660bb5.r2.dev/demos/2026-09-23-artifact/after.png) |',
  '',
  '## Root cause',
  '',
  'The reported pill is `https://github.com/dxos/edge/pull/1145` in the Stability project. SigNoz shows every hover on the reporting device logging `github link preview failed` with a **404** from `api.github.com/repos/dxos/edge/pulls/1145`, exactly one per hover. That means only the anonymous attempt ran: the DXOS space holds no GitHub connection, and `dxos/edge` is private. The resolver therefore returned `undefined`, and `preview-popover.ts` returned without doing anything. The pill looked live but was dead.',
  '',
  'Hover handling in the task row itself is fine. The existing `DescriptionLinks` story, and the same flow driven with Playwright, both open the card when the link resolves.',
  '',
  '## Change',
  '',
  "- `plugin-preview` `preview-popover.ts`: when no resolver answers a link that some resolver *matches*, open a card popover with no subject. The title comes from the resolver's `linkLabel`, and the deck already renders `No preview available.` for a card with no subject. The fallback is gated on `isPreviewLink`, so anchor activations that `EditorMenuProvider` owns (those with no `eid`) still fall through untouched. The stale-activation check now runs before the fallback, so a late lookup cannot reopen a card after the pointer has left.",
  '- `plugin-testing` `Layout`: render the same no-preview body the deck does, so stories can show it.',
  '- `plugin-github` fixtures: links into a repo named `private` resolve to nothing, standing in for a private repo with no token.',
  '- `plugin-tasks` `TaskSetArticle` story `DescriptionLinkUnavailable`: hover a `acme/private` PR chip and expect the card with `#7` and `No preview available.` It **fails without the fix and passes with it**, verified in storybook.',
  '',
  '## Not in this PR',
  '',
  'Getting a real preview for `dxos/edge` PRs requires a GitHub connection in the DXOS space; that is data, not code. A card that says *why* (for example, "connect GitHub to preview private repositories") would be a follow-up in plugin-github.',
  '',
  '## Verification',
  '',
  '- `tsc --noEmit` is clean for plugin-preview, plugin-testing, plugin-github and plugin-tasks.',
  '- `oxlint` is clean and `oxfmt` has been applied to the changed files.',
  '- Storybook interactions: `DescriptionLinkUnavailable` PASS (FAIL with the fix reverted); `DescriptionLinks` still passes.',
  '',
  '🤖 Generated with [Claude Code](https://claude.com/claude-code)',
  '',
  'https://claude.ai/code/session_016GM9fXXzbrr6JGNeeQBCmj',
  '',
  '---',
  '_Generated by [Claude Code](https://claude.ai/code/session_016GM9fXXzbrr6JGNeeQBCmj)_',
  '',
  '<!-- composer-preview:begin -->',
  '---',
  '🚀 Composer preview: https://pr-13348-composer-dev.dxos.workers.dev',
  '<!-- composer-preview:end -->',
  '',
].join('\n');

const DEPOT = 'https://depot.dev/orgs/t8fblrl00n/workflows/hfxxpk92lm?repo=dxos%2Fdxos&job=';

const run = (
  name: string,
  conclusion: 'success' | 'skipped',
  job: string,
  startedAt: string,
  completedAt: string,
): GitHubOperation.CheckRun => ({
  name,
  outcome: conclusion,
  conclusion,
  url: `${DEPOT}${job}`,
  startedAt: `2026-09-23T${startedAt}Z`,
  completedAt: `2026-09-23T${completedAt}Z`,
});

/** The check runs on dxos/dxos#13348's head commit, as GitHub reported them. */
export const PULL_REQUEST_13348_RUNS: GitHubOperation.CheckRun[] = [
  run('Check / report', 'skipped', '7fh69tgb95', '12:59:47', '12:59:47'),
  run('Check / boot-budget-comment', 'success', 'c6p04pkb3t', '12:51:52', '12:51:55'),
  run('Check / test (node-version=24.11.1, shard=3)', 'success', '17h3h82gcs', '12:47:07', '12:51:45'),
  run('Check / test (node-version=24.11.1, shard=2)', 'success', 'nbqk52q3fm', '12:47:08', '12:53:40'),
  run('Check / e2e (browser=chromium, shard=rest)', 'success', 'gsf6kkw035', '12:47:06', '12:51:34'),
  run('Check / test (node-version=24.11.1, shard=5)', 'success', '0t4c6dtjn8', '12:47:08', '12:59:46'),
  run('Check / e2e (browser=webkit, shard=rest)', 'success', '9hl1kp2zwk', '12:47:07', '12:50:31'),
  run('Check / e2e (browser=chromium, shard=composer)', 'success', 'v7nlm01xnb', '12:47:08', '12:54:10'),
  run('Check / test (node-version=24.11.1, shard=4)', 'success', '9cqxpk0681', '12:47:07', '12:54:31'),
  run('Check / test (node-version=24.11.1, shard=1)', 'success', 'cfx86qgz5x', '12:47:07', '12:52:17'),
  run('Check / e2e (browser=firefox, shard=composer)', 'success', 'q9c9nw1w7p', '12:47:07', '12:52:34'),
  run('Check / test (node-version=24.11.1, shard=0)', 'success', '0mlw67znhz', '12:47:07', '12:51:53'),
  run('Check / boot-budget', 'success', 'b21gq1ptpd', '12:47:06', '12:51:46'),
  run('Check / e2e (browser=webkit, shard=composer)', 'success', 'vj4z932vgt', '12:47:06', '12:54:09'),
  run('Check / e2e (browser=firefox, shard=rest)', 'success', 'h9jbcv80ps', '12:47:05', '12:51:10'),
  run('Check / changeset-reminder', 'success', 'cd9102dxk7', '12:47:07', '12:47:21'),
  run('Check / check', 'success', '2qvs1jfpvc', '12:47:05', '12:51:13'),
  run('Check / memory', 'success', '04427k64lt', '12:47:06', '12:48:34'),
  run('Check / cli-foreign', 'skipped', 'q40pt3n8hc', '12:47:04', '12:47:04'),
  run('Check / cli', 'skipped', 'jx1fp4bz0f', '12:47:03', '12:47:03'),
  {
    ...run('Model Fixture / model-fixture', 'success', 'dj3hv8l8vw', '12:46:57', '12:50:07'),
    url: 'https://depot.dev/orgs/t8fblrl00n/workflows/h01tzcxkbp?repo=dxos%2Fdxos&job=dj3hv8l8vw',
  },
  {
    ...run('build', 'success', '', '12:46:56', '12:51:42'),
    url: 'https://github.com/dxos/dxos/actions/runs/35862669563/job/107186431578',
  },
];
