//
// Copyright 2026 DXOS.org
//

// Browser-safe tool contract — Effect Schema input definitions, static
// metadata, and the zod adapter the MCP SDK needs. No node:fs, no ts-morph,
// no MCP transport machinery — those live in @dxos/introspect-mcp.

export { type ListOptions, DEFAULT_LIST_LIMIT, MAX_LIST_LIMIT } from './limits';
export { type ToolMetadata, TOOL_METADATA, inputSchemaToZod } from './metadata';
export {
  type Capability,
  type Idiom,
  type IdiomHost,
  type IdiomHostKind,
  type Operation,
  type Package,
  type PackageDetail,
  type Plugin,
  type PluginDetail,
  type PluginId,
  type PluginsFile,
  type SchemaContribution,
  type SourceLocation,
  type Surface,
  type SymbolDetail,
  type SymbolInclude,
  type SymbolKind,
  type SymbolMatch,
  CapabilitySchema,
  IdiomHostKindSchema,
  IdiomHostSchema,
  IdiomSchema,
  OperationSchema,
  PackageDetailSchema,
  PackageSchema,
  PluginDetailSchema,
  PluginIdSchema,
  PluginSchema,
  SchemaSchema,
  SourceLocationSchema,
  SurfaceSchema,
  SymbolDetailSchema,
  SymbolIncludeSchema,
  SymbolKindSchema,
  SymbolMatchSchema,
} from './output-schemas';
export {
  type FindSymbolArgs,
  type GetPackageArgs,
  type GetSymbolArgs,
  type ListCapabilitiesArgs,
  type ListIdiomsArgs,
  type ListOperationsArgs,
  type ListPackagesArgs,
  type ListPluginsArgs,
  type ListSchemasArgs,
  type ListSurfacesArgs,
  type ListSymbolsArgs,
  type PickerKind,
  FindSymbolInput,
  GetPackageInput,
  GetSymbolInput,
  ListCapabilitiesInput,
  ListIdiomsInput,
  ListOperationsInput,
  ListOptionsInput,
  ListPackagesInput,
  ListPluginsInput,
  ListSchemasInput,
  ListSurfacesInput,
  ListSymbolsInput,
  PickerAnnotationId,
  getPicker,
} from './schemas';
