version: 1
runtime:
  services:
    ipfs:
      server: 'https://ipfs-pub1.kube.dxos.network'
    signal:
      server: 'wss://kube.dxos.org/.well-known/dx/signal'
    ice:
      - urls: 'turn:kube.dxos.org:3478'
        username: 'dxos'
        credential: 'dxos'
