//
// Copyright 2026 DXOS.org
//

import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Easing,
  Img,
  Sequence,
  interpolate,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';

import { COLORS, END_CARD, FONT_STACK, MONO_STACK, TIMING } from './brand.ts';

// Sound files are generated by `npm run sounds` (placeholders until the real sonic logo exists).
export const SOUND = {
  pulse: 'audio/pulse.wav',
  logo: 'audio/sonic-logo.wav',
};

const useLayout = () => {
  const { width, height } = useVideoConfig();
  const portrait = height > width;
  const u = Math.min(width, height) / 1080; // 1 at 1080p
  return {
    width,
    height,
    portrait,
    u,
    margin: portrait ? width * 0.09 : width * 0.104,
    lineSize: Math.round(96 * u * (portrait ? 0.92 : 1)),
  };
};

/** Seconds (from the start of the build) at which each word appears. */
export const wordTimes = (lines: string[]): number[][] => {
  const out: number[][] = [];
  let t = 0;
  for (const line of lines) {
    const words = line.split(' ');
    out.push(words.map((_, i) => t + i * TIMING.wordStep));
    t += (words.length - 1) * TIMING.wordStep + TIMING.lineGap + TIMING.wordStep;
  }
  return out;
};

/**
 * Black field, white type, one word at a time on hard cuts, a slow creep while
 * it holds, then a cut to black at `cutAt` seconds.
 */
export const WordBuild: React.FC<{ lines: string[]; cutAt: number; pulse?: boolean }> = ({
  lines,
  cutAt,
  pulse = true,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const { margin, lineSize, width } = useLayout();
  const t = frame / fps;
  const times = wordTimes(lines);
  const creep = interpolate(t, [0, cutAt], [0, -14], {
    easing: Easing.out(Easing.cubic),
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.ground }}>
      {t < cutAt && (
        <div
          style={{
            position: 'absolute',
            left: margin,
            width: width - margin * 2,
            top: '50%',
            transform: `translate(${creep}px, -50%)`,
            display: 'flex',
            flexDirection: 'column',
            gap: lineSize * 0.2,
          }}
        >
          {lines.map((line, li) => (
            <div
              key={li}
              style={{
                fontFamily: FONT_STACK,
                fontWeight: 500,
                fontSize: lineSize,
                lineHeight: 1.08,
                letterSpacing: '-0.01em',
                color: COLORS.main,
                textWrap: 'balance',
              }}
            >
              {line.split(' ').map((word, wi) => (
                <span key={wi} style={{ opacity: t >= times[li][wi] ? 1 : 0 }}>
                  {word}
                  {wi < line.split(' ').length - 1 ? ' ' : ''}
                </span>
              ))}
            </div>
          ))}
        </div>
      )}
      {pulse &&
        times.flat().map((s, i) =>
          s < cutAt ? (
            <Sequence key={i} from={Math.round(s * fps)} durationInFrames={Math.round(0.6 * fps)} layout='none'>
              <Audio src={staticFile(SOUND.pulse)} volume={0.8} />
            </Sequence>
          ) : null,
        )}
    </AbsoluteFill>
  );
};

/** Opening title: the DXOS logotype, larger than on the end card, fades in and holds. */
export const OpenTitle: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const { u, width } = useLayout();
  const opacity = interpolate(frame / fps, [0, TIMING.open.fadeIn], [0, 1], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp',
    easing: Easing.inOut(Easing.cubic),
  });
  // The lockup SVG is 2:1 with padding, so size it by width and keep it inside the frame on narrow formats.
  const markWidth = Math.min(width * 0.85, 1100 * u);

  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.ground, alignItems: 'center', justifyContent: 'center' }}>
      {END_CARD.markSrc ? (
        <Img src={staticFile(END_CARD.markSrc)} style={{ width: markWidth, display: 'block', opacity }} />
      ) : (
        <div
          style={{
            fontFamily: FONT_STACK,
            fontWeight: 500,
            fontSize: Math.round(320 * u),
            lineHeight: 1,
            letterSpacing: '0.04em',
            color: COLORS.main,
            opacity,
          }}
        >
          {END_CARD.markText}
        </div>
      )}
    </AbsoluteFill>
  );
};

/** DXOS mark lands, tagline follows, accent rule draws, call to action holds. */
export const EndCard: React.FC = () => {
  const frame = useCurrentFrame();
  const { fps, durationInFrames } = useVideoConfig();
  const { u, height, portrait } = useLayout();
  const t = frame / fps;
  const out = Easing.out(Easing.cubic);
  const clamp = { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' } as const;

  const markOpacity = interpolate(t, [0, 0.3], [0, 1], { ...clamp, easing: out });
  const markScale = interpolate(t, [0, 0.6], [0.9, 1], { ...clamp, easing: Easing.out(Easing.back(1.6)) });
  const tagT = interpolate(t, [0.55, 0.95], [0, 1], { ...clamp, easing: out });
  const ruleT = interpolate(t, [0.85, 1.25], [0, 1], { ...clamp, easing: out });
  const ctaT = interpolate(t, [1.05, 1.45], [0, 1], { ...clamp, easing: out });
  const breathe = interpolate(t, [0.6, durationInFrames / fps], [1, 1.012], clamp);

  const markSize = Math.round(220 * u * (portrait ? 1.05 : 1));

  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.ground, alignItems: 'center' }}>
      <div
        style={{
          position: 'absolute',
          top: height * (portrait ? 0.27 : 0.15),
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        }}
      >
        <div
          style={{
            opacity: markOpacity, // Breathe the mark only: scaling text by fractions of a percent makes the glyphs jitter frame to frame.
            transform: `scale(${markScale * breathe})`,
            transformOrigin: '50% 60%',
          }}
        >
          {END_CARD.markSrc ? (
            <Img
              src={staticFile(END_CARD.markSrc)}
              style={{ height: END_CARD.markHeight * u * (portrait ? 1.15 : 1), display: 'block' }}
            />
          ) : (
            <div
              style={{
                fontFamily: FONT_STACK,
                fontWeight: 500,
                fontSize: markSize,
                lineHeight: 1,
                letterSpacing: '0.04em',
                color: COLORS.main,
              }}
            >
              {END_CARD.markText}
            </div>
          )}
        </div>
        <div
          style={{
            // The logo SVG has padding below it, so pull the tagline up when using it.
            marginTop: (END_CARD.markSrc ? -30 : 36) * u,
            fontFamily: FONT_STACK,
            fontWeight: 500,
            fontSize: Math.round(64 * u),
            color: COLORS.second,
            opacity: tagT,
            transform: `translateY(${(1 - tagT) * 24 * u}px)`,
          }}
        >
          {END_CARD.tagline}
        </div>
        <div
          style={{
            marginTop: 34 * u,
            width: 240 * u,
            height: 4 * u,
            borderRadius: 2 * u,
            background: COLORS.accent,
            transform: `scaleX(${ruleT})`,
          }}
        />
      </div>
      <div
        style={{
          position: 'absolute',
          top: height * (portrait ? 0.72 : 0.76),
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          gap: 10 * u,
          opacity: ctaT,
          transform: `translateY(${(1 - ctaT) * 18 * u}px)`,
        }}
      >
        <div style={{ fontFamily: FONT_STACK, fontWeight: 500, fontSize: Math.round(40 * u), color: '#B8B8B8' }}>
          {END_CARD.cta}
        </div>
        <div style={{ fontFamily: MONO_STACK, fontSize: Math.round(40 * u), color: COLORS.second }}>{END_CARD.url}</div>
      </div>
      <Audio src={staticFile(SOUND.logo)} />
    </AbsoluteFill>
  );
};
