//
// Copyright 2026 DXOS.org
//

import { Schema } from 'effect';

import { Annotation, Type } from '@dxos/echo';

/**
 * Unit of knowledge generated by an agent.
 */
export const Memory = Schema.Struct({
  title: Schema.String,
  content: Schema.String,
}).pipe(
  Type.object({ typename: 'dxos.org/type/Memory', version: '0.1.0' }),
  Annotation.LabelAnnotation.set(['title']),
  Annotation.IconAnnotation.set({
    icon: 'ph--brain--regular',
    hue: 'pink',
  }),
);
export interface Memory extends Schema.Schema.Type<typeof Memory> {}
