layer: library
language: typescript
tags:
  - ts-build
  - ts-test
  - pack
tasks:
  build:
    deps:
      - compile-plugin
  compile-plugin:
    command: dx-compile
    args:
      - '--entryPoint=src/plugin/esbuild-plugin.ts'
      - '--entryPoint=src/plugin/rollup-plugin.ts'
      - '--entryPoint=src/plugin/vite-plugin.ts'
      - '--outputPath=dist/plugin'
      - '--platform=node'
    deps:
      - ^:build
      - ^:compile
      - dx-compile:compile
    inputs:
      - '@group(production)'
    outputs:
      - dist/plugin
