FROM cimg/base:2022.04

ENV NODE_VERSION 18.19.0
# https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#global-npm-dependencies
ENV NPM_CONFIG_PREFIX=/home/circleci/.npm-global
ENV PATH=$PATH:/home/circleci/.npm-global/bin

RUN mkdir -p ${NPM_CONFIG_PREFIX}/{bin,lib}

RUN curl -L -o node.tar.xz "https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.xz" && \
  sudo tar -xJf node.tar.xz -C /usr/local --strip-components=1 && \
  rm node.tar.xz && \
  sudo ln -s /usr/local/bin/node /usr/local/bin/nodejs

# NOTE: Keep playwright version in sync with the one in package.json
RUN sudo apt-get update \
  && sudo apt-get install -y libxtst-dev libpng++-dev libenchant-2-2 lsof rsync \
  && npx playwright@1.44.1 install-deps \
  && npm install -g pnpm@8.15.8

# Might be better to use the other image as a base, but keep versioning simpler.

# this is taken verbatim from https://github.com/CircleCI-Public/cimg-go/blob/main/1.21/Dockerfile
ENV GO_VER="1.21.7"

# Install packages needed for CGO
RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends \
		g++ \
		libc6-dev && \
	sudo rm -rf /var/lib/apt/lists/* && \
	[[ $(uname -m) == "x86_64" ]] && ARCH="amd64" || ARCH="arm64" && \
	curl -sSL "https://go.dev/dl/go${GO_VER}.linux-${ARCH}.tar.gz" | sudo tar -xz -C /usr/local/ && \
	mkdir -p /home/circleci/go/bin

ENV GOPATH /home/circleci/go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

# Install related tools
# renovate: datasource=github-releases depName=gotestyourself/gotestsum
ENV GOTESTSUM_VERSION=1.12.0
# renovate: datasource=github-releases depName=golangci/golangci-lint
ENV GOCI_LINT_VERSION=1.59.0
# renovate: datasource=github-releases depName=golang/vuln
ENV GOVULNCHECK_VERSION=1.1.0

RUN [[ $(uname -m) == "x86_64" ]] && ARCH="amd64" || ARCH="arm64" && \
	curl -sSL "https://github.com/gotestyourself/gotestsum/releases/download/v${GOTESTSUM_VERSION}/gotestsum_${GOTESTSUM_VERSION}_linux_${ARCH}.tar.gz" | \
	sudo tar -xz -C /usr/local/bin gotestsum && \
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v${GOCI_LINT_VERSION} && \
	go install "golang.org/x/vuln/cmd/govulncheck@v${GOVULNCHECK_VERSION}" && go clean -cache -modcache && rm -rf "${GOPATH}/pkg"
# end import from https://github.com/CircleCI-Public/cimg-go/blob/main/1.21/Dockerfile

ENV PROTOC_VER 3.20.3
RUN curl -o /tmp/protoc.zip -sSL https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-linux-$(uname -m).zip && \
	sudo unzip /tmp/protoc.zip -d /usr/local && \
	rm -f /tmp/protoc.zip

ENV PROTOC_GEN_GO_VER 1.33.0
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v${PROTOC_GEN_GO_VER}
