version: 1

runtime:
  client:
    storage:
      persistent: true
      dataRoot: '/tmp/dxos/cli/user-2'
    useReactiveObjectApi: true
  services:
    ipfs:
      server: 'https://ipfs-pub1.kube.dxos.network'
    signaling:
      - server: 'wss://kube.dxos.org/.well-known/dx/signal'
    ice:
      - urls: 'turn:kube.dxos.org:3478'
        username: 'dxos'
        credential: 'dxos'
