agents: 3
duration: 20000
iterationDelay: 2000
epochPeriod: 8
# measureNewAgentSyncTime: false
insertionSize: 128
operationCount: 20
signalArguments:
  - globalsubserver
showPNG: false
withReconnects: true
transport: SIMPLE_PEER
