agents: 4
swarmsPerAgent: 10
duration: 60000
transport: SIMPLE_PEER
targetSwarmTimeout: 10000
fullSwarmTimeout: 60000
iterationDelay: 1000
streamsDelay: 60000
signalArguments:
  - globalsubserver
repeatInterval: 5000
streamLoadInterval: 1
streamLoadChunkSize: 5000000
showPNG: true