name: Crab Nebula Release
description: Run a Crab Nebula release command

inputs:
  api-key:
    description: 'Cloud Release API key'
    required: true
  command:
    description: 'Cloud Release command'
    required: true
  application:
    description: 'Cloud Release application name'
    required: true
  framework:
    description: 'Cloud Release framework'
    default: 'tauri'
  working-directory:
    description: 'Working directory'
    default: '.'

runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/cn-channel
      # TODO(wittjosiah): Switch to production.
      if: github.ref_name != 'labs'
      id: release-channel

    - uses: crabnebula-dev/cloud-release@v0
      with:
        # TODO(wittjosiah): Switch to production.
        command: release ${{ inputs.command }} ${{ inputs.application }} --framework ${{ inputs.framework }}${{ github.ref_name != 'labs' && format(' --channel {0}', steps.release-channel.outputs.channel) || '' }}
        api-key: ${{ inputs.api-key }}
        working-directory: ${{ inputs.working-directory }}
