version: 1

runtime:
  client:
    edgeFeatures:
      echoReplicator: true
      feedReplicator: true
      signaling: true
      agents: true
    storage:
      persistent: true
      dataRoot: /tmp/dx/run

  services:
    edge:
      url: ws://localhost:8787/
    iceProviders:
      - urls: https://edge-production.dxos.workers.dev/ice
    ai:
      server: http://localhost:8788
    ipfs:
      server: https://api.ipfs.dxos.network/api/v0
      gateway: https://gateway.ipfs.dxos.network/ipfs

