version: 1

runtime:
  client:
    edgeFeatures:
      echoReplicator: true
      feedReplicator: true
      signaling: true
      agents: true
    storage:
      persistent: true
      dataRoot: /tmp/dx/test

  services:
    edge:
      url: wss://edge.dxos.workers.dev/
    iceProviders:
      - urls: https://edge-production.dxos.workers.dev/ice
    ai:
      server: https://ai-service.dxos.workers.dev
    ipfs:
      server: https://api.ipfs.dxos.network/api/v0
      gateway: https://gateway.ipfs.dxos.network/ipfs
