//
// Copyright 2026 DXOS.org
//

import * as LanguageModel from '@effect/ai/LanguageModel';
import * as Effect from 'effect/Effect';
import * as Layer from 'effect/Layer';

import { AiService } from '@dxos/ai';
import { Message } from '@dxos/types';
import { trim } from '@dxos/util';

import { type ModelPolicy, resolveModel } from '../model-policy';

// Per-message topic tagging (productized from the stories-brain research tagger): free-form lowercase
// topic tags plus a spam flag, generated by the AI service. Deterministic stages don't tag; this is
// the one LLM-bearing per-message classification the topics pipeline applies via `Mailbox.applyTag`.

export type TagResult = {
  readonly tags: string[];
  readonly spam: boolean;
};

const TAG_PROMPT = trim`
  Classify the following email. Assign between 1 and 5 short, lowercase, single-word topic tags
  (e.g. "invoice", "newsletter", "security", "personal"). Decide whether the email is spam or a
  cold marketing blast; if so include the tag "spam".
  Respond with ONLY a JSON object of the form {"tags": string[], "spam": boolean}.
`;

/** Parses the tag response leniently (models wrap JSON in prose); infers/dedups the spam tag. Pure. */
export const parseTagResult = (raw: string): TagResult => {
  const match = raw.match(/\{[\s\S]*\}/);
  if (!match) {
    return { tags: [], spam: false };
  }
  try {
    const parsed = JSON.parse(match[0]) as { tags?: unknown; spam?: unknown };
    const tags = Array.isArray(parsed.tags)
      ? parsed.tags.map((tag) => String(tag).toLowerCase()).filter((tag) => tag.length > 0)
      : [];
    const spam = parsed.spam === true || tags.includes('spam');
    return { tags: spam && !tags.includes('spam') ? [...tags, 'spam'] : tags, spam };
  } catch {
    return { tags: [], spam: false };
  }
};

/**
 * Tags a single message (topic tags + spam) via the AI service. The model comes from the `tag` stage
 * of the model policy (overridable per run). Degrades to no tags on timeout/error so one bad message
 * never fails the pipeline.
 */
export const tagMessage = (
  message: Message.Message,
  options: { readonly policy?: ModelPolicy } = {},
): Effect.Effect<TagResult, never, AiService.AiService> =>
  Effect.gen(function* () {
    const subject = String(message.properties?.subject ?? '');
    const raw = yield* LanguageModel.generateText({
      prompt: `${TAG_PROMPT}\n\nSubject: ${subject}\n\n${Message.extractText(message)}`,
    }).pipe(
      Effect.provide(AiService.model(resolveModel('tag', options.policy)).pipe(Layer.orDie)),
      Effect.timeout('30 seconds'),
      Effect.map((response) => response.text),
      Effect.orElse(() => Effect.succeed('')),
    );
    return parseTagResult(raw);
  });
