//
// Copyright 2026 DXOS.org
//

import * as LanguageModel from '@effect/ai/LanguageModel';
import * as Effect from 'effect/Effect';
import * as Layer from 'effect/Layer';

import { AiService } from '@dxos/ai';
import { Message } from '@dxos/types';
import { trim } from '@dxos/util';

import { type ModelPolicy, resolveModel } from '../model-policy';

// Per-message topic tagging (productized from the stories-brain research tagger): free-form lowercase
// topic tags plus a spam flag, generated by the AI service. Deterministic stages don't tag; this is
// the one LLM-bearing per-message classification the topics pipeline applies via `Mailbox.applyTag`.

export type TagResult = {
  readonly tags: string[];
  readonly spam: boolean;
  /** No-action automated mail (receipts, logins, confirmations) — distinct from spam and from action-required mail. */
  readonly bulk: boolean;
};

const TAG_PROMPT = trim`
  Classify the following email. Assign between 1 and 5 short, lowercase, single-word topic tags
  (e.g. "invoice", "newsletter", "security", "personal"). Decide whether the email is spam or a
  cold marketing blast; if so include the tag "spam".
  Decide whether the email is "bulk" — automated, no-action mail such as receipts, login or
  security notices, order/shipping confirmations, or newsletters. If so include the tag "bulk".
  Do NOT tag invoices, payment requests, or anything that needs a reply as "bulk".
  Respond with ONLY a JSON object of the form {"tags": string[], "spam": boolean}.
`;

// No-action transactional/automated mail — receipts, login/security notices, order & shipping
// confirmations, newsletters. These get a `bulk` tag (nothing for the user to do), distinct from
// spam (unsolicited) and from invoices / payment requests (which DO require action).
const BULK_SUBJECT_RE =
  /\b(receipts?|your (order|purchase|receipt)|order (confirmation|placed|shipped|#)|(has )?shipped|out for delivery|tracking (number|info)|sign[-\s]?in|log[-\s]?in|new login|verify( your)?|verification code|confirm your (email|address)|password reset|welcome to|newsletter|digest|weekly (update|digest)|unsubscribe|subscription (confirmed|renewed))\b/i;

// Action-required financial mail — must NOT be classified bulk even when it looks automated.
const ACTION_SUBJECT_RE =
  /\b(invoices?|payment (due|request|reminder|required)|amount due|balance due|past due|overdue|outstanding balance|please pay|remittance|bill(ing)? (due|statement)|pay now)\b/i;

// Role / no-reply local parts that send automated no-action mail (used only when the subject gives no signal).
const BULK_LOCALPART_RE =
  /^(no-?reply|do-?not-?reply|receipts?|notifications?|notify|alerts?|updates?|news(letter)?|digest|mailer|postmaster)([._+-]|$)/i;

/**
 * Deterministic bulk / no-action signal from the subject + sender. Returns `'action'` when the mail
 * clearly requires a response (invoice / payment request) — such mail is never bulk even if it also
 * looks automated; `'bulk'` for no-action transactional / automated mail (receipts, login and
 * security notices, order confirmations, newsletters); `'unknown'` otherwise. Pure.
 */
export const classifyBulk = (input: {
  readonly subject?: string;
  readonly senderEmail?: string;
}): 'bulk' | 'action' | 'unknown' => {
  const subject = input.subject ?? '';
  if (ACTION_SUBJECT_RE.test(subject)) {
    return 'action';
  }
  if (BULK_SUBJECT_RE.test(subject)) {
    return 'bulk';
  }
  const localPart = (input.senderEmail ?? '').split('@')[0] ?? '';
  return BULK_LOCALPART_RE.test(localPart) ? 'bulk' : 'unknown';
};

/** Folds the deterministic bulk classification into a tag set: adds `bulk` for no-action mail, strips it for action-required mail. Pure. */
export const applyBulkTag = (tags: readonly string[], classification: 'bulk' | 'action' | 'unknown'): string[] => {
  if (classification === 'action') {
    return tags.filter((tag) => tag !== 'bulk');
  }
  if (classification === 'bulk' && !tags.includes('bulk')) {
    return [...tags, 'bulk'];
  }
  return [...tags];
};

/** Parses the tag response leniently (models wrap JSON in prose); infers/dedups the spam tag. Pure. */
export const parseTagResult = (raw: string): TagResult => {
  const match = raw.match(/\{[\s\S]*\}/);
  if (!match) {
    return { tags: [], spam: false, bulk: false };
  }
  try {
    const parsed = JSON.parse(match[0]) as { tags?: unknown; spam?: unknown };
    const tags = Array.isArray(parsed.tags)
      ? parsed.tags.map((tag) => String(tag).toLowerCase()).filter((tag) => tag.length > 0)
      : [];
    const spam = parsed.spam === true || tags.includes('spam');
    return {
      tags: spam && !tags.includes('spam') ? [...tags, 'spam'] : tags,
      spam,
      bulk: tags.includes('bulk'),
    };
  } catch {
    return { tags: [], spam: false, bulk: false };
  }
};

/**
 * Tags a single message (topic tags + spam) via the AI service. The model comes from the `tag` stage
 * of the model policy (overridable per run). Degrades to no tags on timeout/error so one bad message
 * never fails the pipeline.
 */
export const tagMessage = (
  message: Message.Message,
  options: { readonly policy?: ModelPolicy } = {},
): Effect.Effect<TagResult, never, AiService.AiService> =>
  Effect.gen(function* () {
    const subject = String(message.properties?.subject ?? '');
    const raw = yield* LanguageModel.generateText({
      prompt: `${TAG_PROMPT}\n\nSubject: ${subject}\n\n${Message.extractText(message)}`,
    }).pipe(
      Effect.provide(AiService.model(resolveModel('tag', options.policy)).pipe(Layer.orDie)),
      Effect.timeout('30 seconds'),
      Effect.map((response) => response.text),
      Effect.orElse(() => Effect.succeed('')),
    );
    const parsed = parseTagResult(raw);
    // Deterministic bulk gate overrides the model: it adds `bulk` for no-action mail the model missed
    // and strips it from invoices / payment requests the model wrongly tagged.
    const classification = classifyBulk({ subject, senderEmail: message.sender?.email });
    const tags = applyBulkTag(parsed.tags, classification);
    return { tags, spam: parsed.spam, bulk: tags.includes('bulk') };
  });
