//
// Copyright 2026 DXOS.org
//

import { type WidgetProps, type XmlWidgetRegistry, getXmlInnerText, getXmlTextChild } from '@dxos/ui-editor';

import {
  FallbackWidget,
  ReasoningWidget,
  ReferenceWidget,
  RequestWidget,
  SelectWidget,
  StatsWidget,
  StatusWidget,
  SuggestionWidget,
  SummaryWidget,
  SyntheticWidget,
  ToolWidget,
} from './widgets/index.ts';

/**
 * Floor for a portaled panel's collapsed height, reserved before its content paints. `heightMode:
 * 'min'` makes it a floor rather than a pin — without it the row is measured at the height of an
 * empty box and grows a frame later, a row moving under a reader scrolling up.
 */
const COLLAPSED_HEIGHT = 42;

/** An `<option>` child of a `<select>` tag, as the XML parser emits it. */
const isOption = (node: unknown): node is { _tag: 'option'; children?: WidgetProps['children'] } =>
  typeof node === 'object' && node !== null && '_tag' in node && node._tag === 'option';

/**
 * Widgets for the tags {@link createRenderer} emits.
 *
 * Host-extensible by spreading: the plugin adds its `surface` widget (which renders an
 * app-framework Surface this package must not depend on) over the fallback registered here.
 * DOM widgets render synchronously from the tag alone; React widgets are portaled and declare a
 * collapsed-height floor so the row's first measurement is honest.
 */
export const assistantRegistry: XmlWidgetRegistry = {
  // No widget: the reader's own words stay in the document, where they can be selected and
  // searched. Registered so the markdown parser keeps the tag as one block, and framed by the
  // chrome, not here.
  prompt: {
    block: true,
  },

  //
  // DOM widgets
  //

  reasoning: {
    block: true,
    streaming: true,
    factory: ({ children, range }) => {
      // `getXmlInnerText`: a model fences blocks in tags of its own, and `getXmlTextChild` would
      // stop at the first one — the reader saw a heading and an opening fence, then nothing.
      const text = getXmlInnerText(children ?? []);
      return text ? new ReasoningWidget(text, range?.from) : null;
    },
  },

  status: {
    block: true,
    streaming: true,
    factory: ({ children }) => {
      const text = getXmlTextChild(children ?? []);
      return text ? new StatusWidget(text) : null;
    },
  },

  reference: {
    block: false,
    factory: ({ children, ref }) => {
      const text = getXmlTextChild(children ?? []);
      return text && typeof ref === 'string' ? new ReferenceWidget(text, ref) : null;
    },
  },

  suggestion: {
    block: false,
    factory: ({ children }) => {
      const text = getXmlTextChild(children ?? []);
      return text ? new SuggestionWidget(text) : null;
    },
  },

  select: {
    block: true,
    factory: ({ children }) => {
      const options = (children ?? []).flatMap((option) => {
        const text = isOption(option) ? getXmlTextChild(option.children) : null;
        return text ? [text] : [];
      });
      return options.length ? new SelectWidget(options) : null;
    },
  },

  stats: {
    block: true,
    factory: ({ children }) => {
      const text = getXmlTextChild(children ?? []);
      return text ? new StatsWidget(text) : null;
    },
  },

  //
  // React widgets (portaled outside the editor)
  //

  toolkit: {
    block: true,
    streaming: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: ToolWidget,
  },

  // A "user"-turn message generated by the system (a trigger, an encoded event): meant to start the
  // agent without reading as the reader's own prompt.
  synthetic: {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: SyntheticWidget,
  },

  summary: {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: SummaryWidget,
  },

  request: {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: RequestWidget,
  },

  // The host overrides this with a widget that can actually dispatch the surface.
  surface: {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: FallbackWidget,
  },

  //
  // Fallback
  //

  json: {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: FallbackWidget,
  },
} as const;
