//
// Copyright 2026 DXOS.org
//

import { AnchorWidget, type XmlWidgetRegistry, getXmlInnerText, getXmlTextChild } from '@dxos/ui-editor';

import {
  FallbackWidget,
  ReasoningWidget,
  ReferenceWidget,
  SelectWidget,
  StatsWidget,
  StatusWidget,
  SuggestionWidget,
  SummaryWidget,
  SyntheticWidget,
  ToolWidget,
} from './widgets';

/**
 * Floor for a portaled panel's collapsed height, reserved before its content paints. `heightMode:
 * 'min'` makes it a floor rather than a pin — without it the row is measured at the height of an
 * empty box and grows a frame later, a row moving under a reader scrolling up.
 */
const COLLAPSED_HEIGHT = 42;

/**
 * Widgets for the tags {@link createRenderer} emits.
 *
 * Host-extensible by spreading: the plugin adds its `surface` widget (which renders an
 * app-framework Surface this package must not depend on) over the fallback registered here.
 * DOM widgets render synchronously from the tag alone; React widgets are portaled and declare a
 * collapsed-height floor so the row's first measurement is honest.
 */
export const assistantRegistry: XmlWidgetRegistry = {
  // No widget: the reader's own words stay in the document, where they can be selected and
  // searched. Registered so the markdown parser keeps the tag as one block, and framed by the
  // chrome, not here.
  'prompt': {
    block: true,
  },

  //
  // DOM widgets
  //

  'link-preview': {
    block: false,
    urlSchemes: ['dxn:', 'echo:'],
    factory: ({ label, dxn }) =>
      typeof label === 'string' && typeof dxn === 'string' ? new AnchorWidget(label, dxn) : null,
  },

  // A "user"-turn message generated by the system (a trigger, an encoded event): meant to start the
  // agent without reading as the reader's own prompt.
  'synthetic': {
    block: true,
    factory: ({ children }) => {
      // `getXmlInnerText`: a model fences blocks in tags of its own, and `getXmlTextChild` would
      // stop at the first one — the reader saw a heading and an opening fence, then nothing.
      const text = getXmlInnerText(children ?? []);
      return text ? new SyntheticWidget(text) : null;
    },
  },

  'reasoning': {
    block: true,
    streaming: true,
    factory: ({ children, range }) => {
      // `getXmlInnerText`: a model fences blocks in tags of its own, and `getXmlTextChild` would
      // stop at the first one — the reader saw a heading and an opening fence, then nothing.
      const text = getXmlInnerText(children ?? []);
      return text ? new ReasoningWidget(text, range?.from) : null;
    },
  },

  'status': {
    block: true,
    streaming: true,
    factory: ({ children }) => {
      const text = getXmlTextChild(children ?? []);
      return text ? new StatusWidget(text) : null;
    },
  },

  'reference': {
    block: false,
    factory: ({ children, ref }) => {
      const text = getXmlTextChild(children ?? []);
      return text && typeof ref === 'string' ? new ReferenceWidget(text, ref) : null;
    },
  },

  'suggestion': {
    block: false,
    factory: ({ children }) => {
      const text = getXmlTextChild(children ?? []);
      return text ? new SuggestionWidget(text) : null;
    },
  },

  'select': {
    block: true,
    factory: ({ children }) => {
      const options = (children ?? [])
        .map((option: any) => option?._tag === 'option' && getXmlTextChild(option.children))
        .filter(Boolean) as string[];
      return options.length ? new SelectWidget(options) : null;
    },
  },

  'stats': {
    block: true,
    factory: ({ children }) => {
      const text = getXmlTextChild(children ?? []);
      return text ? new StatsWidget(text) : null;
    },
  },

  //
  // React widgets (portaled outside the editor)
  //

  'toolkit': {
    block: true,
    streaming: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: ToolWidget,
  },

  'summary': {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: SummaryWidget,
  },

  // The host overrides this with a widget that can actually dispatch the surface.
  'surface': {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: FallbackWidget,
  },

  //
  // Fallback
  //

  'json': {
    block: true,
    estimatedHeight: () => COLLAPSED_HEIGHT,
    heightMode: 'min',
    Component: FallbackWidget,
  },
} as const;
