//
// Copyright 2026 DXOS.org
//

import { type Locator, type Page } from '@playwright/test';

import {
  type InboxHttpMock,
  type InboxHttpMockOptions,
  createInboxHttpMock,
} from '@dxos/plugin-inbox/testing/http-mock';

// Page-object for the inbox/mailbox surface. All selectors are data-testid (see the
// `browser-e2e-tests` skill); the credential-form fields are the one exception — they're
// schema-generated by `@dxos/react-ui-form` and carry no testid, so they're targeted by label.
export const Inbox = {
  /** The mailbox article surface. */
  mailbox: (page: Page): Locator => page.getByTestId('inbox.mailbox'),

  /** Message + conversation tiles in the list. */
  rows: (page: Page): Locator => page.getByTestId(/^inbox\.(message|conversation)\.row$/),

  /** Connect a JMAP account through the real credential form (host + fake token). */
  connectJmap: async (page: Page, { host, token, email }: { host: string; token: string; email?: string }) => {
    await page.getByTestId('connectorPlugin.connect').click();
    await page.getByTestId('connectorPlugin.connect.jmap-mail').click();
    await page.getByLabel('Server').fill(host);
    if (email) {
      await page.getByLabel('Email').fill(email);
    }
    await page.getByLabel('API token').fill(token);
    await page.getByTestId('save-button').click();
    // Once the connection is bound the toolbar swaps the connect button for a sync button.
    await page.getByTestId('inbox.mailbox.sync').waitFor();
  },

  /** Trigger a client-side sync. */
  sync: async (page: Page) => {
    await page.getByTestId('inbox.mailbox.sync').click();
  },

  /** Select the first thread; the message companion opens. */
  selectFirstThread: async (page: Page) => {
    await Inbox.rows(page).first().click();
    await page.getByTestId('message-header').first().waitFor();
  },

  /** Draft and send a reply to the currently-open thread. Reply-mode prefills the recipient. */
  reply: async (page: Page, body: string) => {
    // Reply lives in the message toolbar's "more" overflow (only Reply All is directly visible).
    await page.getByTestId('inbox.message.more').first().click();
    await page.getByTestId('inbox.message.reply').first().click();
    await page.getByTestId('edit-email-form').waitFor();
    // The body is a CodeMirror editor rendered as a sibling of the form (Form.Root puts the testid on
    // an inner element), and the reply draft is appended at the thread tail, so its editor is the last.
    const bodyEditor = page.locator('.cm-content').last();
    await bodyEditor.click();
    await bodyEditor.pressSequentially(body);
    await page.getByTestId('save-button').click();
  },
};

// Intercept the browser's provider HTTP and answer it from the fixture-backed mock. `page.route`
// only sees browser-originated requests, which is exactly the inbox sync/send path today (sync runs
// client-side). See the `inbox-e2e-sync-in-browser-dependency` note: when sync moves to the edge,
// this interception stops applying and an in-browser flag will be needed.
// The provider hosts are cross-origin to the app (localhost:4173), so fulfilled responses need CORS
// headers, and the JMAP POST (Authorization + JSON body) triggers a preflight OPTIONS. Handle both
// here in the transport layer so the mock stays a pure request→response data function.
const CORS_HEADERS = {
  'access-control-allow-origin': '*',
  'access-control-allow-methods': 'GET,POST,OPTIONS',
  'access-control-allow-headers': 'authorization,content-type',
};

export const installInboxMock = async (page: Page, options?: InboxHttpMockOptions): Promise<InboxHttpMock> => {
  const mock = createInboxHttpMock(options);
  await page.route(isMockedUrl, async (route) => {
    const request = route.request();
    if (request.method().toUpperCase() === 'OPTIONS') {
      return route.fulfill({ status: 204, headers: CORS_HEADERS });
    }

    const response = mock.handle({
      method: request.method(),
      url: request.url(),
      body: request.postData() ?? undefined,
    });
    if (!response) {
      // Not a request the mock owns — let it hit the network (or a later route).
      return route.fallback();
    }
    await route.fulfill({
      status: response.status,
      headers: { ...CORS_HEADERS, 'content-type': response.contentType },
      body: response.body,
    });
  });
  return mock;
};

/** URLs the inbox mock owns: Gmail REST, Gmail userinfo, JMAP discovery + the discovered api host. */
const isMockedUrl = (url: URL): boolean =>
  (url.hostname === 'gmail.googleapis.com' && url.pathname.startsWith('/gmail/v1/')) ||
  (url.hostname === 'www.googleapis.com' && url.pathname === '/oauth2/v3/userinfo') ||
  url.pathname === '/.well-known/jmap' ||
  url.hostname === 'jmap.test';
