//
// Copyright 2025 DXOS.org
//

import { type Meta, type StoryObj } from '@storybook/react-vite';
import React, { useEffect, useState } from 'react';

import { useSpaces } from '@dxos/react-client/echo';
import { withClientProvider } from '@dxos/react-client/testing';
import { Loading, withLayout, withTheme } from '@dxos/react-ui/testing';
import { Text } from '@dxos/schema';
import { trim } from '@dxos/util';

import { translations } from '#translations';
import { CodeProject, SourceFile, Spec } from '#types';

import { CodeArticle } from './CodeArticle';

const SEED_FILES = [
  {
    path: 'package.json',
    content:
      JSON.stringify(
        {
          name: '@example/my-plugin',
          version: '0.1.0',
          private: true,
          type: 'module',
          main: 'src/plugin.ts',
        },
        null,
        2,
      ) + '\n',
  },
  {
    path: 'src/plugin.ts',
    content:
      trim`
        //
        // Copyright 2026 DXOS.org
        //

        import { definePlugin } from '@dxos/app-framework';

        export const plugin = definePlugin({
          meta: {
            id: '@example/my-plugin',
            name: 'My Plugin',
          },
          ready: async () => {
            // Initialize plugin here.
          },
        });
      ` + '\n',
  },
  {
    path: 'src/components/Panel.tsx',
    content:
      trim`
        //
        // Copyright 2026 DXOS.org
        //

        import React from 'react';

        export const Panel = ({ title }: { title: string }) => (
          <section>
            <h2>{title}</h2>
          </section>
        );
      ` + '\n',
  },
  {
    path: 'README.md',
    content: '# my-plugin\n\nGenerated by the Coder blueprint.\n',
  },
];

const DefaultStory = () => {
  const spaces = useSpaces();
  const space = spaces[0];
  const [project, setProject] = useState<CodeProject.CodeProject | undefined>();

  useEffect(() => {
    if (space && !project) {
      const spec = space.db.add(Spec.make());
      const files = SEED_FILES.map((seed) => space.db.add(SourceFile.make(seed)));
      setProject(space.db.add(CodeProject.make({ name: 'Demo', spec, files })));
    }
  }, [space, project]);

  if (!project) {
    return <Loading />;
  }

  return <CodeArticle role='article' subject={project} attendableId='story' />;
};

const EmptyStory = () => {
  const spaces = useSpaces();
  const space = spaces[0];
  const [project, setProject] = useState<CodeProject.CodeProject | undefined>();

  useEffect(() => {
    if (space && !project) {
      const spec = space.db.add(Spec.make());
      setProject(space.db.add(CodeProject.make({ name: 'Empty', spec })));
    }
  }, [space, project]);

  if (!project) {
    return <Loading />;
  }

  return <CodeArticle role='article' subject={project} attendableId='story' />;
};

const meta = {
  title: 'plugins/plugin-code/containers/CodeArticle',
  decorators: [
    withClientProvider({
      createIdentity: true,
      createSpace: true,
      types: [Spec.Spec, CodeProject.CodeProject, SourceFile.SourceFile, Text.Text],
    }),
    withTheme(),
    withLayout({ layout: 'column', classNames: 'w-[60rem]' }),
  ],
  parameters: {
    layout: 'fullscreen',
    translations,
  },
} satisfies Meta;

export default meta;

type Story = StoryObj;

export const Default: Story = {
  render: () => <DefaultStory />,
};

export const Empty: Story = {
  render: () => <EmptyStory />,
};
