#!/usr/bin/env node
//
// Regenerates `src/internal/icon-data.ts` from the DXOS mark.
//
// The mark is embedded as base64 rather than served from an asset binding: it is ~2KB, and an HTTP
// host must serve it from its own origin, because the MCP specification tells clients to verify
// that an icon URI is same-origin as the server and to fetch it without credentials.
//
// Two variants because the mark is monochrome. A black mark is invisible on a dark UI and a white
// one on a light UI, so each is advertised with the `theme` it suits and clients pick.
//
// Usage: node scripts/generate-icon.mjs
//

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = resolve(PACKAGE_ROOT, '../../../..');
const SOURCE_SVG = join(REPO_ROOT, 'packages/ui/brand/assets/icons/dxos.svg');
const OUTPUT = join(PACKAGE_ROOT, 'src/internal/icon-data.ts');
const SIZE = 96;

// Ranks a store directory (`sharp@0.34.5`) by version; a lexical sort would put 0.9 above 0.34.
const rank = (dir) =>
  dir
    .slice('sharp@'.length)
    .split('.')
    .reduce((total, part) => total * 1000 + (Number.parseInt(part, 10) || 0), 0);

// sharp is a heavy native package and this generator runs about as often as the mark changes, so it
// is resolved from the workspace store rather than declared as a dependency every install pays for.
const loadSharp = () => {
  try {
    return require('sharp');
  } catch {
    const store = join(REPO_ROOT, 'node_modules/.pnpm');
    const [dir] = readdirSync(store)
      .filter((name) => name.startsWith('sharp@'))
      .sort((left, right) => rank(right) - rank(left));
    if (!dir) {
      throw new Error('sharp not found in the workspace; add it with `pnpm add -w -D sharp` and re-run');
    }
    return require(join(store, dir, 'node_modules/sharp'));
  }
};

const sharp = loadSharp();
const svg = readFileSync(SOURCE_SVG, 'utf8');

// Recoloured on the root element, which every shape inherits. Setting `fill` per `<path>` misses
// the mark's other shapes and renders a two-tone icon.
const withFill = (colour) => {
  const filled = svg.replace('fill="currentColor"', `fill="${colour}"`);
  if (filled === svg) {
    throw new Error(`${SOURCE_SVG} no longer declares fill="currentColor"; the recolour would be silent`);
  }
  return Buffer.from(filled);
};

const render = async (colour) => {
  const png = await sharp(withFill(colour), { density: 600 })
    .resize(SIZE, SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png({ compressionLevel: 9 })
    .toBuffer();
  return png.toString('base64');
};

const light = await render('#000000'); // dark mark, for light backgrounds
const dark = await render('#ffffff'); // light mark, for dark backgrounds

writeFileSync(
  OUTPUT,
  `//
// Copyright 2026 DXOS.org
//

//
// GENERATED by scripts/generate-icon.mjs -- do not edit by hand.
//
// The DXOS mark at ${SIZE}x${SIZE}, embedded so an HTTP host can serve it from its own origin: the
// MCP specification tells clients to verify that an icon URI is same-origin as the server, and to
// fetch it without credentials.
//
// Two variants because the mark is monochrome -- a black mark vanishes on a dark UI and a white one
// on a light UI. Each is advertised with the \`theme\` it suits, and the client picks.
//

export const ICON_SIZE = ${SIZE};

/** Dark mark, for light backgrounds. */
export const ICON_LIGHT_BASE64 = '${light}';

/** Light mark, for dark backgrounds. */
export const ICON_DARK_BASE64 = '${dark}';
`,
);

console.log(`wrote ${OUTPUT}`);
console.log(`  light variant: ${Math.round((light.length * 3) / 4)} bytes`);
console.log(`  dark variant:  ${Math.round((dark.length * 3) / 4)} bytes`);
