#!/usr/bin/env node
//
// Regenerates `src/internal/icon-data.ts` from the Composer mark.
//
// The mark is embedded as base64 rather than served from an asset binding: it is a few KB, and an
// HTTP host must serve it from its own origin, because the MCP specification tells clients to
// verify that an icon URI is same-origin as the server and to fetch it without credentials.
//
// Usage: node scripts/generate-icon.mjs
//

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = resolve(PACKAGE_ROOT, '../../../..');
const SOURCE_SVG = join(REPO_ROOT, 'packages/ui/brand/assets/icons/composer-icon.svg');
const OUTPUT = join(PACKAGE_ROOT, 'src/internal/icon-data.ts');
const SIZE = 96;

// Ranks a store directory (`sharp@0.34.5`) by version; a lexical sort would put 0.9 above 0.34.
const rank = (dir) =>
  dir
    .slice('sharp@'.length)
    .split('.')
    .reduce((total, part) => total * 1000 + (Number.parseInt(part, 10) || 0), 0);

// sharp is a heavy native package and this generator runs about as often as the mark changes, so it
// is resolved from the workspace store rather than declared as a dependency every install pays for.
const loadSharp = () => {
  try {
    return require('sharp');
  } catch {
    const store = join(REPO_ROOT, 'node_modules/.pnpm');
    const [dir] = readdirSync(store)
      .filter((name) => name.startsWith('sharp@'))
      .sort((left, right) => rank(right) - rank(left));
    if (!dir) {
      throw new Error('sharp not found in the workspace; add it with `pnpm add -w -D sharp` and re-run');
    }
    return require(join(store, dir, 'node_modules/sharp'));
  }
};

const sharp = loadSharp();
const svg = readFileSync(SOURCE_SVG);

const png = await sharp(svg, { density: 600 })
  .resize(SIZE, SIZE, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
  .png({ compressionLevel: 9 })
  .toBuffer();

// An ICO whose single entry is the PNG itself (valid since Windows Vista, read by every browser and
// favicon crawler), so `/favicon.ico` needs no second rasterisation.
const toIco = (image) => {
  const header = Buffer.alloc(22);
  header.writeUInt16LE(0, 0); // Reserved.
  header.writeUInt16LE(1, 2); // Type: icon.
  header.writeUInt16LE(1, 4); // Image count.
  header.writeUInt8(SIZE, 6); // Width.
  header.writeUInt8(SIZE, 7); // Height.
  header.writeUInt8(0, 8); // Palette size.
  header.writeUInt8(0, 9); // Reserved.
  header.writeUInt16LE(1, 10); // Colour planes.
  header.writeUInt16LE(32, 12); // Bits per pixel.
  header.writeUInt32LE(image.length, 14); // Image size.
  header.writeUInt32LE(header.length, 18); // Image offset.
  return Buffer.concat([header, image]);
};

const icon = png.toString('base64');
const favicon = toIco(png).toString('base64');

writeFileSync(
  OUTPUT,
  `//
// Copyright 2026 DXOS.org
//

//
// GENERATED by scripts/generate-icon.mjs -- do not edit by hand.
//
// The Composer mark at ${SIZE}x${SIZE}, embedded so an HTTP host can serve it from its own origin: the
// MCP specification tells clients to verify that an icon URI is same-origin as the server, and to
// fetch it without credentials.
//

export const ICON_SIZE = ${SIZE};

/** The mark as PNG; full colour, so one image suits light and dark UIs alike. */
export const ICON_BASE64 = '${icon}';

/** The same PNG wrapped as an ICO, for clients that brand a connector by the domain's favicon. */
export const FAVICON_BASE64 = '${favicon}';
`,
);

console.log(`wrote ${OUTPUT}`);
console.log(`  icon:    ${png.length} bytes`);
