//
// Copyright 2025 DXOS.org
//

import React from 'react';

import { log } from '@dxos/log';
import { ContentBlock, type Message } from '@dxos/types';
import { type XmlWidgetRegistry, getXmlTextChild } from '@dxos/ui-editor';

import { type BlockRenderer, type MessageThreadContext } from './sync';
import { applyToolBlockToWidgetState } from './tool-widget-state';
import {
  FallbackWidget,
  PromptWidget,
  ReasoningWidget,
  ReferenceWidget,
  SelectWidget,
  SuggestionWidget,
  StatsWidget,
  SummaryWidget,
  ToolWidget,
  StatusWidget,
} from './widgets';

/**
 * Custom XML tags registry.
 */
export const componentRegistry: XmlWidgetRegistry = {
  //
  // DOM Widgets
  //

  prompt: {
    block: true,
    factory: ({ children }) => {
      const text = getXmlTextChild(children);
      return text ? new PromptWidget(text) : null;
    },
  },
  synthetic: {
    block: true,
    factory: ({ children, range }) => {
      const text = getXmlTextChild(children);
      // TODO(dmaretskyi): Synthetic blocks are "user"-turn messages generated by the system, i.e. and event from a trigger, an email-encoded to JSON, etc.
      //                   They are meant to start agent, to process the event without looking like user-authored prompt.
      //                   Create a new widget type for them.
      return text ? new ReasoningWidget(text, range.from) : null;
    },
  },
  reasoning: {
    block: true,
    streaming: true,
    factory: ({ children, range }) => {
      const text = getXmlTextChild(children);
      return text ? new ReasoningWidget(text, range.from) : null;
    },
  },
  reference: {
    block: false,
    factory: ({ children, ref }) => {
      const text = getXmlTextChild(children);
      return text && ref ? new ReferenceWidget(text, ref) : null;
    },
  },
  select: {
    block: true,
    factory: ({ children }) => {
      const options = children
        ?.map((option: any) => option._tag === 'option' && getXmlTextChild(option.children))
        .filter(Boolean);
      return options?.length ? new SelectWidget(options) : null;
    },
  },
  suggestion: {
    block: true,
    factory: ({ children }) => {
      const text = getXmlTextChild(children);
      return text ? new SuggestionWidget(text) : null;
    },
  },
  stats: {
    block: true,
    factory: ({ children }) => {
      const text = getXmlTextChild(children);
      return text ? new StatsWidget(text) : null;
    },
  },
  status: {
    block: true,
    streaming: true,
    factory: ({ children, range }) => {
      const text = getXmlTextChild(children);
      return text ? new StatusWidget(text, range.from) : null;
    },
  },

  //
  // React Widgets (portaled outside of the editor)
  //

  summary: {
    block: true,
    Component: SummaryWidget,
  },
  toolCall: {
    block: true,
    Component: (props) => (
      <div role='none' className='py-2'>
        <ToolWidget {...props} />
      </div>
    ),
  },
  toolResult: {
    block: true,
    Component: FallbackWidget,
  },
  toolkit: {
    block: true,
    Component: FallbackWidget,
  },

  //
  // Fallback
  //

  json: {
    block: true,
    Component: FallbackWidget,
  },
};

/**
 * Convert block to markdown.
 */
export const blockToMarkdown: BlockRenderer = (
  context: MessageThreadContext,
  message: Message.Message,
  block: ContentBlock.Any,
) => {
  let str = blockToMarkdownImpl(context, message, block);
  if (str && !block.pending) {
    return (str += '\n');
  }

  return str;
};

const blockToMarkdownImpl = (context: MessageThreadContext, message: Message.Message, block: ContentBlock.Any) => {
  log('blockToMarkdown', { block: JSON.stringify(block) });
  switch (block._tag) {
    case 'text': {
      if (message.sender.role === 'user') {
        if (block.disposition === 'synthetic') {
          return renderXMLBlock('synthetic', { content: block.text, pending: block.pending });
        } else {
          return `<prompt>${block.text}</prompt>`;
        }
      } else {
        const text = block.text.trim();
        if (text.length > 0) {
          return text;
        }
      }
      break;
    }

    case 'reference': {
      if (block.pending) {
        return;
      }
      const dxn = block.reference.dxn;
      return `<reference ref="${dxn.toString()}">${context.getObjectLabel(dxn)}</reference>`;
    }

    case 'suggestion': {
      if (block.pending) {
        return;
      }
      return `<suggestion>${block.text}</suggestion>`;
    }

    case 'select': {
      if (block.pending || block.options.length === 0) {
        return;
      }
      return `<select>${block.options.map((option) => `<option>${option}</option>`).join('')}</select>`;
    }

    case 'toolCall': {
      applyToolBlockToWidgetState(context, block);
      return `<toolCall id="${block.toolCallId}" />`;
    }

    case 'toolResult': {
      // TODO(dmaretskyi): the parameter could be undefined, perhaps tool blocks are not arriving in order.
      applyToolBlockToWidgetState(context, block);
      break;
    }

    case 'stats': {
      return '';
    }

    case 'reasoning': {
      let text = block.reasoningText ?? block.redactedText;
      if (!text) {
        return;
      }
      return renderXMLBlock('reasoning', { content: text, pending: block.pending });
    }

    case 'summary': {
      return renderXMLBlock('summary', { content: block.content, pending: block.pending });
    }

    case 'status': {
      return renderXMLBlock('status', { content: block.statusText, pending: block.pending });
    }

    default: {
      // TODO(burdon): Needs stable ID.
      return `<json id="${message.id}">\n${JSON.stringify(block)}\n</json>`;
    }
  }
};

/**
 * Escape text embedded in generated XML so the mixed XML parser does not treat `&`, `<`, `>` as markup.
 */
const escapeXmlTextContent = (raw: string): string =>
  raw.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const renderXMLBlock = (tag: string, opts: { content?: string; pending?: boolean; attributes?: string }) => {
  // Replace paragraph breaks so that the markdown parser does not split the content into multiple paragraphs.
  // NOTE: do not strip leading list-marker prefixes (`-`, `*`, `1. `, ...) per line — the streaming
  // tag's range is replaced atomically by the XML widget so the inner markdown is never user-visible,
  // and stripping can collapse a line to empty mid-stream (e.g. when only `1. ` has arrived), breaking
  // the prefix-extension contract that `MessageSyncer` relies on for incremental appends.
  const content = escapeXmlTextContent((opts.content ?? '').replace(/\n\n/g, ' ').trim());

  if (opts.pending) {
    return `<${tag}${opts.attributes ? ` ${opts.attributes}` : ''}>${content}`;
  } else {
    return `<${tag}${opts.attributes ? ` ${opts.attributes}` : ''}>${content}</${tag}>`;
  }
};
