# $schema:./node_modules/@dxos/functions/schema/functions.json

##
## Test:
## curl -s -X POST -H "Content-Type: application/json" http://localhost:7100/dev/hello | jq
##

functions:

  - uri: 'dxos.org/function/hello'
    route: '/hello'
    handler: 'hello'
    description: 'Hello World!'

  - uri: 'dxos.org/function/calendar'
    route: '/calendar'
    handler: 'calendar'
    description: 'Calendar Sync.'

  - uri: 'dxos.org/function/chess'
    route: '/chess'
    handler: 'chess'
    description: 'Chess.'

  - uri: 'dxos.org/function/email'
    route: '/email'
    handler: 'email'
    description: 'Email Sync.'

  - uri: 'dxos.org/function/email-extractor'
    route: '/email-extractor'
    handler: 'email-extractor'
    description: 'Email Extractor.'

  - uri: 'dxos.org/function/email-worker'
    route: '/email-worker'
    handler: 'email-worker'
    description: 'Email Sync with Cloudflare Worker.'

  - uri: 'dxos.org/function/embedding'
    route: '/embedding'
    handler: 'embedding'
    description: 'Text embedding.'

  - uri: 'dxos.org/function/gpt'
    route: '/gpt'
    handler: 'gpt'
    description: 'GPT Chat.'

  - uri: 'dxos.org/function/github'
    route: '/github'
    handler: 'github'
    description: 'Github Sync.'

triggers:

  - function: 'dxos.org/function/hello'
    meta:
      sender: 'DXOS'
    spec:
      type: 'webhook'
      method: 'GET'

  - function: 'dxos.org/function/email-worker'
    meta:
      account: 'hello@dxos.network'
    spec:
      type: 'websocket'
      url: 'https://hub.dxos.network/api/mailbox/hello@dxos.network'
      init:
        type: 'sync'

  - function: 'dxos.org/function/chess'
    meta:
      level: 2
    spec:
      type: 'subscription'
      filter:
      - type: 'dxos.org/type/Chess'

  - function: 'dxos.org/function/gpt'
    meta:
      prompt: 'faq'
    spec:
      type: 'subscription'
      filter:
      - type: 'braneframe.Message'

#  - function: 'dxos.org/function/embedding'
#    spec:
#      type: 'subscription'
#      filter:
#      - type: 'braneframe.Document'
#      - type: 'braneframe.File'
#      options:
#        deep: true
#        delay: 5

#  - function: 'dxos.org/function/calendar'
#    spec:
#      type: 'timer'
#      cron: '*/30 * * * * *'
#
#  - function: 'dxos.org/function/calendar'
#    spec:
#      type: 'subscription'
#      filter:
#      - type: 'braneframe.Calendar'
#
#  - function: 'dxos.org/function/email'
#    spec:
#      type: 'timer'
#      cron: '*/30 * * * * *'
#
#  - function: 'dxos.org/function/email-extractor'
#    spec:
#      type: 'subscription'
#      filter:
#      - type: 'braneframe.Message'
#        props:
#          type: 'email'
#      options:
#        delay: 5
#
#  - function: 'dxos.org/function/github'
#    spec:
#      type: 'subscription'
#      filter:
#      - type: 'example.com/schema/project'
