//
// Copyright 2026 DXOS.org
//

import fs from 'node:fs';
import path from 'node:path';

import { type BarrelMember, parseBarrel } from './barrel';
import {
  collectFreeIdentifiers,
  parseFile,
  rewriteRelativeSpecifiers,
  topLevelExportConsts,
  topLevelImportDeclarations,
} from './ts-util';

export type GenerateResult = {
  pluginDir: string;
  environments: string[];
  files: Array<{ path: string; included: number; stubbed: number; overridden: number }>;
};

const findFirst = (dir: string, names: string[]): string | null =>
  names.map((name) => path.join(dir, name)).find((candidate) => fs.existsSync(candidate)) ?? null;

/**
 * Generates the per-environment headless capability barrels for one plugin package:
 * `src/capabilities/gen/<env>.ts` for every environment named by an `environments` annotation in
 * the canonical barrel, plus the matching `#capabilities` condition map in package.json.
 */
export const generate = (pluginDir: string): GenerateResult => {
  const capabilitiesDir = path.join(pluginDir, 'src/capabilities');
  const indexPath = findFirst(capabilitiesDir, ['index.ts', 'index.tsx']);
  if (!indexPath) {
    throw new Error(`no capabilities barrel found at ${capabilitiesDir}/index.ts`);
  }

  const members = parseBarrel(indexPath);
  const moduleMembers = [...members.values()].filter((member) => member.kind === 'maker-call');
  const environments = [
    ...new Set(moduleMembers.flatMap((member) => member.environments ?? []).filter((env) => env !== 'browser')),
  ].sort();

  const genDir = path.join(capabilitiesDir, 'gen');
  const result: GenerateResult = { pluginDir, environments, files: [] };
  if (environments.length === 0) {
    return result;
  }
  fs.mkdirSync(genDir, { recursive: true });

  for (const env of environments) {
    const overridesPath = findFirst(capabilitiesDir, [`overrides.${env}.ts`, `overrides.${env}.tsx`]);
    const overrideNames = new Set<string>();
    if (overridesPath) {
      const overridesSource = parseFile(overridesPath);
      for (const entry of topLevelExportConsts(overridesSource!)) {
        overrideNames.add(entry.name);
      }
    }

    const included = moduleMembers.filter(
      (member) => !overrideNames.has(member.name) && (member.environments ?? []).includes(env),
    );
    const stubbed = moduleMembers.filter(
      (member) => !overrideNames.has(member.name) && !(member.environments ?? []).includes(env),
    );

    const text = renderBarrel({ env, genDir, included, stubbed, overridesPath, overrideNames });
    const outPath = path.join(genDir, `${env}.ts`);
    fs.writeFileSync(outPath, text);
    result.files.push({
      path: outPath,
      included: included.length,
      stubbed: stubbed.length,
      overridden: overrideNames.size,
    });
  }

  syncPackageImports(pluginDir, environments);
  return result;
};

type RenderOptions = {
  env: string;
  genDir: string;
  included: BarrelMember[];
  stubbed: BarrelMember[];
  overridesPath: string | null;
  overrideNames: Set<string>;
};

const renderBarrel = ({ env, genDir, included, stubbed, overridesPath, overrideNames }: RenderOptions): string => {
  // Imports selected per included statement against the file the statement was sliced from, so
  // cross-file re-exports resolve their own imports; specifiers re-based into gen/.
  const importTexts = new Set<string>();
  const importCache = new Map<string, ReturnType<typeof topLevelImportDeclarations>>();
  for (const member of included) {
    const free = collectFreeIdentifiers(member.statementText);
    if (!importCache.has(member.sourceFile)) {
      importCache.set(member.sourceFile, topLevelImportDeclarations(parseFile(member.sourceFile)!));
    }
    for (const decl of importCache.get(member.sourceFile)!) {
      if ([...decl.boundNames].some((name) => free.has(name))) {
        importTexts.add(rewriteRelativeSpecifiers(decl.text, path.dirname(member.sourceFile), genDir));
      }
    }
  }

  const lines: string[] = [
    '//',
    '// Copyright 2026 DXOS.org',
    '//',
    '',
    `// GENERATED by dx-plugin — do not edit. Sliced from ../index.ts for the '${env}'`,
    '// environment: modules flagged for it keep their exact declarations, excluded modules are',
    '// stubbed as `undefined` (skipped by `Plugin.addModule`), so the canonical plugin entry',
    '// serves every environment while this barrel keeps browser-only imports out of the static',
    '// module graph.',
    '',
  ];
  if (importTexts.size > 0) {
    lines.push(...sortImports([...importTexts]), '');
  }
  if (overridesPath) {
    const overridesSpec = `../${path.basename(overridesPath).replace(/\.tsx?$/, '')}`;
    lines.push(`export { ${[...overrideNames].sort().join(', ')} } from '${overridesSpec}';`, '');
  }
  for (const member of included) {
    lines.push(rewriteRelativeSpecifiers(member.statementText, path.dirname(member.sourceFile), genDir), '');
  }
  for (const member of [...stubbed].sort((a, b) => a.name.localeCompare(b.name))) {
    lines.push(`export const ${member.name} = undefined;`);
  }
  return (
    lines
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n'
  );
};

/** Sort import statements into the repo's groups: external, @dxos, `#` internal, relative. */
const sortImports = (imports: string[]): string[] => {
  const specifier = (text: string): string => /from\s+['"]([^'"]+)['"]/.exec(text)?.[1] ?? text;
  const group = (spec: string): number =>
    spec.startsWith('#') ? 2 : spec.startsWith('.') ? 3 : spec.startsWith('@dxos/') ? 1 : 0;
  const sorted = [...imports].sort((a, b) => {
    const specA = specifier(a);
    const specB = specifier(b);
    return group(specA) - group(specB) || specA.localeCompare(specB);
  });
  const out: string[] = [];
  let lastGroup: number | null = null;
  for (const text of sorted) {
    const currentGroup = group(specifier(text));
    if (lastGroup !== null && currentGroup !== lastGroup) {
      out.push('');
    }
    out.push(text);
    lastGroup = currentGroup;
  }
  return out;
};

/**
 * Rewrites the `#capabilities` entry of the plugin's package.json so each generated environment
 * resolves the generated barrel (source condition) and its built counterpart (dist condition).
 * Key order is load-bearing: `source` first, env conditions before `default`.
 */
const syncPackageImports = (pluginDir: string, environments: string[]): void => {
  const pkgPath = path.join(pluginDir, 'package.json');
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  const existing = pkg.imports?.['#capabilities'] ?? {};
  const existingSource = typeof existing.source === 'object' ? existing.source : {};

  // Conditions resolve in map order; workerd before node before default matches the runtimes'
  // own condition lists (wrangler never resolves `node`).
  const envOrder = ['workerd', 'node'].filter((env) => environments.includes(env));
  const source: Record<string, string> = {};
  for (const env of envOrder) {
    source[env] = `./src/capabilities/gen/${env}.ts`;
  }
  source.default =
    typeof existing.source === 'string' ? existing.source : (existingSource.default ?? './src/capabilities/index.ts');

  const entry: Record<string, unknown> = {
    source,
    types: existing.types ?? './dist/types/src/capabilities/index.d.ts',
  };
  for (const env of envOrder) {
    entry[env] = `./dist/lib/capabilities.${env}.mjs`;
  }
  entry.default = existing.default ?? './dist/lib/capabilities.mjs';

  pkg.imports = { ...pkg.imports, '#capabilities': entry };
  fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
};
