//
// Copyright 2026 DXOS.org
//

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

import { Shell } from '#shell';

/**
 * The prebaked editor, as source rather than a shipped file.
 *
 * The route's only verb is "run this script", so the editor has to arrive as a script — and a file
 * on disk cannot be located from both `src/` (dev) and `dist/lib/` (built) without guessing which
 * one loaded. A string constant is in the bundle either way, and {@link materializeScripts} writes
 * it out on mount.
 *
 * The program is deliberately dependency-free: `node` is the only thing it needs on PATH.
 */
const APPLY_EDITS_PROGRAM = `//
// Generated by @dxos/plugin-computer. Applies a batch of find/replace edits read from stdin.
//

import { chmodSync, readFileSync, realpathSync, renameSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { relative, resolve, sep } from 'node:path';

const root = process.env[${JSON.stringify(Shell.ROOT_ENV)}];

const report = (result, code) => {
  // Not process.exit: a write to a pipe is asynchronous, so exiting can truncate a large result and
  // make a batch that WAS applied read as a failure.
  process.stdout.write(JSON.stringify(result));
  process.exitCode = code;
};

const fail = (error) => report({ applied: false, files: [], error }, 1);

const contains = (dir, target) => target === dir || target.startsWith(dir + sep);

const readStdin = async () => {
  // Decoded once, after the last chunk: decoding per chunk turns a multi-byte character split across
  // a chunk boundary into replacement characters, which would then be written into the file.
  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf8');
};

const main = async () => {
  let payload;
  try {
    payload = JSON.parse(await readStdin());
  } catch (err) {
    return fail('unparseable payload: ' + err.message);
  }

  const edits = payload?.edits ?? [];
  if (!Array.isArray(edits) || edits.length === 0) {
    return fail('no edits supplied');
  }

  // Every file is read once and edited in memory, so a later failure leaves the tree untouched: a
  // half-applied batch is the one outcome a caller cannot recover from by retrying.
  const files = new Map();
  for (let index = 0; index < edits.length; ++index) {
    const { path: file, oldString, newString, replaceAll } = edits[index] ?? {};
    const label = 'edit ' + (index + 1) + ' (' + file + ')';
    if (typeof file !== 'string' || file.length === 0) {
      return fail(label + ': path must be a non-empty string');
    }
    if (typeof oldString !== 'string' || oldString.length === 0) {
      return fail(label + ': oldString must be a non-empty string');
    }
    if (typeof newString !== 'string') {
      return fail(label + ': newString must be a string');
    }

    // Checked lexically and then again after realpath: the first names an escape the caller wrote out,
    // the second catches an in-root symlink that both the read and the write would otherwise follow.
    const lexical = resolve(file);
    if (root && !contains(root, lexical)) {
      return fail(label + ': path is outside the configured root');
    }
    let absolute;
    try {
      absolute = realpathSync(lexical);
    } catch (err) {
      return fail(label + ': cannot read file: ' + err.message);
    }
    if (root && !contains(root, absolute)) {
      return fail(label + ': path is outside the configured root');
    }

    let entry = files.get(absolute);
    if (!entry) {
      try {
        entry = { path: relative(process.cwd(), absolute) || file, content: readFileSync(absolute, 'utf8'), replacements: 0 };
      } catch (err) {
        return fail(label + ': cannot read file: ' + err.message);
      }
      files.set(absolute, entry);
    }

    const matches = entry.content.split(oldString).length - 1;
    if (matches === 0) {
      return fail(label + ': oldString not found');
    }
    if (matches > 1 && !replaceAll) {
      return fail(
        label + ': oldString matched ' + matches + ' times; include more surrounding context or set replaceAll',
      );
    }

    if (replaceAll) {
      // split/join rather than String.replace: a replacement containing $&, $1 or $' would
      // otherwise be expanded as a pattern reference instead of written literally.
      entry.content = entry.content.split(oldString).join(newString);
      entry.replacements += matches;
    } else {
      const at = entry.content.indexOf(oldString);
      entry.content = entry.content.slice(0, at) + newString + entry.content.slice(at + oldString.length);
      entry.replacements += 1;
    }
  }

  for (const [absolute, entry] of files) {
    // Written beside the target and renamed over it, carrying the original's mode: a direct write
    // interrupted midway leaves a truncated file, which no retry of the batch can reconstruct.
    const temporary = absolute + '.dx-computer-tmp';
    try {
      writeFileSync(temporary, entry.content);
      chmodSync(temporary, statSync(absolute).mode & 0o777);
      renameSync(temporary, absolute);
    } catch (err) {
      try {
        unlinkSync(temporary);
      } catch {}
      return fail('cannot write ' + entry.path + ': ' + err.message);
    }
  }

  return report(
    {
      applied: true,
      files: [...files.values()].map(({ path, replacements }) => ({ path, replacements })),
    },
    0,
  );
};

await main();
`;

/**
 * Writes the prebaked scripts to a fresh private directory under the OS temp dir and returns it.
 *
 * `mkdtemp` because a predictable path under a world-writable temp dir lets another local user plant
 * the script the host then runs as the developer.
 */
export const materializeScripts = (): string => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'dx-computer-'));
  fs.writeFileSync(path.join(dir, Shell.APPLY_EDITS_SCRIPT), APPLY_EDITS_PROGRAM, { mode: 0o600 });
  return dir;
};
