#:schema node_modules/wrangler/config-schema.json
#
# Workers configuration file.
# https://developers.cloudflare.com/workers/wrangler/configuration
#

name = "cf-labs"
main = "src/worker/index.ts"
account_id = "950816f3f59b079880a1ae33fb0ec320"
compatibility_date = "2024-04-05"
compatibility_flags = [ "nodejs_compat" ]
#node_compat = true

[vars]
  WORKER_ENV = "production"

[env]
  [env.local]
    [env.local.vars]
      WORKER_ENV = "local"

# [[durable_objects.bindings]]
# name = "ROUTER"
# class_name = "RouterObject"

# [[durable_objects.bindings]]
# name = "SWARM"
# class_name = "SwarmObject"

# [[migrations]]
# tag = "v1"
# new_classes = ["RouterObject", "SwarmObject"]
