version: 1

runtime:
  client:
    storage:
      persistent: true
      dataRoot: /tmp/dx/run

  services:
    ipfs:
      server: http://dx.dev.kube.dxos.org:5001/
      gateway: http://dx.dev.kube.dxos.org:8888/ipfs
    signaling:
      - server: wss://dx.dev.kube.dxos.org/.well-known/dx/signal
      - server: wss://staging.kube.dxos.org/.well-known/dx/signal
    ice:
      - urls: stun:dx.dev.kube.dxos.org:3478
      - urls: turn:dx.dev.kube.dxos.org:3478
        username: dxos
        credential: dxos
    publisher:
      server: wss://dx.dev.kube.dxos.org/.well-known/dx/deploy
    supervisor:
      server: wss://dx.dev.kube.dxos.org/.well-known/dx/supervisor
    tunneling:
      server: wss://dx.dev.kube.dxos.org/.well-known/dx/tunnel
