version: 1

runtime:
  client:
    storage:
      persistent: true
      path: '/tmp/dx/cli'

  services:
    ipfs:
      server: "http://dx.dev.kube.dxos.org:5001/"
      gateway: "http://dx.dev.kube.dxos.org:8888/ipfs"
    signal:
      server: 'wss://dx.dev.kube.dxos.org/.well-known/dx/signal'
    ice:
      - urls: 'turn:dx.dev.kube.dxos.org:3478'
        username: 'dxos'
        credential: 'dxos'
    publisher:
      server: 'wss://dx.dev.kube.dxos.org/.well-known/dx/deploy'
