version: 1

runtime:
  client:
    storage:
      persistent: true
      path: '/tmp/dx/cli'

  services:
    ipfs:
      server: "http://staging.kube.dxos.org:5001/"
      gateway: "http://staging.kube.dxos.org:8888/ipfs"
    signal:
      server: 'wss://staging.kube.dxos.org/.well-known/dx/signal'
    ice:
      - urls: 'stun:staging.kube.dxos.org:3478'
      - urls: 'turn:staging.kube.dxos.org:3478'
        username: 'dxos'
        credential: 'dxos'
    publisher:
      server: 'wss://staging.kube.dxos.org/.well-known/dx/deploy'
    supervisor:
      server: wss://staging.kube.dxos.org/.well-known/dx/supervisor
