//
// Copyright 2026 DXOS.org
//

import { type HierarchyNode, curveBundle, cluster as d3Cluster, hierarchy, lineRadial } from 'd3';

import { type Graph } from '@dxos/graph';
import { log } from '@dxos/log';

import { type GraphLayoutEdge, type GraphLayoutNode } from '../types';
import { type GraphRadialProjectorOptions, GraphRadialProjector, updateNode } from './graph-radial-projector';

export type GraphBundleProjectorOptions = GraphRadialProjectorOptions & {
  /** Reserved space around the bundle (screen pixels). */
  margin?: number;
  /** Radius for leaf nodes. Default 4. */
  leafRadius?: number;
  /**
   * Group key for each node — synthetic intermediate nodes are created per unique key
   * to give the bundling layout a routing point (lowest common ancestor) for edges
   * between leaves in different groups. Return `undefined` to attach the node directly
   * to the root (all such leaves bundle through the root).
   */
  groupOf?: (node: GraphLayoutNode) => string | undefined;
  /** Bundling tension passed to `d3.curveBundle.beta`. 0 = straight chord, 1 = max bundled. */
  tension?: number;
};

const ROOT_ID = '__bundle_root__';
const GROUP_PREFIX = '__bundle_group__:';

/**
 * Cartesian → d3-radial polar. d3 measures angle clockwise from "up" (the -y direction).
 * Inverse of `[cos(a - π/2) * r, sin(a - π/2) * r]`.
 */
const cartesianToPolar = (x: number, y: number): { angle: number; radius: number } => ({
  angle: Math.atan2(x, -y),
  radius: Math.hypot(x, y),
});

type PolarPoint = { angle: number; radius: number };

/**
 * Hierarchical edge bundling — Holten 2006 / d3 observable notebook
 * (https://observablehq.com/@d3/hierarchical-edge-bundling).
 *
 * Synthesizes the same root → group → leaf hierarchy as `GraphClusterProjector`, runs
 * d3.cluster to give every node a polar position, but renders ONLY the leaves
 * (root + groups are routing anchors, not visible nodes). Each data edge is replaced
 * with a curve generated by `lineRadial(curveBundle.beta(tension))` over the polar
 * positions of `source.path(target)` — i.e. the chain of ancestors through the lowest
 * common ancestor.
 *
 * Per-frame `onTickFrame` refreshes the leaf endpoints (first + last point of every
 * path) from current cartesian positions so the curves stay glued to leaves during a
 * cross-variant tween (force → bundle, lattice → bundle). Internal ancestor positions
 * are fixed at d3.cluster's final polar layout, which means during the tween curves
 * route through the destination "pivot points" while the leaf endpoints catch up —
 * visually the bundle "snaps into shape" as the leaves arrive.
 */
export class GraphBundleProjector<
  NodeData = any,
  Options extends GraphBundleProjectorOptions = any,
> extends GraphRadialProjector<NodeData, Options> {
  // Per-edge polar point arrays. Points 0 and N-1 are the source / target leaves and are
  // overwritten from current cartesian on every tick; intermediate points stay fixed at
  // their cluster-layout polar coordinates.
  #edgePoints = new Map<string, PolarPoint[]>();
  #lineGen = lineRadial<PolarPoint>()
    .radius((d) => d.radius)
    .angle((d) => d.angle);

  protected override onUpdate(graph?: Graph.Any) {
    log('onUpdate', { graph: { nodes: graph?.nodes.length, edges: graph?.edges.length } });
    this.mergeData(graph);
    this.doBundleLayout();
    this.emitUpdate('topology');
    this.animate();
  }

  /**
   * Refresh leaf endpoint polar values from current cartesian so the curve tracks
   * its endpoints during the tween. Internal hierarchy positions stay constant.
   */
  protected override onTickFrame(_t: number): void {
    for (const edge of this.layout.graph.edges) {
      if (edge.type !== 'bundle') {
        continue;
      }
      const points = this.#edgePoints.get(edge.id);
      if (!points || points.length < 2) {
        continue;
      }
      const s = cartesianToPolar(edge.source.x ?? 0, edge.source.y ?? 0);
      const t = cartesianToPolar(edge.target.x ?? 0, edge.target.y ?? 0);
      points[0] = { angle: s.angle, radius: s.radius };
      points[points.length - 1] = { angle: t.angle, radius: t.radius };
      edge.path = this.#lineGen(points) ?? undefined;
    }
  }

  private doBundleLayout() {
    if (!this.context.size) {
      return;
    }
    const dataNodes = [...this.layout.graph.nodes];
    if (!dataNodes.length) {
      return;
    }

    const groupOf = this.options.groupOf;

    // Synthesize root → groups → leaves hierarchy so d3.cluster gives every node
    // (including the routing-only internal ones) a polar coordinate.
    type HierNode = { id: string; parent?: string; node?: GraphLayoutNode<NodeData> };
    const items: HierNode[] = [{ id: ROOT_ID }];
    const groupIds = new Map<string, string>();
    for (const node of dataNodes) {
      const key = groupOf?.(node);
      let parent = ROOT_ID;
      if (key !== undefined) {
        let groupId = groupIds.get(key);
        if (!groupId) {
          groupId = `${GROUP_PREFIX}${key}`;
          groupIds.set(key, groupId);
          items.push({ id: groupId, parent: ROOT_ID });
        }
        parent = groupId;
      }
      items.push({ id: node.id, parent, node });
    }

    const childrenByParent = new Map<string, HierNode[]>();
    for (const item of items) {
      if (item.parent) {
        const list = childrenByParent.get(item.parent) ?? [];
        list.push(item);
        childrenByParent.set(item.parent, list);
      }
    }

    const root = hierarchy<HierNode>({ id: ROOT_ID }, (d) => childrenByParent.get(d.id) ?? []);

    const { width, height } = this.context.size;
    const margin = this.options.margin ?? 120;
    const ringRadius = Math.max(0, Math.min(width, height) / 2 - margin);

    d3Cluster<HierNode>()
      .size([2 * Math.PI, ringRadius])
      .separation((a: any, b: any) => (a.parent === b.parent ? 1 : 2) / Math.max(1, a.depth))(root);

    const leafR = this.options.leafRadius ?? 4;

    // Re-bake the line generator with the configured tension. d3 curve factories return
    // a new curve when `.beta` is called, so this must happen whenever options change.
    const tension = this.options.tension ?? 0.85;
    this.#lineGen = lineRadial<PolarPoint>()
      .curve(curveBundle.beta(tension))
      .radius((d) => d.radius)
      .angle((d) => d.angle);

    // Index hierarchy nodes by data id for fast lookup when building edge paths.
    const hierById = new Map<string, HierarchyNode<HierNode>>();
    root.each((d) => {
      hierById.set(d.data.id, d);
    });

    // Position the leaf data nodes (cartesian); internal nodes stay layout-only.
    root.leaves().forEach((d: any) => {
      const angle = d.x;
      const radius = d.y;
      const x = Math.cos(angle - Math.PI / 2) * radius;
      const y = Math.sin(angle - Math.PI / 2) * radius;
      if (d.data.node) {
        updateNode(d.data.node, [x, y], leafR);
      }
    });
    this.layout.graph.nodes = dataNodes;

    // Build bundle edges. `mergeData` already populated `layout.graph.edges` with data
    // edges referencing the leaf GraphLayoutNodes — keep those references (so node
    // animations & hover wiring continue to work) and enhance each with a routed path
    // through the hierarchy.
    this.#edgePoints.clear();
    const incomingEdges = [...this.layout.graph.edges];
    const bundleEdges: GraphLayoutEdge<NodeData>[] = [];
    for (const edge of incomingEdges) {
      const sourceHier = hierById.get(edge.source.id);
      const targetHier = hierById.get(edge.target.id);
      if (!sourceHier || !targetHier || sourceHier === targetHier) {
        continue;
      }
      // hierarchy.path returns [source, ...up to LCA, ...down to target] (inclusive endpoints).
      const pathNodes = sourceHier.path(targetHier);
      const points: PolarPoint[] = pathNodes.map((n: any) => ({ angle: n.x, radius: n.y }));
      this.#edgePoints.set(edge.id, points);
      bundleEdges.push({
        id: edge.id,
        type: 'bundle',
        source: edge.source,
        target: edge.target,
        data: edge.data,
      });
    }
    this.layout.graph.edges = bundleEdges;

    // Seed initial paths so the topology emit has correct geometry to enter into the DOM.
    this.onTickFrame(0);
  }
}
