$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  test-browser:
    command: pnpm exec dx-killorphans vitest run --passWithNoTests --project="browser-*"
    deps:
      - esbuild-plugins:build
      - node-std:build
      - vite-plugin-icons:build
      - vite-plugin-import-source:build
      - ^:build
    inputs:
      - '@group(sources)'
      - /vitest.base.config.ts
      - /pnpm-lock.yaml # Ensure cache is invalidated when dependencies change.
      - vitest.config.ts
      - $VITEST_COVERAGE
      - $VITEST_DEBUG
      - $VITEST_ENV
      - $VITEST_XML_REPORT
    outputs:
      - /coverage/$project/browser/**
      - /test-results/$project/browser/**
    options:
      timeout: 600

inheritedBy:
  tags: ts-test-browser
