$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  build:
    command: pnpm exec tsdown
    deps:
      - dx-tsdown:compile
      - ^:build
      # Ensure ts-compile dependency packages are compiled first.
      - ^:compile
    inputs:
      - /tsconfig.base.json
      - tsconfig.json
      - tsdown.config.ts
      - '@group(sources)'
    outputs:
      - dist/lib/
      - dist/types/
    options:
      timeout: 60

inheritedBy:
  tags: ts-build
