$schema: https://moonrepo.dev/schemas/tasks.json
tasks:
  lint:
    command: pnpm exec oxlint -f unix --config .oxlintrc.json $projectSource
    inputs:
      - /.oxlintrc.json
      - /packages/common/eslint-plugin-rules/{src,dist}/**/*
      - /packages/common/eslint-plugin-rules/package.json
      - '@group(sources)'
    options:
      # ignorePatterns breaks when not run from workspace root.
      runFromWorkspaceRoot: true

inheritedBy:
  toolchains: typescript
