#!/usr/bin/env node

/* eslint-disable  import/no-extraneous-dependencies */

const { existsSync, readFileSync } = require('fs');
const { join } = require('path');
const execa = require('execa');

const MAIN_BRANCH = 'main';

(async () => {
  const { projects } = JSON.parse(readFileSync(join(__dirname, '../workspace.json'), 'utf-8'));

  const rePkg = /(packages\/([\w\-_]+))\/?/;
  const { stdout: diff } = await execa('git', ['diff', `${MAIN_BRANCH}...HEAD`, '--name-only']);
  const changedFiles = diff
    .split('\n')
    .filter((line) => rePkg.test(line) && existsSync(join(__dirname, '..', line)))
   
  const changedProjects = Object.entries(projects).filter(([name, project]) => changedFiles.some(file => file.includes(project))).map(([name, project]) => name)

  console.log(changedProjects.join(','))
})();