#!/usr/bin/env node

/* eslint-disable import/no-extraneous-dependencies */

const { existsSync } = require('fs');
const { execSync } = require('child_process');
const { join, basename, relative } = require('path');
const execa = require('execa');

const MAIN_BRANCH = 'origin/main';

(async () => {
  const projects = JSON.parse(execSync('pnpm ls -r --depth -1 --json').toString());

  const rePkg = /(packages\/([\w\-_]+))\/?/;
  const { stdout: diff } = await execa('git', ['diff', `${MAIN_BRANCH}...HEAD`, '--name-only']);
  const changedFiles = diff
  .split('\n')
  .filter((line) => rePkg.test(line) && existsSync(join(__dirname, '..', line)))

  const repoRoot = execSync('git rev-parse --show-toplevel').toString().trim();

  const changedProjects = projects.filter(({ name, path }) => changedFiles.some(file => file.includes(relative(repoRoot, path)))).map(({ path }) => basename(path))

  console.log(changedProjects.join(','))
})();
