--
-- Covering index for a bounded natural read of one feed: `WHERE spaceId = ? AND queueId = ?
-- ORDER BY objectId LIMIT ?` walks this index and stops at the limit, instead of scanning every
-- row of the feed and sorting them. `queuePosition` (0004) cannot serve it — natural order is by
-- entity id, and an unpositioned block has no position to sort on.
--
-- `spaceId` leads so the seek cannot cross spaces: a queue id is unique only within its space.
--
-- Immutable: recorded in `entity_meta_migrations` and never re-run.
--
CREATE INDEX IF NOT EXISTS idx_object_index_queueObjectId ON objectMeta(spaceId, queueId, objectId);
