//
// Copyright 2026 DXOS.org
//

// Per-channel brand artwork for the web bundle.
//
// Every non-production channel deploys as its own app on its own origin, and the desktop builds install
// side by side (see `.github/actions/cn-config`). Shared artwork makes those indistinguishable once
// they are open — the same tab favicon, the same mark on the boot screen — so each channel ships a
// recoloured mark. `pnpm icons:variants` generates them; this module decides which set a build uses.
//
// To see a channel's artwork, bundle with its environment and preview the output — `vite preview` serves
// `out/composer`:
//
//   DX_ENVIRONMENT=preview moon run composer-app:bundle && pnpm exec vite preview
//
// `moon run composer-app:serve` always shows production's, whatever `DX_ENVIRONMENT` says.

import { copyFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { type ConfigEnv, type PluginOption } from 'vite';

/** Variant directories under `assets/`, generated by `scripts/gen-icon-variants.mjs`. */
export type ChannelVariant = 'purple' | 'rust';

/**
 * Every icon the shell hands the browser — `index.html`'s `<link rel=icon>` set plus the two
 * `site.webmanifest` names. The manifest pair matters as much as the favicons: a browser picks the tab
 * and app icon from both, so leaving them blue shows the released mark next to the channel's own.
 * Replaced wholesale, so a variant set must carry all of them.
 */
const FAVICONS = [
  'favicon.svg',
  'favicon-96x96.png',
  'apple-touch-icon.png',
  'favicon.ico',
  'web-app-manifest-192x192.png',
  'web-app-manifest-512x512.png',
];

/**
 * The variant a deploy environment brands itself with, or undefined for the released app.
 * Preview is the channel people are asked to run alongside production, so it gets the mark that reads
 * least like it; the rest share one, since telling them apart from each other matters less than telling
 * any of them apart from the app holding real data.
 * Only a bundle is branded — the variant marks a deployed channel, so a dev server showing one would
 * claim this build came from somewhere it did not.
 */
export const channelVariant = (
  command: ConfigEnv['command'],
  environment = process.env.DX_ENVIRONMENT,
): ChannelVariant | undefined => {
  if (command !== 'build' || !environment || environment === 'production') {
    return undefined;
  }
  return environment === 'preview' ? 'purple' : 'rust';
};

/** Hue of the released mark's four-colour ramp (`rgb(1 122 183)` and its steps), in degrees. */
const RAMP_HUE = 200;

/**
 * Each variant as `scripts/gen-icon-variants.mjs` defines it for the raster icons: a hue that replaces
 * the ramp's, and a saturation scale. Kept in step by hand; the numbers are the channel's identity.
 */
const MARK_VARIANTS: Record<ChannelVariant, { hue: number; saturation: number }> = {
  purple: { hue: 282, saturation: 1 },
  rust: { hue: 20, saturation: 0.75 },
};

/**
 * The CSS filter that turns the released boot mark into the channel's, or undefined for the released
 * app. An SVG needs no generated copy to change colour: the loader applies this over the one mark.
 */
export const bootMarkFilter = (variant: ChannelVariant | undefined): string | undefined => {
  if (!variant) {
    return undefined;
  }
  const { hue, saturation } = MARK_VARIANTS[variant];
  const rotate = (((hue - RAMP_HUE) % 360) + 360) % 360;
  return [`hue-rotate(${rotate}deg)`, saturation !== 1 && `saturate(${saturation})`].filter(Boolean).join(' ');
};

/**
 * Overwrite the favicons already emitted into `outDir` with the channel's own. No-op without a variant,
 * which is what a production or local build gets.
 */
export const applyChannelFavicons = (appDir: string, outDir: string, variant: ChannelVariant | undefined): void => {
  if (!variant) {
    return;
  }
  const source = path.join(appDir, 'assets', `favicons-${variant}`);
  for (const favicon of FAVICONS) {
    const from = path.join(source, favicon);
    if (!existsSync(from)) {
      // A half-generated variant would ship production's mark on a prerelease, which is the exact
      // confusion this exists to prevent — fail the build instead.
      throw new Error(`channel favicon missing: ${from} (run \`pnpm icons:variants\`)`);
    }
    copyFileSync(from, path.join(outDir, favicon));
  }
};

/**
 * Applies {@link applyChannelFavicons} to the build output.
 * Runs in `closeBundle` rather than `generateBundle`, since the favicons are `publicDir` files rather
 * than rollup assets and are copied outside the bundle hooks. Deliberately without `order: 'post'`, and
 * declared ahead of `VitePWA`: Workbox hashes these files off disk to build its precache manifest, so a
 * swap after that records the released icon's revision against the channel's file and the service worker
 * then serves whichever it cached first.
 */
export const channelFaviconPlugin = (appDir: string, variant: ChannelVariant | undefined): PluginOption => {
  let outDir: string;
  return {
    name: 'dxos-channel-favicon',
    apply: 'build',
    configResolved(config) {
      outDir = path.resolve(config.root, config.build.outDir);
    },
    closeBundle() {
      applyChannelFavicons(appDir, outDir, variant);
      if (variant) {
        // eslint-disable-next-line no-console
        console.log(`dxos-channel-favicon: ${variant}`);
      }
    },
  };
};
