//
// Copyright 2026 DXOS.org
//

// GENERATED FILE — regenerate with `moon run composer-app:gen-optimize-deps`.

/**
 * Every dependency entrypoint the app reaches, pre-bundled by vite's optimizer up front.
 *
 * Vite's dependency scan is all-or-nothing — one unresolvable import anywhere in the crawl aborts
 * it and pre-bundles nothing — and it runs only when there is no valid optimizer cache, so the
 * damage outlives the start that caused it: every dep is then discovered mid-session, one
 * re-optimize and full page reload per plugin family. Listing the deps statically keeps
 * pre-bundling independent of the scan. Entries reached only through a `@dxos/*` package do not
 * resolve from the app root under pnpm, so they take vite's nested `parent > child` form.
 */
export const optimizeDepsInclude: string[] = [
  '@atlaskit/pragmatic-drag-and-drop',
  '@atlaskit/pragmatic-drag-and-drop-react-drop-indicator',
  '@atlaskit/pragmatic-drag-and-drop-react-drop-indicator/box',
  '@atlaskit/pragmatic-drag-and-drop/combine',
  '@atlaskit/pragmatic-drag-and-drop/element/adapter',
  '@atlaskit/pragmatic-drag-and-drop/element/center-under-pointer',
  '@atlaskit/pragmatic-drag-and-drop/element/disable-native-drag-preview',
  '@atlaskit/pragmatic-drag-and-drop/element/preserve-offset-on-source',
  '@atlaskit/pragmatic-drag-and-drop/element/scroll-just-enough-into-view',
  '@atlaskit/pragmatic-drag-and-drop/element/set-custom-native-drag-preview',
  '@atlaskit/pragmatic-drag-and-drop/prevent-unhandled',
  '@automerge/automerge',
  '@automerge/automerge-repo',
  '@bufbuild/protobuf',
  '@bufbuild/protobuf/codegenv2',
  '@bufbuild/protobuf/wkt',
  '@codemirror/autocomplete',
  '@codemirror/commands',
  '@codemirror/lang-javascript',
  '@codemirror/lang-json',
  '@codemirror/lang-markdown',
  '@codemirror/language',
  '@codemirror/state',
  '@codemirror/theme-one-dark',
  '@codemirror/view',
  '@dxos/app-framework > @dxos/react-hooks > alea',
  '@dxos/app-framework > @dxos/react-hooks > mini-virtual-list',
  '@dxos/app-framework > @dxos/ui-theme > tailwind-merge',
  '@dxos/app-framework > @dxos/ui-theme > tailwind-variants',
  '@dxos/app-framework > idb-keyval',
  '@dxos/app-toolkit > @dxos/client-protocol > base-x',
  '@dxos/app-toolkit > @dxos/credentials > bip39',
  '@dxos/app-toolkit > @dxos/react-focus > @zag-js/hotkeys',
  '@dxos/app-toolkit > @tauri-apps/plugin-opener',
  '@dxos/async > zen-observable',
  '@dxos/async > zen-push',
  '@dxos/client > @dxos/echo-client > eventemitter3',
  '@dxos/client > @dxos/rpc-tunnel > ua-parser-js',
  '@dxos/client > jwt-decode',
  '@dxos/client > lodash.isequalwith',
  '@dxos/client-services > @dxos/echo-host > bs58check',
  '@dxos/client-services > @dxos/echo-host > fast-deep-equal',
  '@dxos/client-services > @dxos/feed-store > race-as-promised',
  '@dxos/client-services > @dxos/feed-store > streamx',
  '@dxos/client-services > @dxos/hypercore > readable-stream',
  '@dxos/client-services > @dxos/random-access-storage > buffer-alloc',
  '@dxos/client-services > @dxos/random-access-storage > buffer-from',
  '@dxos/client-services > @dxos/random-access-storage > inherits',
  '@dxos/client-services > @dxos/random-access-storage > next-tick',
  '@dxos/client-services > @dxos/random-access-storage > once',
  '@dxos/client-services > @dxos/random-access-storage > pify',
  '@dxos/client-services > @dxos/random-access-storage > random-access-memory',
  '@dxos/client-services > @dxos/random-access-storage > random-access-storage',
  '@dxos/client-services > @obsidize/tar-browserify',
  '@dxos/client-services > cbor-x',
  '@dxos/client-services > platform',
  '@dxos/config > localforage',
  '@dxos/config > lodash.defaultsdeep',
  '@dxos/config > lodash.ismatch',
  '@dxos/devtools > @dxos/ai > diff',
  '@dxos/devtools > @dxos/ai > json-stable-stringify',
  '@dxos/devtools > @dxos/ai > parsimmon',
  '@dxos/devtools > @dxos/ai > tokenx',
  '@dxos/devtools > @dxos/react-ui-components > motion/react',
  '@dxos/devtools > @dxos/react-ui-graph > js-clipper',
  '@dxos/devtools > @dxos/react-ui-list > @ark-ui/react/accordion',
  '@dxos/devtools > @dxos/react-ui-list > @ark-ui/react/collection',
  '@dxos/devtools > @dxos/react-ui-list > @ark-ui/react/tree-view',
  '@dxos/devtools > @dxos/react-ui-list > @atlaskit/pragmatic-drag-and-drop-auto-scroll/element',
  '@dxos/devtools > @dxos/react-ui-list > @atlaskit/pragmatic-drag-and-drop-hitbox/util/get-reorder-destination-index',
  '@dxos/devtools > @dxos/react-ui-syntax-highlighter > react-syntax-highlighter/dist/esm/create-element',
  '@dxos/devtools > @dxos/react-ui-syntax-highlighter > react-syntax-highlighter/dist/esm/prism-async-light',
  '@dxos/devtools > @dxos/react-ui-syntax-highlighter > react-syntax-highlighter/dist/esm/styles/prism',
  '@dxos/devtools > @dxos/react-ui-tabs > @ark-ui/react/tabs',
  '@dxos/devtools > @robloche/chartjs-plugin-streaming',
  '@dxos/devtools > bytes',
  '@dxos/devtools > change-case',
  '@dxos/devtools > chart.js',
  '@dxos/devtools > chartjs-adapter-luxon',
  '@dxos/devtools > date-fns',
  '@dxos/devtools > date-fns/format',
  '@dxos/devtools > date-fns/formatDistance',
  '@dxos/devtools > react-drag-drop-files',
  '@dxos/devtools > react-resize-detector',
  '@dxos/devtools > react-router-dom',
  '@dxos/edge-client > isomorphic-ws',
  '@dxos/effect > @effect/opentelemetry/OtelTracer',
  '@dxos/effect > @effect/opentelemetry/Resource',
  '@dxos/effect > jsonpath-plus',
  '@dxos/keys > base32-decode',
  '@dxos/keys > base32-encode',
  '@dxos/keys > ulidx',
  '@dxos/observability > @opentelemetry/auto-instrumentations-web',
  '@dxos/observability > @opentelemetry/core',
  '@dxos/observability > @opentelemetry/exporter-trace-otlp-http',
  '@dxos/observability > @opentelemetry/instrumentation',
  '@dxos/observability > @opentelemetry/resources',
  '@dxos/observability > @opentelemetry/sdk-trace-base',
  '@dxos/observability > @opentelemetry/sdk-trace-web',
  '@dxos/observability > @opentelemetry/semantic-conventions',
  '@dxos/observability > posthog-js',
  '@dxos/plugin-assistant > @ark-ui/react/collapsible',
  '@dxos/plugin-assistant > @dxos/assistant > @dxos/mcp-client > @modelcontextprotocol/sdk/client/sse.js',
  '@dxos/plugin-assistant > @dxos/assistant > @xenova/transformers',
  '@dxos/plugin-assistant > @dxos/react-ui-search > command-score',
  '@dxos/plugin-assistant > @dxos/react-ui-transcription > date-fns/intervalToDuration',
  '@dxos/plugin-assistant > @dxos/ui-editor > @codemirror/lang-xml',
  '@dxos/plugin-assistant > @dxos/ui-editor > @codemirror/language-data',
  '@dxos/plugin-assistant > @dxos/ui-editor > @codemirror/merge',
  '@dxos/plugin-assistant > @dxos/ui-editor > @lezer/common',
  '@dxos/plugin-assistant > @dxos/ui-editor > @lezer/markdown',
  '@dxos/plugin-assistant > @dxos/ui-editor > @replit/codemirror-vim',
  '@dxos/plugin-assistant > @dxos/ui-editor > @replit/codemirror-vscode-keymap',
  '@dxos/plugin-assistant > @dxos/ui-editor > @uiw/codemirror-theme-vscode',
  '@dxos/plugin-assistant > @dxos/ui-editor > ajv',
  '@dxos/plugin-assistant > @dxos/ui-editor > codemirror-lang-mermaid',
  '@dxos/plugin-assistant > @dxos/ui-editor > lodash.sortby',
  '@dxos/plugin-atproto > @dxos/echo-panproto > @panproto/core',
  '@dxos/plugin-bookmarks > @dxos/react-ui-editor > @codemirror/search',
  '@dxos/plugin-brain > @dxos/pipeline-rdf > @comunica/query-sparql-rdfjs',
  '@dxos/plugin-brain > @dxos/pipeline-rdf > asynciterator',
  '@dxos/plugin-brain > @dxos/pipeline-rdf > n3',
  '@dxos/plugin-brain > @dxos/pipeline-rdf > sparqljs',
  '@dxos/plugin-calls > @peermetrics/webrtc-stats',
  '@dxos/plugin-calls > md5-hex',
  '@dxos/plugin-chess > chess.js',
  '@dxos/plugin-client > @dxos/cli-util > @effect/platform-bun/BunHttpServer',
  '@dxos/plugin-client > @dxos/cli-util > get-port-please',
  '@dxos/plugin-client > @dxos/react-ui-pickers > @emoji-mart/react',
  '@dxos/plugin-code > @dxos/deus > @lezer/lr',
  '@dxos/plugin-code > @typescript/vfs',
  '@dxos/plugin-code > esbuild-wasm',
  '@dxos/plugin-commerce > node-html-parser',
  '@dxos/plugin-conductor > @dxos/react-ui-canvas-compute > @dxos/react-ui-experimental > flubber',
  '@dxos/plugin-conductor > @dxos/react-ui-canvas-editor > @antv/graphlib',
  '@dxos/plugin-conductor > @dxos/react-ui-canvas-editor > @antv/layout',
  '@dxos/plugin-debug > @dxos/random > @ngneat/falso',
  '@dxos/plugin-debug > @dxos/react-ui-terminal > @xterm/addon-fit',
  '@dxos/plugin-debug > @dxos/react-ui-terminal > @xterm/xterm',
  '@dxos/plugin-deck > @ark-ui/react/factory',
  '@dxos/plugin-deck > @dxos/react-ui-mosaic > @tanstack/react-virtual',
  '@dxos/plugin-deck > @tauri-apps/plugin-deep-link',
  '@dxos/plugin-deck > immer',
  '@dxos/plugin-devtools > @dxos/react-ui-introspect > @dxos/introspect-tools > @dxos/effect-zod > zod',
  '@dxos/plugin-devtools > @dxos/react-ui-introspect > @modelcontextprotocol/sdk/client/index.js',
  '@dxos/plugin-devtools > @dxos/react-ui-introspect > @modelcontextprotocol/sdk/client/streamableHttp.js',
  '@dxos/plugin-discord > dfx',
  '@dxos/plugin-excalidraw > @excalidraw/excalidraw',
  '@dxos/plugin-explorer > @observablehq/plot',
  '@dxos/plugin-explorer > d3',
  '@dxos/plugin-explorer > force-graph',
  '@dxos/plugin-explorer > topojson-client',
  '@dxos/plugin-file > pdfjs-dist/legacy/build/pdf.mjs',
  '@dxos/plugin-file > react-dropzone',
  '@dxos/plugin-file-system > @tauri-apps/plugin-dialog',
  '@dxos/plugin-file-system > @tauri-apps/plugin-fs',
  '@dxos/plugin-google > @dxos/markdown > linkedom',
  '@dxos/plugin-google > @dxos/markdown > turndown',
  '@dxos/plugin-illustrator > @dagrejs/dagre',
  '@dxos/plugin-illustrator > elkjs/lib/elk.bundled.js',
  '@dxos/plugin-inbox > @dxos/react-ui-calendar > react-virtualized',
  '@dxos/plugin-lametric > @tauri-apps/plugin-http',
  '@dxos/plugin-library > @dxos/react-ui-markdown > remark-gfm',
  '@dxos/plugin-library > foliate-js/view.js',
  '@dxos/plugin-magazine > defuddle/full',
  '@dxos/plugin-magazine > defuddle/node',
  '@dxos/plugin-map > @dxos/react-ui-geo > leaflet',
  '@dxos/plugin-map > @dxos/react-ui-geo > react-leaflet',
  '@dxos/plugin-map > @dxos/react-ui-geo > topojson-simplify',
  '@dxos/plugin-map > @dxos/react-ui-geo > versor',
  '@dxos/plugin-map-solid > @dxos/echo-solid > @solid-primitives/utils',
  '@dxos/plugin-map-solid > @dxos/solid-ui-geo > @solid-primitives/resize-observer',
  '@dxos/plugin-map-solid > solid-element',
  '@dxos/plugin-mermaid > mermaid',
  '@dxos/plugin-native > @tauri-apps/plugin-process',
  '@dxos/plugin-native > @tauri-apps/plugin-shell',
  '@dxos/plugin-native > @tauri-apps/plugin-updater',
  '@dxos/plugin-native > date-fns/formatDistanceToNow',
  '@dxos/plugin-navtree > @atlaskit/pragmatic-drag-and-drop-hitbox/closest-edge',
  '@dxos/plugin-navtree > @atlaskit/pragmatic-drag-and-drop-hitbox/tree-item',
  '@dxos/plugin-navtree > @dxos/lit-ui > @lit/react',
  '@dxos/plugin-onboarding > @dxos/brand > @phosphor-icons/react/dist/lib/IconBase',
  '@dxos/plugin-payments > @x402/evm',
  '@dxos/plugin-payments > @x402/fetch',
  '@dxos/plugin-payments > viem',
  '@dxos/plugin-payments > viem/chains',
  '@dxos/plugin-presenter > hastscript',
  '@dxos/plugin-presenter > highlight.js',
  '@dxos/plugin-presenter > highlight.js/lib/languages/typescript',
  '@dxos/plugin-presenter > react-markdown',
  '@dxos/plugin-presenter > rehype-add-classes',
  '@dxos/plugin-presenter > rehype-highlight',
  '@dxos/plugin-presenter > remark-frontmatter',
  '@dxos/plugin-presenter > remark-parse-frontmatter',
  '@dxos/plugin-presenter > reveal.js',
  '@dxos/plugin-presenter > reveal.js/plugin/highlight/highlight',
  '@dxos/plugin-presenter > reveal.js/plugin/markdown/plugin.js',
  '@dxos/plugin-review > @dxos/react-ui-thread > date-fns/startOfDay',
  '@dxos/plugin-routine > cronstrue',
  '@dxos/plugin-script > @codemirror/lint',
  '@dxos/plugin-script > @lezer/highlight',
  '@dxos/plugin-script > @octokit/core',
  '@dxos/plugin-script > @valtown/codemirror-continue',
  '@dxos/plugin-script > @valtown/codemirror-ts',
  '@dxos/plugin-search > main-thread-scheduling',
  '@dxos/plugin-sequencer > @dxos/react-ui-canvas > bind-event-listener',
  '@dxos/plugin-sequencer > @dxos/react-ui-canvas > transformation-matrix',
  '@dxos/plugin-sequencer > tone',
  '@dxos/plugin-sheet > @dxos/lit-grid > lit',
  '@dxos/plugin-sheet > @dxos/lit-grid > lit/decorators.js',
  '@dxos/plugin-sheet > @dxos/lit-grid > lit/directives/ref.js',
  '@dxos/plugin-sheet > @dxos/lit-grid > lit/directives/style-map.js',
  '@dxos/plugin-sheet > @dxos/lit-grid > lit/static-html.js',
  '@dxos/plugin-sheet > codemirror-lang-spreadsheet',
  '@dxos/plugin-spacetime > @babylonjs/core',
  '@dxos/plugin-spacetime > @babylonjs/loaders/glTF',
  '@dxos/plugin-spacetime > manifold-3d',
  '@dxos/plugin-support > html-to-image',
  '@dxos/plugin-support > react-joyride',
  '@dxos/plugin-terra > @babylonjs/core/Cameras/arcRotateCamera',
  '@dxos/plugin-terra > @babylonjs/core/Cameras/targetCamera',
  '@dxos/plugin-terra > @babylonjs/core/Engines/constants',
  '@dxos/plugin-terra > @babylonjs/core/Engines/engine',
  '@dxos/plugin-terra > @babylonjs/core/Lights/hemisphericLight',
  '@dxos/plugin-terra > @babylonjs/core/Materials/material',
  '@dxos/plugin-terra > @babylonjs/core/Materials/standardMaterial',
  '@dxos/plugin-terra > @babylonjs/core/Maths/math',
  '@dxos/plugin-terra > @babylonjs/core/Meshes/Builders/boxBuilder',
  '@dxos/plugin-terra > @babylonjs/core/Meshes/Builders/cylinderBuilder',
  '@dxos/plugin-terra > @babylonjs/core/Meshes/Builders/polyhedronBuilder',
  '@dxos/plugin-terra > @babylonjs/core/Meshes/Builders/sphereBuilder',
  '@dxos/plugin-terra > @babylonjs/core/Meshes/mesh',
  '@dxos/plugin-terra > @babylonjs/core/Meshes/mesh.vertexData',
  '@dxos/plugin-terra > @babylonjs/core/Meshes/thinInstanceMesh',
  '@dxos/plugin-terra > @babylonjs/core/scene',
  '@dxos/plugin-terra > @babylonjs/gui/2D/advancedDynamicTexture',
  '@dxos/plugin-terra > @babylonjs/gui/2D/controls/control',
  '@dxos/plugin-terra > @babylonjs/gui/2D/controls/textBlock',
  '@dxos/plugin-terra > seedrandom',
  '@dxos/plugin-terra > simplex-noise',
  '@dxos/plugin-theme > @dxos/i18n > i18next',
  '@dxos/plugin-tldraw > @tldraw/assets/selfHosted',
  '@dxos/plugin-tldraw > @tldraw/editor',
  '@dxos/plugin-tldraw > @tldraw/state',
  '@dxos/plugin-tldraw > @tldraw/tldraw',
  '@dxos/plugin-tldraw > @tldraw/tlschema',
  '@dxos/plugin-tldraw > @tldraw/utils',
  '@dxos/plugin-transcription > @dxos/pipeline-transcription > wavefile',
  '@dxos/plugin-voxel > @react-three/drei',
  '@dxos/plugin-voxel > @react-three/fiber',
  '@dxos/plugin-voxel > three',
  '@dxos/plugin-wnfs > @ipld/car',
  '@dxos/plugin-wnfs > blockstore-core',
  '@dxos/plugin-wnfs > blockstore-idb',
  '@dxos/plugin-wnfs > debounce',
  '@dxos/plugin-wnfs > it-all',
  '@dxos/plugin-wnfs > multiformats',
  '@dxos/plugin-wnfs > multiformats/cid',
  '@dxos/plugin-wnfs > multiformats/codecs/raw',
  '@dxos/plugin-wnfs > multiformats/hashes/sha2',
  '@dxos/plugin-wnfs > uint8arrays',
  '@dxos/plugin-wnfs > wnfs/web',
  '@dxos/protocols > @dxos/codec-protobuf > compress-json',
  '@dxos/protocols > @dxos/codec-protobuf > lodash.merge',
  '@dxos/protocols > @dxos/codec-protobuf > protobufjs',
  '@dxos/react-error-boundary > react-error-boundary',
  '@dxos/react-ui > @ark-ui/react/carousel',
  '@dxos/react-ui > @ark-ui/react/checkbox',
  '@dxos/react-ui > @ark-ui/react/editable',
  '@dxos/react-ui > @ark-ui/react/slider',
  '@dxos/react-ui > @ark-ui/react/splitter',
  '@dxos/react-ui > @ark-ui/react/steps',
  '@dxos/react-ui > @ark-ui/react/toggle',
  '@dxos/react-ui > @ark-ui/react/toggle-group',
  '@dxos/react-ui > @internationalized/date',
  '@dxos/react-ui > @radix-ui/react-alert-dialog',
  '@dxos/react-ui > @radix-ui/react-context',
  '@dxos/react-ui > @radix-ui/react-dismissable-layer',
  '@dxos/react-ui > @radix-ui/react-focus-guards',
  '@dxos/react-ui > @radix-ui/react-focus-scope',
  '@dxos/react-ui > @radix-ui/react-menu',
  '@dxos/react-ui > @radix-ui/react-popper',
  '@dxos/react-ui > @radix-ui/react-portal',
  '@dxos/react-ui > @radix-ui/react-presence',
  '@dxos/react-ui > @radix-ui/react-primitive',
  '@dxos/react-ui > @radix-ui/react-select',
  '@dxos/react-ui > @radix-ui/react-slot',
  '@dxos/react-ui > @radix-ui/react-toast',
  '@dxos/react-ui > @radix-ui/react-visually-hidden',
  '@dxos/react-ui > aria-hidden',
  '@dxos/react-ui > date-fns/locale/en-US',
  '@dxos/react-ui > dompurify',
  '@dxos/react-ui > error-stack-parser',
  '@dxos/react-ui > react-aria-components',
  '@dxos/react-ui > react-i18next',
  '@dxos/react-ui > react-remove-scroll',
  '@dxos/util > @hazae41/symbol-dispose-polyfill',
  '@effect/ai-anthropic',
  '@effect/ai-anthropic/AnthropicClient',
  '@effect/ai-anthropic/AnthropicLanguageModel',
  '@effect/ai-anthropic/AnthropicTool',
  '@effect/ai-anthropic/Generated',
  '@effect/ai-openai',
  '@effect/ai-openai/OpenAiClient',
  '@effect/ai-openai/OpenAiLanguageModel',
  '@effect/atom-react',
  '@effect/atom-react/Hooks',
  '@effect/atom-react/RegistryContext',
  '@effect/platform-browser',
  '@effect/platform-browser/BrowserKeyValueStore',
  '@effect/platform-browser/BrowserWorker',
  '@effect/platform-browser/BrowserWorkerRunner',
  '@opentelemetry/api',
  '@opentelemetry/api-logs',
  '@opentelemetry/exporter-logs-otlp-http',
  '@opentelemetry/exporter-metrics-otlp-http',
  '@opentelemetry/sdk-logs',
  '@opentelemetry/sdk-metrics',
  '@radix-ui/react-context-menu',
  '@radix-ui/react-dialog',
  '@radix-ui/react-dropdown-menu',
  '@radix-ui/react-popover',
  '@radix-ui/react-scroll-area',
  '@radix-ui/react-tooltip',
  '@tauri-apps/api/core',
  '@tauri-apps/api/event',
  '@tauri-apps/api/window',
  '@tauri-apps/plugin-os',
  '@typescript/typescript6',
  '@xstate/react',
  'chalk',
  'codemirror',
  'crc-32',
  'effect',
  'effect/Array',
  'effect/Cause',
  'effect/Chunk',
  'effect/Clock',
  'effect/Config',
  'effect/Console',
  'effect/Context',
  'effect/Cron',
  'effect/Data',
  'effect/DateTime',
  'effect/Deferred',
  'effect/Duration',
  'effect/Effect',
  'effect/Effectable',
  'effect/Equal',
  'effect/Exit',
  'effect/Fiber',
  'effect/FileSystem',
  'effect/Function',
  'effect/Graph',
  'effect/Hash',
  'effect/HashSet',
  'effect/Latch',
  'effect/Layer',
  'effect/ManagedRuntime',
  'effect/Match',
  'effect/Option',
  'effect/Order',
  'effect/Path',
  'effect/Pipeable',
  'effect/Predicate',
  'effect/PubSub',
  'effect/Queue',
  'effect/Record',
  'effect/Redacted',
  'effect/Ref',
  'effect/Result',
  'effect/Runtime',
  'effect/Schedule',
  'effect/Schema',
  'effect/SchemaAST',
  'effect/SchemaIssue',
  'effect/SchemaTransformation',
  'effect/Scope',
  'effect/ScopedRef',
  'effect/Semaphore',
  'effect/Sink',
  'effect/Stdio',
  'effect/Stream',
  'effect/String',
  'effect/Struct',
  'effect/Terminal',
  'effect/Tracer',
  'effect/Tuple',
  'effect/unstable/ai/AiError',
  'effect/unstable/ai/IdGenerator',
  'effect/unstable/ai/LanguageModel',
  'effect/unstable/ai/Prompt',
  'effect/unstable/ai/Response',
  'effect/unstable/ai/Telemetry',
  'effect/unstable/ai/Tool',
  'effect/unstable/ai/Toolkit',
  'effect/unstable/cli/Argument',
  'effect/unstable/cli/CliError',
  'effect/unstable/cli/Command',
  'effect/unstable/cli/Flag',
  'effect/unstable/cli/Prompt',
  'effect/unstable/http/FetchHttpClient',
  'effect/unstable/http/Headers',
  'effect/unstable/http/HttpBody',
  'effect/unstable/http/HttpClient',
  'effect/unstable/http/HttpClientError',
  'effect/unstable/http/HttpClientRequest',
  'effect/unstable/http/HttpClientResponse',
  'effect/unstable/http/HttpRouter',
  'effect/unstable/http/HttpServerRequest',
  'effect/unstable/http/HttpServerResponse',
  'effect/unstable/persistence/KeyValueStore',
  'effect/unstable/process/ChildProcessSpawner',
  'effect/unstable/reactivity/AsyncResult',
  'effect/unstable/reactivity/Atom',
  'effect/unstable/reactivity/AtomHttpApi',
  'effect/unstable/reactivity/AtomRef',
  'effect/unstable/reactivity/AtomRegistry',
  'effect/unstable/reactivity/AtomRpc',
  'effect/unstable/reactivity/Reactivity',
  'effect/unstable/rpc/Rpc',
  'effect/unstable/rpc/RpcClient',
  'effect/unstable/rpc/RpcClientError',
  'effect/unstable/rpc/RpcGroup',
  'effect/unstable/rpc/RpcMessage',
  'effect/unstable/rpc/RpcMiddleware',
  'effect/unstable/rpc/RpcSchema',
  'effect/unstable/rpc/RpcSerialization',
  'effect/unstable/rpc/RpcServer',
  'effect/unstable/rpc/RpcTest',
  'effect/unstable/sql/Migrator',
  'effect/unstable/sql/SqlClient',
  'effect/unstable/sql/SqlError',
  'effect/unstable/sql/Statement',
  'fast-xml-parser',
  'json5',
  'prettier',
  'prettier/plugins/estree',
  'prettier/plugins/typescript',
  'react',
  'react-dom',
  'react-dom/client',
  'react-qr-rounded',
  'react/jsx-dev-runtime',
  'react/jsx-runtime',
  'semver',
  'solid-js',
  'solid-js/h',
  'solid-js/html',
  'solid-js/jsx-dev-runtime',
  'solid-js/store',
  'solid-js/web',
  'typescript',
  'xstate',
  'yaml',
];
