//
// Copyright 2024 DXOS.org
//

export const data = {
  v1: {
    'document:document': { gridSize: 10, name: '', meta: {}, id: 'document:document', typeName: 'document' },
    'page:4erp5FF7mts21Njur5UKw': {
      meta: {},
      id: 'page:4erp5FF7mts21Njur5UKw',
      name: 'Page 1',
      index: 'a1',
      typeName: 'page',
    },
    'shape:_-1kyVBGSUAeNrcxiGAbw': {
      x: 0,
      y: 0,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: 'shape:_-1kyVBGSUAeNrcxiGAbw',
      type: 'geo',
      props: {
        w: 160,
        h: 160,
        geo: 'rectangle',
        color: 'black',
        labelColor: 'black',
        fill: 'none',
        dash: 'dotted',
        size: 'l',
        font: 'draw',
        text: 'ECHO',
        align: 'middle',
        verticalAlign: 'middle',
        growY: 0,
        url: '',
      },
      parentId: 'page:4erp5FF7mts21Njur5UKw',
      index: 'a1',
      typeName: 'shape',
    },
    'shape:kXmGpjXqyzlg1savamgn8': {
      x: 320,
      y: 0,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: 'shape:kXmGpjXqyzlg1savamgn8',
      type: 'geo',
      props: {
        w: 160,
        h: 160,
        geo: 'star',
        color: 'yellow',
        labelColor: 'black',
        fill: 'none',
        dash: 'draw',
        size: 'm',
        font: 'draw',
        text: 'DXOS',
        align: 'middle',
        verticalAlign: 'middle',
        growY: 0,
        url: '',
      },
      parentId: 'page:4erp5FF7mts21Njur5UKw',
      index: 'a2',
      typeName: 'shape',
    },
    'shape:eYiyZDA7Iwoi16QjTkJUE': {
      x: 0,
      y: 240,
      rotation: -15 * (Math.PI / 180),
      isLocked: false,
      opacity: 1,
      meta: {},
      id: 'shape:eYiyZDA7Iwoi16QjTkJUE',
      type: 'text',
      props: {
        color: 'light-green',
        size: 'xl',
        w: 320,
        text: 'DXOS!',
        font: 'mono',
        align: 'middle',
        autoSize: true,
        scale: 1,
      },
      parentId: 'page:4erp5FF7mts21Njur5UKw',
      index: 'a4',
      typeName: 'shape',
    },

    // NOTE: This record will fail to be migrated.
    'shape:F_o1eH6pS_ABcU3-JPadv': {
      x: 0,
      y: 240,
      rotation: -15 * (Math.PI / 180),
      isLocked: false,
      opacity: 1,
      meta: {},
      id: 'shape:F_o1eH6pS_ABcU3-JPadv',
      type: 'arrow',
      parentId: 'page:4erp5FF7mts21Njur5UKw',
      index: 'a3',
      props: {
        dash: 'draw',
        size: 's',
        fill: 'none',
        color: 'blue',
        labelColor: 'black',
        bend: 0,
        start: {
          // Incompatible with v2 migration.
          type: 'binding',
          boundShapeId: 'shape:_-1kyVBGSUAeNrcxiGAbw',
          normalizedAnchor: { x: 0.5, y: 0.5 },
          isExact: false,
        },
        end: {
          // Incompatible with v2 migration.
          type: 'binding',
          boundShapeId: 'shape:kXmGpjXqyzlg1savamgn8',
          normalizedAnchor: { x: 0.5, y: 0.5 },
          isExact: false,
        },
        arrowheadStart: 'none',
        arrowheadEnd: 'arrow',
        text: '',
        font: 'draw',
      },
      typeName: 'shape',
    },
  },

  v2: {
    'document:document': {
      gridSize: 10,
      name: '',
      meta: {},
      id: 'document:document',
      typeName: 'document',
    },
    'page:1': {
      meta: {},
      id: 'page:4erp5FF7mts21Njur5UKw',
      name: 'Page 1',
      index: 'a1',
      typeName: 'page',
    },
    'shape:_-1kyVBGSUAeNrcxiGAbw': {
      x: 0,
      y: 0,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: 'shape:_-1kyVBGSUAeNrcxiGAbw',
      type: 'geo',
      props: {
        w: 160,
        h: 160,
        geo: 'rectangle',
        color: 'black',
        labelColor: 'black',
        fill: 'none',
        dash: 'dotted',
        size: 'l',
        font: 'draw',
        text: 'ECHO',
        align: 'middle',
        verticalAlign: 'middle',
        growY: 0,
        url: '',
        scale: 1,
      },
      parentId: 'page:4erp5FF7mts21Njur5UKw',
      index: 'a1',
      typeName: 'shape',
    },
    'shape:kXmGpjXqyzlg1savamgn8': {
      x: 320,
      y: 0,
      rotation: 0,
      isLocked: false,
      opacity: 1,
      meta: {},
      id: 'shape:kXmGpjXqyzlg1savamgn8',
      type: 'geo',
      props: {
        w: 160,
        h: 160,
        geo: 'star',
        color: 'yellow',
        labelColor: 'black',
        fill: 'none',
        dash: 'draw',
        size: 'm',
        font: 'draw',
        text: 'DXOS',
        align: 'middle',
        verticalAlign: 'middle',
        growY: 0,
        url: '',
        scale: 1,
      },
      parentId: 'page:4erp5FF7mts21Njur5UKw',
      index: 'a2',
      typeName: 'shape',
    },
    'shape:eYiyZDA7Iwoi16QjTkJUE': {
      x: 0,
      y: 240,
      rotation: -15 * (Math.PI / 180),
      isLocked: false,
      opacity: 1,
      meta: {},
      id: 'shape:eYiyZDA7Iwoi16QjTkJUE',
      type: 'text',
      props: {
        color: 'light-green',
        size: 'xl',
        w: 320,
        text: 'DXOS!',
        font: 'mono',
        autoSize: true,
        scale: 1,
        textAlign: 'middle',
      },
      parentId: 'page:4erp5FF7mts21Njur5UKw',
      index: 'a4',
      typeName: 'shape',
    },
  },
};
