//
// Copyright 2026 DXOS.org
//

import { defineConfig } from '../../../vite.base.config.ts';

export default defineConfig({
  entry: {
    Accordion: 'src/next/components/Accordion/Accordion.tsx',
    AlertDialog: 'src/next/components/AlertDialog/AlertDialog.tsx',
    Avatar: 'src/next/components/Avatar/Avatar.tsx',
    Banner: 'src/next/components/Banner/Banner.tsx',
    Breadcrumb: 'src/next/components/Breadcrumb/Breadcrumb.tsx',
    Button: 'src/next/namespaces/Button.ts',
    Card: 'src/next/components/Card/Card.tsx',
    Carousel: 'src/next/components/Carousel/Carousel.tsx',
    Collapsible: 'src/next/components/Collapsible/Collapsible.tsx',
    Combobox: 'src/next/components/Combobox/Combobox.tsx',
    Dialog: 'src/next/components/Dialog/Dialog.tsx',
    DragHandle: 'src/next/components/DragHandle/DragHandle.tsx',
    Editable: 'src/next/components/Editable/Editable.tsx',
    Field: 'src/next/components/Field/Field.tsx',
    Fieldset: 'src/next/components/Fieldset/Fieldset.tsx',
    FloatingPanel: 'src/next/components/FloatingPanel/FloatingPanel.tsx',
    Focus: 'src/next/components/Focus/Focus.tsx',
    Hooks: 'src/hooks/Hooks.ts',
    HoverCard: 'src/next/components/HoverCard/HoverCard.tsx',
    Icon: 'src/next/components/Icon/Icon.tsx',
    Input: 'src/next/namespaces/Input.ts',
    Layout: 'src/next/namespaces/Layout.ts',
    Listbox: 'src/next/components/Listbox/Listbox.tsx',
    Main: 'src/next/components/Main/Main.tsx',
    Match: 'src/flow/Match.tsx',
    Media: 'src/next/components/Media/Media.ts',
    Menu: 'src/next/components/Menu/Menu.tsx',
    Panel: 'src/next/components/Panel/Panel.tsx',
    Popover: 'src/next/components/Popover/Popover.tsx',
    QrCode: 'src/next/components/QrCode/QrCode.tsx',
    ScrollArea: 'src/next/components/ScrollArea/ScrollArea.tsx',
    ScrollContainer: 'src/next/components/ScrollContainer/ScrollContainer.tsx',
    Select: 'src/next/components/Select/Select.tsx',
    Show: 'src/flow/Show.tsx',
    Splitter: 'src/next/components/Splitter/Splitter.tsx',
    Status: 'src/next/namespaces/Status.ts',
    SystemButton: 'src/next/components/SystemButton/SystemButton.tsx',
    Tabs: 'src/next/components/Tabs/Tabs.tsx',
    Tag: 'src/next/components/Tag/Tag.tsx',
    Theme: 'src/providers/ThemeProvider/Theme.tsx',
    Toast: 'src/next/components/Toast/Toast.tsx',
    ToggleGroup: 'src/next/components/ToggleGroup/ToggleGroup.tsx',
    Toolbar: 'src/next/components/Toolbar/Toolbar.tsx',
    Tooltip: 'src/next/components/Tooltip/Tooltip.tsx',
    Tour: 'src/next/components/Tour/Tour.tsx',
    Typography: 'src/next/components/Typography/Typography.tsx',
    Util: 'src/util/Util.ts',
    VirtualAnchor: 'src/next/components/VirtualAnchor/VirtualAnchor.ts',
    index: 'src/index.ts',
    testing: 'src/testing/index.ts',
    translations: 'src/translations.ts',
  },
  jsx: 'react',
  test: { node: { environment: 'happy-dom' }, storybook: true },
});
