//
// Copyright 2026 DXOS.org
//

import { defineConfig } from '../../../vite.base.config.ts';

export default defineConfig({
  entry: {
    Accordion: 'src/next/components/Accordion/Accordion.tsx',
    AlertDialog: 'src/next/components/AlertDialog/AlertDialog.tsx',
    AttentionGlyph: 'src/next/components/AttentionGlyph/AttentionGlyph.tsx',
    Avatar: 'src/next/components/Avatar/Avatar.tsx',
    Banner: 'src/next/components/Banner/Banner.tsx',
    Block: 'src/next/components/Block/Block.tsx',
    Breadcrumb: 'src/next/components/Breadcrumb/Breadcrumb.tsx',
    Button: 'src/next/components/Button/Button.tsx',
    Card: 'src/next/components/Card/Card.tsx',
    Carousel: 'src/next/components/Carousel/Carousel.tsx',
    Checkbox: 'src/next/components/Checkbox/Checkbox.tsx',
    Collapsible: 'src/next/components/Collapsible/Collapsible.tsx',
    Combobox: 'src/next/components/Combobox/Combobox.tsx',
    Container: 'src/next/components/Container/Container.tsx',
    ControlFrame: 'src/next/components/ControlFrame/ControlFrame.tsx',
    DateInput: 'src/next/components/DateInput/DateInput.tsx',
    Deferred: 'src/next/components/Deferred/Deferred.tsx',
    Dialog: 'src/next/components/Dialog/Dialog.tsx',
    DragHandle: 'src/next/components/DragHandle/DragHandle.tsx',
    Editable: 'src/next/components/Editable/Editable.tsx',
    Empty: 'src/next/components/Empty/Empty.tsx',
    ErrorFallback: 'src/next/components/ErrorFallback/ErrorFallback.tsx',
    Field: 'src/next/components/Field/Field.tsx',
    Fieldset: 'src/next/components/Fieldset/Fieldset.tsx',
    Flex: 'src/layout/Flex/Flex.tsx',
    FloatingPanel: 'src/next/components/FloatingPanel/FloatingPanel.tsx',
    Focus: 'src/next/components/Focus/Focus.tsx',
    Grid: 'src/layout/Grid/Grid.tsx',
    Group: 'src/next/components/Group/Group.tsx',
    Hooks: 'src/hooks/Hooks.ts',
    HoverCard: 'src/next/components/HoverCard/HoverCard.tsx',
    Icon: 'src/next/components/Icon/Icon.tsx',
    Image: 'src/next/components/Image/Image.tsx',
    Input: 'src/next/components/Input/Input.tsx',
    Link: 'src/next/components/Link/Link.tsx',
    Listbox: 'src/next/components/Listbox/Listbox.tsx',
    Main: 'src/next/components/Main/Main.tsx',
    Match: 'src/flow/Match.tsx',
    MediaPlayer: 'src/next/components/MediaPlayer/MediaPlayer.tsx',
    Menu: 'src/next/components/Menu/Menu.tsx',
    MenuButton: 'src/next/components/MenuButton/MenuButton.tsx',
    NumberInput: 'src/next/components/NumberInput/NumberInput.tsx',
    Panel: 'src/next/components/Panel/Panel.tsx',
    PasswordInput: 'src/next/components/PasswordInput/PasswordInput.tsx',
    PinInput: 'src/next/components/PinInput/PinInput.tsx',
    Popover: 'src/next/components/Popover/Popover.tsx',
    Progress: 'src/next/components/Progress/Progress.tsx',
    QrCode: 'src/next/components/QrCode/QrCode.tsx',
    ScrollArea: 'src/next/components/ScrollArea/ScrollArea.tsx',
    ScrollContainer: 'src/next/components/ScrollContainer/ScrollContainer.tsx',
    Select: 'src/next/components/Select/Select.tsx',
    Separator: 'src/next/components/Separator/Separator.tsx',
    Show: 'src/flow/Show.tsx',
    Skeleton: 'src/next/components/Skeleton/Skeleton.tsx',
    Slider: 'src/next/components/Slider/Slider.tsx',
    Splitter: 'src/next/components/Splitter/Splitter.tsx',
    Steps: 'src/next/components/Steps/Steps.tsx',
    Switch: 'src/next/components/Switch/Switch.tsx',
    SystemButton: 'src/next/components/SystemButton/SystemButton.tsx',
    Tabs: 'src/next/components/Tabs/Tabs.tsx',
    Tag: 'src/next/components/Tag/Tag.tsx',
    Textarea: 'src/next/components/Textarea/Textarea.tsx',
    TextCrawl: 'src/next/components/TextCrawl/TextCrawl.tsx',
    ThemeProvider: 'src/providers/ThemeProvider/ThemeProvider.tsx',
    Timestamp: 'src/next/components/Timestamp/Timestamp.tsx',
    Toast: 'src/next/components/Toast/Toast.tsx',
    Toggle: 'src/next/components/Toggle/Toggle.tsx',
    ToggleGroup: 'src/next/components/ToggleGroup/ToggleGroup.tsx',
    Toolbar: 'src/next/components/Toolbar/Toolbar.tsx',
    Tooltip: 'src/next/components/Tooltip/Tooltip.tsx',
    Tour: 'src/next/components/Tour/Tour.tsx',
    Typography: 'src/next/components/Typography/Typography.tsx',
    Util: 'src/util/Util.ts',
    VirtualAnchor: 'src/next/components/VirtualAnchor/VirtualAnchor.ts',
    index: 'src/index.ts',
    testing: 'src/testing/index.ts',
    translations: 'src/translations.ts',
  },
  jsx: 'react',
  test: { node: { environment: 'happy-dom' }, storybook: true },
});
