//
// Copyright 2026 DXOS.org
//

import { defineConfig } from '../../../vite.base.config.ts';

export default defineConfig({
  entry: {
    'Accordion': 'src/components/Accordion/Accordion.tsx',
    'AlertDialog': 'src/components/Dialog/AlertDialog.tsx',
    'AttentionGlyph': 'src/components/AttentionGlyph/AttentionGlyph.tsx',
    'Avatar': 'src/components/Avatars/Avatar.tsx',
    'Banner': 'src/components/Banner/Banner.tsx',
    'Breadcrumb': 'src/components/Breadcrumb/Breadcrumb.tsx',
    'Button': 'src/components/Button/Button.tsx',
    'Calendar': 'src/components/Calendar/Calendar.tsx',
    'Card': 'src/components/Card/Card.tsx',
    'Carousel': 'src/components/Carousel/Carousel.tsx',
    'Collapsible': 'src/components/Collapsible/Collapsible.tsx',
    'Column': 'src/components/Column/Column.tsx',
    'Container': 'src/layout/Container/Container.tsx',
    'DatePicker': 'src/components/DatePicker/DatePicker.tsx',
    'Deferred': 'src/components/Deferred/Deferred.tsx',
    'DensityProvider': 'src/providers/DensityProvider/DensityProvider.tsx',
    'Dialog': 'src/components/Dialog/Dialog.tsx',
    'Drawer': 'src/components/Drawer/Drawer.tsx',
    'Editable': 'src/components/Editable/Editable.tsx',
    'ElevationProvider': 'src/providers/ElevationProvider/ElevationProvider.tsx',
    'ErrorFallback': 'src/components/ErrorFallback/ErrorFallback.tsx',
    'ErrorStack': 'src/components/ErrorFallback/ErrorStack.tsx',
    'Field': 'src/components/Field/Field.tsx',
    'Fieldset': 'src/components/Fieldset/Fieldset.tsx',
    'Flex': 'src/layout/Flex/Flex.tsx',
    'FloatingPanel': 'src/components/FloatingPanel/FloatingPanel.tsx',
    'Focus': 'src/components/Focus/Focus.tsx',
    'Grid': 'src/layout/Grid/Grid.tsx',
    'Hooks': 'src/hooks/Hooks.ts',
    'HoverCard': 'src/components/HoverCard/HoverCard.tsx',
    'Icon': 'src/components/Icon/Icon.tsx',
    'IconBlock': 'src/components/Icon/IconBlock.tsx',
    'IconButton': 'src/components/Button/IconButton.tsx',
    'Image': 'src/components/Image/Image.tsx',
    'Link': 'src/components/Link/Link.tsx',
    'Main': 'src/components/Main/Main.tsx',
    'MediaPlayer': 'src/components/MediaPlayer/MediaPlayer.tsx',
    'Menu': 'src/components/Menu/Menu.tsx',
    'MenuButton': 'src/components/MenuButton/MenuButton.tsx',
    'Panel': 'src/components/Panel/Panel.tsx',
    'PinInput': 'src/components/Field/PinInput.tsx',
    'Popover': 'src/components/Popover/Popover.tsx',
    'Progress': 'src/components/Progress/Progress.tsx',
    'QrCode': 'src/components/QrCode/QrCode.tsx',
    'ScrollArea': 'src/components/ScrollArea/ScrollArea.tsx',
    'ScrollAreaThumbs': 'src/components/ScrollArea/ScrollAreaThumbs.tsx',
    'ScrollContainer': 'src/components/ScrollContainer/ScrollContainer.tsx',
    'Select': 'src/components/Select/Select.tsx',
    'Separator': 'src/components/Separator/Separator.tsx',
    'Show': 'src/flow/Show.tsx',
    'Skeleton': 'src/components/Skeleton/Skeleton.tsx',
    'Slider': 'src/components/Slider/Slider.tsx',
    'Splitter': 'src/components/Splitter/Splitter.tsx',
    'Steps': 'src/components/Steps/Steps.tsx',
    'Switch': 'src/flow/Switch.tsx',
    'SystemIconButton': 'src/components/Button/SystemIconButton.tsx',
    'Tabs': 'src/components/Tabs/Tabs.tsx',
    'Tag': 'src/components/Tag/Tag.tsx',
    'TextCrawl': 'src/components/TextCrawl/TextCrawl.tsx',
    'TextTooltip': 'src/components/Tooltip/TextTooltip.tsx',
    'ThemeProvider': 'src/providers/ThemeProvider/ThemeProvider.tsx',
    'ThrowError': 'src/components/ErrorFallback/ThrowError.tsx',
    'Timestamp': 'src/components/Timestamp/Timestamp.tsx',
    'Toast': 'src/components/Toast/Toast.tsx',
    'Toc': 'src/components/Toc/Toc.tsx',
    'Toggle': 'src/components/Button/Toggle.tsx',
    'ToggleGroup': 'src/components/Button/ToggleGroup.tsx',
    'ToggleIconButton': 'src/components/Button/ToggleIconButton.tsx',
    'Toolbar': 'src/components/Toolbar/Toolbar.tsx',
    'Tooltip': 'src/components/Tooltip/Tooltip.tsx',
    'Tour': 'src/components/Tour/Tour.tsx',
    'TranslationsProvider': 'src/providers/ThemeProvider/TranslationsProvider.tsx',
    'Util': 'src/util/Util.ts',
    'index': 'src/index.ts',
    'next': 'src/next/index.ts',
    'next-testing': 'src/next/testing/stories.tsx',
    'testing': 'src/testing/index.ts',
    'translations': 'src/translations.ts',
  },
  jsx: 'react',
  test: { node: { environment: 'happy-dom' }, storybook: true },
});
