//
// Copyright 2026 DXOS.org
//

// Scores a `vitest bench --outputJson` run against the committed budgets, or proposes budgets from one.
//
//   node src/bench-score/cli.ts score --results <json> [--publish] [--summary <file>]
//   node src/bench-score/cli.ts calibrate --results <json> [--headroom 1.1] [--band 1.5] [--write]
//   node src/bench-score/cli.ts docs [--write]
//
// `score` never fails on a low score: a measurement is not a pass/fail, and a shared runner's variance
// would make it a coin toss. It exits non-zero only when the inputs are broken.

import * as Schema from 'effect/Schema';
import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';

import {
  type Budget,
  parseBudgets,
  publishPosthogBatch,
  renderBudgetTables,
  renderReport,
  scoreMeasurements,
  toScoreEvents,
  validateBudget,
} from '@dxos/perf-harness/score';

import { BenchJsonReport, proposeBudgets, toMeasurements } from './results.ts';

const PACKAGE_ROOT = path.resolve(import.meta.dirname, '../..');
const WORKSPACE_ROOT = path.resolve(PACKAGE_ROOT, '../../../..');
const BUDGETS_FILE = path.join(import.meta.dirname, 'budgets.json');
const DOCS_FILE = path.join(PACKAGE_ROOT, 'BUDGETS.md');
const OUT_DIR = path.join(WORKSPACE_ROOT, 'test-results', 'echo-bench');

const readJson = <A, I>(schema: Schema.Codec<A, I>, file: string): A =>
  Schema.decodeUnknownSync(schema)(JSON.parse(readFileSync(file, 'utf8')));

const readBudgets = (): Record<string, Budget> => parseBudgets(JSON.parse(readFileSync(BUDGETS_FILE, 'utf8')));

const writeBudgets = (budgets: Record<string, Budget>) =>
  writeFileSync(BUDGETS_FILE, JSON.stringify(budgets, null, 2) + '\n');

const renderDocs = (budgets: Record<string, Budget>): string =>
  [
    '# echo-client-e2e — benchmark budgets',
    '',
    '<!-- Generated by `node src/bench-score/cli.ts docs --write` from `src/bench-score/budgets.json`; do not edit. -->',
    '',
    'Every benchmark is scored nightly against the range below; `packages/e2e/perf-harness/src/score/score.ts`',
    'documents the curve. Scores run 0–1: at or under the target scores 1 and the limit scores 0.5; past',
    'the limit the score keeps falling, to 0.2 one budget band further (in log space) and 0.1 two bands',
    'further, floored at 0.01. Values are the median time per bench call.',
    '',
    renderBudgetTables(
      Object.entries(budgets).map(([id, budget]) => {
        const [group, ...rest] = id.split(' > ');
        return { id, group, label: rest.join(' > '), budget };
      }),
    ),
    '',
  ].join('\n');

const { positionals, values } = parseArgs({
  allowPositionals: true,
  options: {
    results: { type: 'string' },
    publish: { type: 'boolean', default: false },
    summary: { type: 'string' },
    headroom: { type: 'string', default: '1.1' },
    band: { type: 'string', default: '1.5' },
    write: { type: 'boolean', default: false },
  },
});

const [command] = positionals;

if (command === 'score') {
  if (!values.results) {
    throw new Error('--results is required');
  }
  const budgets = readBudgets();
  const measurements = toMeasurements(readJson(BenchJsonReport, values.results));
  if (measurements.length === 0) {
    throw new Error(`no benchmarks in ${values.results}; did the bench run fail?`);
  }
  const report = scoreMeasurements(measurements, budgets);
  const markdown = renderReport('ECHO benchmarks', report);
  console.log(markdown);
  if (values.summary) {
    appendFileSync(values.summary, markdown + '\n');
  }

  const stale = Object.keys(budgets).filter((id) => !measurements.some((measurement) => measurement.id === id));
  for (const id of stale) {
    console.log(`::warning::budget for "${id}" matched no benchmark; rename or remove it`);
  }
  for (const { id } of report.unbudgeted) {
    console.log(`::warning::benchmark "${id}" has no budget; run \`calibrate\` and review the proposal`);
  }

  mkdirSync(OUT_DIR, { recursive: true });
  const eventsFile = path.join(OUT_DIR, 'score.events.ndjson');
  const events = toScoreEvents(report, { suite: 'echo' });
  writeFileSync(eventsFile, events.map((event) => JSON.stringify(event)).join('\n') + '\n');
  if (values.publish) {
    const published = publishPosthogBatch(WORKSPACE_ROOT, eventsFile);
    console.log(published ? `published ${events.length} score events` : '::warning::score events NOT published');
  }
} else if (command === 'calibrate') {
  if (!values.results) {
    throw new Error('--results is required');
  }
  const headroom = Number(values.headroom);
  const band = Number(values.band);
  if (!(headroom > 0 && Number.isFinite(headroom)) || !(band > 1 && Number.isFinite(band))) {
    throw new Error(`--headroom must be positive and --band greater than 1; got ${values.headroom}, ${values.band}`);
  }
  // A weight is a judgement about a row (e.g. a plain-object reference), not a measurement, so it survives recalibration.
  const current = readBudgets();
  const proposed = Object.fromEntries(
    Object.entries(proposeBudgets(readJson(BenchJsonReport, values.results), { headroom, band })).map(
      ([id, budget]) => {
        const weight = current[id]?.weight;
        return [id, weight === undefined ? budget : { ...budget, weight }];
      },
    ),
  );
  // The scorer rejects an invalid budget, so a proposal it would reject must never reach budgets.json.
  for (const [id, budget] of Object.entries(proposed)) {
    validateBudget(id, budget);
  }
  if (values.write) {
    writeBudgets(proposed);
    writeFileSync(DOCS_FILE, renderDocs(proposed));
    console.log(`wrote ${Object.keys(proposed).length} budgets and ${path.relative(PACKAGE_ROOT, DOCS_FILE)}`);
  } else {
    console.log(JSON.stringify(proposed, null, 2));
  }
} else if (command === 'docs') {
  const markdown = renderDocs(readBudgets());
  if (values.write) {
    writeFileSync(DOCS_FILE, markdown);
  } else {
    console.log(markdown);
  }
} else {
  throw new Error(`unknown command "${command ?? ''}"; expected score, calibrate or docs`);
}
