#
# Pages Functions configuration.
# https://developers.cloudflare.com/pages/functions/wrangler-configuration
#

name = "dxos-storybook"
compatibility_date = "2024-04-05"
pages_build_output_dir = "./out/all"

#
# Dev
# http://localhost:8788
# pnpm -w nx storybook-build stories
# wrangler pages dev
#
