#
# https://docs.netlify.com/configure-builds/file-based-configuration
#

# TODO(burdon): Is this used or configured via the Netlify dashboard?
# Both. This file overrides configuration in the dashboard.

[build]
  base = "docs/"
  publish = "public/"
  command = "yarn build"
  ignore = "bash ./netlify-ignore.sh"
