#
# https://docs.netlify.com/configure-builds/file-based-configuration
#

# TODO(burdon): Is this used or configured via the Netlify dashboard?

[build]
  base = "docs/"
  publish = "public/"
  command = "yarn build"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF . ../packages/"
