//
// Copyright 2023 DXOS.org
//

import { type Preview } from '@storybook/react';

import { preview } from '../../.storybook/preview';

export * from '../../.storybook/preview';

// IMPORTANT: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#v7-style-story-sort
// The preview.js export should not be generated by a function.

// ERROR: CSF Parsing error: Expected 'ObjectExpression' but found 'undefined' instead in 'Identifier'.
//   If just try to export `preview`
// ERROR: SyntaxError: Unexpected token ':'
//   If try to use TS type defs in story fn.
// ERROR: Error: Unexpected 'storySort'. Parameter 'options.storySort' should be defined inline e.g.:
//   If try to assign storySort from import.

// https://storybook.js.org/docs/api/parameters#optionsstorysort
// https://storybook.js.org/docs/writing-stories/naming-components-and-hierarchy#sorting-stories

export default {
  ...preview,
  parameters: {
    ...preview.parameters,
    options: {
      // This must be defined inline and may not include TS type defs.
      storySort: (a, b) => a.title === b.title ? 0 : a.id.localeCompare(b.id, undefined, { numeric: true })
    }
  }
} as Preview;
