version: 1
package:
  modules:
    - name: tasks
      type: dxos:type/app
      build:
        command: npm run build
        outdir: out/tasks
runtime:
  client:
    storage:
      persistent: true
  services:
    signaling:
      - server: wss://kube.dxos.org/.well-known/dx/signal
    ice:
      - urls: turn:kube.dxos.org:3478
        username: dxos
        credential: dxos
