version: 1
package:
  modules:
    - name: tasks
      type: dxos:type/app
      build:
        command: moon run tasks:bundle
        outdir: out/tasks

runtime:
  client:
    storage:
      persistent: true
    edgeFeatures:
      signaling: true

  services:
    edge:
      url: wss://edge-production.dxos.workers.dev/
    iceProviders:
      - urls: https://edge-production.dxos.workers.dev/ice
