//
// Copyright 2026 DXOS.org
//

// Scores a perf nightly's `measure` rows against `src/playwright/perf/budgets.json`, or renders the
// budgets as `spec/PERF-BUDGETS.md`.
//
//   node scripts/score-perf.ts score [--dir test-results/perf] [--publish] [--summary <file>]
//   node scripts/score-perf.ts docs [--write]
//
// Run once after every iteration has written its batch: a night's score is the median across them.
// A low score never fails the job; only broken inputs do.

import * as Schema from 'effect/Schema';
import { appendFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';

import {
  type Budget,
  parseBudgets,
  publishPosthogBatch,
  renderBudgetTables,
  renderReport,
  scoreMeasurements,
  toScoreEvents,
} from '@dxos/perf-harness/score';

import { StageEvent, groupOfId, toMeasurements } from '../src/playwright/perf/score.ts';

const APP_ROOT = path.resolve(import.meta.dirname, '..');
const WORKSPACE_ROOT = path.resolve(APP_ROOT, '../../..');
const BUDGETS_FILE = path.join(APP_ROOT, 'src/playwright/perf/budgets.json');
const DOCS_FILE = path.join(APP_ROOT, 'spec/PERF-BUDGETS.md');

/** The flow and scale the budgets were calibrated on; another flow's rows are not scored. */
const FLOW = 'projects-tasks';

const readBudgets = (): Record<string, Budget> => parseBudgets(JSON.parse(readFileSync(BUDGETS_FILE, 'utf8')));

const renderDocs = (budgets: Record<string, Budget>): string =>
  [
    '# Composer performance budgets',
    '',
    '<!-- Generated by `node scripts/score-perf.ts docs --write` from `src/playwright/perf/budgets.json`; do not edit. -->',
    '',
    `The desired range of every metric the perf nightly (\`.depot/workflows/perf-nightly.yml\`, flow`,
    `\`${FLOW}\` in \`PERF.mdl\`) scores. Each value is the median across the night's iterations: a stage's`,
    'wall time and CPU (all processes), and whole-run levels reduced as the dashboard reduces them — the',
    'worst stage for memory and lag, the sum for blocking time and code shipped.',
    '',
    'Scores run 0–1 (`packages/e2e/perf-harness/src/score/score.ts`): at or under the target scores 1, the',
    'limit scores 0.5, and past it the score falls to 0.2 one budget band further (in log space) and 0.1',
    'two bands further, floored at 0.01. A budgeted stage that failed in every iteration scores 0.01. The',
    'overall score is the geometric mean of the three group scores, each the weighted geometric mean of',
    'its metrics.',
    '',
    'Budgets were calibrated on the CI runner (depot-ubuntu-24.04-8) from the nightly history in PostHog:',
    'the target is the stable level before a known regression, the limit 1.35× it — about 3× the 10–13%',
    'night-to-night spread a stage shows — widened where the evidence is thin (the task stages after',
    'windowing, 1.5×), narrowed where the stage is mostly scripted waits (scroll, edit: 1.15–1.2×) and',
    'doubled for `await-replication`, which waits on the network and carries half weight.',
    '',
    renderBudgetTables(
      Object.entries(budgets).map(([id, budget]) => ({
        id,
        group: groupOfId(id),
        label: id.split(' > ').slice(1).join(' > '),
        budget,
      })),
    ),
    '',
  ].join('\n');

const { positionals, values } = parseArgs({
  allowPositionals: true,
  options: {
    dir: { type: 'string', default: path.join(WORKSPACE_ROOT, 'test-results', 'perf') },
    publish: { type: 'boolean', default: false },
    summary: { type: 'string' },
    write: { type: 'boolean', default: false },
  },
});

const [command] = positionals;

if (command === 'score') {
  const dir = path.resolve(values.dir);
  // Only the per-iteration `measure` batches: the spec writes nothing else with this suffix.
  const files = readdirSync(dir).filter(
    (file) => file.startsWith(`${FLOW}-measure-`) && file.endsWith('.events.ndjson'),
  );
  if (files.length === 0) {
    throw new Error(`no ${FLOW} measure batches in ${dir}; did the flow reach a stage?`);
  }
  const decode = Schema.decodeUnknownSync(StageEvent);
  const events = files.flatMap((file) =>
    readFileSync(path.join(dir, file), 'utf8')
      .split('\n')
      .filter((line) => line.trim())
      .map((line) => decode(JSON.parse(line))),
  );

  const report = scoreMeasurements(toMeasurements(events), readBudgets(), { scoreMissing: { groupOf: groupOfId } });
  const markdown = renderReport('Composer performance', report);
  console.log(markdown);
  if (values.summary) {
    appendFileSync(values.summary, markdown + '\n');
  }
  for (const { id } of report.unbudgeted) {
    console.log(`::warning::metric "${id}" has no budget in src/playwright/perf/budgets.json`);
  }

  // The comparability fields every stage row carries, so a score tile can pin the same run shape.
  const first = events[0].properties;
  const pinned = Object.fromEntries(
    ['flow', 'scale', 'servingMode', 'pluginSet', 'profileState', 'instruments']
      .map((key) => [key, first[key]] as const)
      .filter((entry): entry is readonly [string, string | number | boolean] => entry[1] !== undefined),
  );
  const out = path.join(WORKSPACE_ROOT, 'test-results', 'perf-score');
  mkdirSync(out, { recursive: true });
  const eventsFile = path.join(out, 'composer.events.ndjson');
  const scoreEvents = toScoreEvents(report, { suite: 'composer', properties: pinned });
  writeFileSync(eventsFile, scoreEvents.map((event) => JSON.stringify(event)).join('\n') + '\n');
  if (values.publish) {
    const published = publishPosthogBatch(WORKSPACE_ROOT, eventsFile);
    console.log(published ? `published ${scoreEvents.length} score events` : '::warning::score events NOT published');
  }
} else if (command === 'docs') {
  const markdown = renderDocs(readBudgets());
  if (values.write) {
    writeFileSync(DOCS_FILE, markdown);
  } else {
    console.log(markdown);
  }
} else {
  throw new Error(`unknown command "${command ?? ''}"; expected score or docs`);
}
