//
// Copyright 2026 DXOS.org
//

// Scores a perf nightly's `measure` rows against `src/playwright/perf/budgets.json`, proposes
// work-counter budgets from several nights' rows, or renders the budgets as `spec/PERF-BUDGETS.md`.
//
//   node scripts/score-perf.ts score [--dir test-results/perf] [--counters] [--publish] [--summary <file>]
//   node scripts/score-perf.ts calibrate --run <dir> --run <dir> ... [--counters] [--write]
//   node scripts/score-perf.ts docs [--write]
//
// `--counters` selects the counters-on pass (`DX_PERF_COUNTERS=trace,calls,react`): its costed work
// counters alone, against `budgets-counters.json`, as the `composer-work` suite. Its timings are
// inflated by the instruments and are never scored.
//
// `calibrate` reads one directory per run — a downloaded `perf-nightly` (or `perf-counters`) artifact
// — and replaces the work-counter budgets with its proposal, leaving every other budget as it is.
//
// Run `score` once after every iteration has written its batch: a night's score is the median across
// them. A low score never fails the job; only broken inputs do.

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parseArgs } from 'node:util';

import {
  type Budget,
  COSTED_WORK_METRICS,
  type MeasureOptions,
  type WorkMetric,
  calibrateStageRuns,
  groupOfId,
  parseBudgets,
  renderBudgetTables,
  replaceWorkBudgets,
  scoreStageRun,
} from '@dxos/perf-harness/score';

const APP_ROOT = path.resolve(import.meta.dirname, '..');
const WORKSPACE_ROOT = path.resolve(APP_ROOT, '../../..');
const BUDGETS_FILE = path.join(APP_ROOT, 'src/playwright/perf/budgets.json');
const COUNTERS_BUDGETS_FILE = path.join(APP_ROOT, 'src/playwright/perf/budgets-counters.json');
const DOCS_FILE = path.join(APP_ROOT, 'spec/PERF-BUDGETS.md');

/** The flow and scale the budgets were calibrated on; another flow's rows are not scored. */
const FLOW = 'projects-tasks';

type Pass = { budgetsFile: string; suite: string; title: string; measure?: MeasureOptions; work?: WorkMetric[] };

const DEFAULT_PASS: Pass = { budgetsFile: BUDGETS_FILE, suite: 'composer', title: 'Composer performance' };

const COUNTERS_PASS: Pass = {
  budgetsFile: COUNTERS_BUDGETS_FILE,
  suite: 'composer-work',
  title: 'Composer work counters (counters-on pass)',
  measure: { work: [...COSTED_WORK_METRICS], timings: false },
  work: [...COSTED_WORK_METRICS],
};

const readBudgets = (file: string): Record<string, Budget> => parseBudgets(JSON.parse(readFileSync(file, 'utf8')));

const relative = (file: string) => path.relative(APP_ROOT, file);

const tables = (budgets: Record<string, Budget>) =>
  renderBudgetTables(
    Object.entries(budgets).map(([id, budget]) => ({
      id,
      group: groupOfId(id),
      label: id.split(' > ').slice(1).join(' > '),
      budget,
    })),
  );

/** A work counter's label leads with the stage, as the tables list stages; its id leads with the counter. */
const workTables = (budgets: Record<string, Budget>) =>
  renderBudgetTables(
    Object.entries(budgets).map(([id, budget]) => {
      const [counter, stage] = id.split(' > ');
      return {
        id,
        group: `${groupOfId(id)} (${relative(COUNTERS_BUDGETS_FILE)})`,
        label: `${stage} › ${counter}`,
        budget,
      };
    }),
  );

const renderDocs = (budgets: Record<string, Budget>, counters: Record<string, Budget>): string =>
  [
    '# Composer performance budgets',
    '',
    '<!-- Generated by `node scripts/score-perf.ts docs --write` from `src/playwright/perf/budgets*.json`; do not edit. -->',
    '',
    `The desired range of every metric the perf nightly (\`.depot/workflows/perf-nightly.yml\`, flow`,
    `\`${FLOW}\` in \`PERF.mdl\`) scores. Each value is the median across the night's iterations: a stage's`,
    'wall time, CPU (all processes) and work counters, and whole-run levels reduced as the dashboard',
    'reduces them — the worst stage for memory and lag, the sum for blocking time and code shipped.',
    '',
    'Scores run 0–1 (`packages/e2e/perf-harness/src/score/score.ts`): at or under the target scores 1, the',
    'limit scores 0.5, and past it the score falls to 0.2 one budget band further (in log space) and 0.1',
    'two bands further, floored at 0.01. A budgeted stage that failed in every iteration scores 0.01. The',
    'overall score is the geometric mean of the group scores, each the weighted geometric mean of its',
    'metrics.',
    '',
    'Timing budgets were calibrated on the CI runner (depot-ubuntu-24.04-8) from the nightly history in PostHog:',
    'the target is the stable level before a known regression, the limit 1.35× it — about 3× the 10–13%',
    'night-to-night spread a stage shows — widened where the evidence is thin (the task stages after',
    'windowing, 1.5×), narrowed where the stage is mostly scripted waits (scroll, edit: 1.15–1.2×) and',
    'doubled for `await-replication`, which waits on the network and carries half weight.',
    '',
    'Work-counter budgets (`<counter> > <stage>`, the `work` group) come from `score-perf.ts calibrate`',
    'over several nights’ artifacts: the target is the median of each night’s median, the limit three',
    'measured spreads above it (at least 5% and one count). A count moves only when the code does more',
    'or less work, so these sit within a few percent where timings need 35%. Only user-driven stages are',
    'budgeted, and only counters that are non-zero and under 5% per-iteration spread there.',
    '',
    tables(budgets),
    '',
    '## Counters-on pass',
    '',
    'The costed counters (`DX_PERF_COUNTERS=trace,calls,react`: a trace per stage and V8 precise',
    'coverage) cost 7–29% of wall time, so a separate job runs them and scores only them, as the',
    '`composer-work` suite; its timings are never scored or published.',
    '',
    workTables(counters),
    '',
  ].join('\n');

const { positionals, values } = parseArgs({
  allowPositionals: true,
  options: {
    dir: { type: 'string', default: path.join(WORKSPACE_ROOT, 'test-results', 'perf') },
    run: { type: 'string', multiple: true, default: [] },
    counters: { type: 'boolean', default: false },
    publish: { type: 'boolean', default: false },
    summary: { type: 'string' },
    write: { type: 'boolean', default: false },
  },
});

const [command] = positionals;
const pass = values.counters ? COUNTERS_PASS : DEFAULT_PASS;

if (command === 'score') {
  scoreStageRun({
    workspaceRoot: WORKSPACE_ROOT,
    dir: path.resolve(values.dir),
    flow: FLOW,
    measure: pass.measure,
    suite: pass.suite,
    title: pass.title,
    budgets: readBudgets(pass.budgetsFile),
    budgetsFile: relative(pass.budgetsFile),
    publish: values.publish,
    summary: values.summary,
  });
} else if (command === 'calibrate') {
  if (values.run.length < 2) {
    throw new Error('calibrate needs --run for at least two runs; one night cannot show a spread');
  }
  const proposed = calibrateStageRuns({
    dirs: values.run.map((dir) => path.resolve(dir)),
    flow: FLOW,
    ...(pass.work ? { work: pass.work } : {}),
  });
  const budgets = replaceWorkBudgets(readBudgets(pass.budgetsFile), proposed);
  if (values.write) {
    writeFileSync(pass.budgetsFile, JSON.stringify(budgets, null, 2) + '\n');
    console.log(`wrote ${Object.keys(proposed).length} work budgets to ${relative(pass.budgetsFile)}`);
  } else {
    console.log(JSON.stringify(proposed, null, 2));
  }
} else if (command === 'docs') {
  const markdown = renderDocs(readBudgets(BUDGETS_FILE), readBudgets(COUNTERS_BUDGETS_FILE));
  if (values.write) {
    writeFileSync(DOCS_FILE, markdown);
  } else {
    console.log(markdown);
  }
} else {
  throw new Error(`unknown command "${command ?? ''}"; expected score, calibrate or docs`);
}
