#!/usr/bin/env bash
set -euo pipefail

# We're consuming stdin to be able to pass it to git lfs later
consumed_stdin=""

# Each line is formatted as: local_ref local_sha remote_ref remote_sha
while IFS= read -r line; do
  remote_ref=$(echo "$line" | awk '{print $3}')

  if [[ "$remote_ref" = "refs/heads/main" ]] ; then
    if [[ "${push_to_main:-}" != "true" ]] ; then
      echo "Tried pushing to main. If you know what you're doing, run:"
      echo "push_to_main=true git push origin main"
      echo ""
      exit 1
    fi
  fi

  consumed_stdin="${consumed_stdin}${line}\n"
done

# Will consume stdin if runs first
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
printf "%b" "$consumed_stdin" | git lfs pre-push "$@"
