#!/usr/bin/env sh

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
git lfs pre-push "$@"

branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch == "main" ]] ; then
  if [[ "$push_to_main" != "true" ]] ; then
    echo "Tried pushing to main. If you know what you're doing, run:"
    echo "push_to_main=true git push origin main\n"
    exit 1
  fi
fi

exit 0
