#!/usr/bin/env sh

branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch == "main" ]] ; then
  if [[ "$push_to_main" != "true" ]] ; then
    echo "Tried pushing to main. If you know what you're doing, run:"
    echo "push_to_main=true git push origin main\n"
    exit 1
  fi
fi

exit 0