on:
  workflow_dispatch:
  push:
    branches:
      - main

# TODO(wittjosiah): Update for Nx repo. Migrate to CircleCI.

name: Integration tests with DXNS
jobs:
  check-integration-dxns:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: false
      - name: Check integration with DXNS
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npm install -g @microsoft/rush pnpm

          sudo apt-get update
          sudo apt-get install -y autoconf automake make g++ libtool libxtst-dev libpng-dev libx11-dev jq gstreamer1.0-plugins-bad libenchant1c2a gstreamer1.0-libav lsof
          npx playwright@1.11.0 install-deps

          # Install dependencies
          echo "::group::Install"
          node common/scripts/install-run-rush.js install
          echo "::endgroup::"

          node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build --verbose --to @dxos/registry-client

          docker pull ghcr.io/dxos/substrate-node:dev
          docker run -d --name dxns-integration-tests -p 9944:9944 ghcr.io/dxos/substrate-node:dev \
            dxns --dev --tmp --rpc-cors all -lsync=warn -lconsole-debug \
            --port 30333 --ws-port 9944 --rpc-port 9933 --rpc-methods Unsafe --ws-external --rpc-external

          cd packages/sdk/registry-client
          rushx test:integration
      - name: Cleanup
        if: always()
        run: |
          docker kill dxns-integration-tests || true
          docker rm dxns-integration-tests || true
