name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
          - 18.20.1
          - 20.12.1
          - 21.7.2
    env:
      DX_ENVIRONMENT: ci
      NODE_VERSION: ${{ matrix.node-version }}
      PNPM_HOME: /home/runner/.local/share/pnpm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          architecture: arm64

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
        shell: bash

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Configure PNPM
        run: |
          echo "PNPM_HOME=/home/runner/.local/share/pnpm" >> $GITHUB_ENV
          echo "/home/runner/.local/share/pnpm" >> $GITHUB_PATH
          echo "/home/runner/.local/share/pnpm/bin" >> $GITHUB_PATH

      - name: Cache PNPM store
        uses: actions/cache@v4
        with:
          path: /home/runner/.local/share/pnpm/store/v3
          key: ubuntu-pnpm-store-18.20.1
          restore-keys: |
            ubuntu-pnpm-store-18.20.1-

      - name: Install dependencies
        run: |
          pnpm set verify-store-integrity false
          pnpm config set network-timeout 300000
          pnpm install --prefer-offline
          pnpm install-playwright
        env:
          PNPM_HOME: /home/runner/.local/share/pnpm
          PATH: ${{ env.PATH }}:/home/runner/.local/share/pnpm

      - name: Set NX shas
        run: nx/set-shas

      - name: Run affected lint
        run: pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=lint

      - name: Run affected build
        run: pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=build

      - name: Run affected tests
        run: |
          export VITEST_XML_REPORT=true
          export VITEST_ENV=node
          pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=test

      - name: Run full tests on main branch
        if: github.ref == 'refs/heads/main'
        run: |
          pnpm nx run-many --target=lint
          pnpm nx run-many --target=build
          VITEST_XML_REPORT=true pnpm nx run-many --target=test --skip-nx-cache

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Install system dependencies
        run: |
          sudo apk add --no-cache build-base cairo-dev pango-dev jpeg-dev giflib-dev librsvg-dev

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Configure PNPM
        run: |
          echo "PNPM_HOME=${HOME}/.local/share/pnpm" >> $GITHUB_ENV
          echo "${HOME}/.local/share/pnpm" >> $GITHUB_PATH
          echo "${HOME}/.local/share/pnpm/bin" >> $GITHUB_PATH

      - name: Cache PNPM store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install PNPM globally
        run: npm install -g pnpm

      - name: Configure environment
        run: |
          echo "export PNPM_HOME=${HOME}/.local/share/pnpm" >> $HOME/.profile
          echo "export PATH=${PATH}:${HOME}/.local/share/pnpm" >> $HOME/.profile
          source $HOME/.profile

      - name: Configure PNPM
        run: |
          pnpm config set unsafe-perm true
          pnpm config set ignore-scripts false
          pnpm config set network-timeout 300000

      - name: Cache PNPM store (after install)
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}-after-install
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          export PNPM_HOME=${HOME}/.local/share/pnpm
          export PATH=${PATH}:${HOME}/.local/share/pnpm
          echo "PNPM_HOME=${HOME}/.local/share/pnpm" >> $GITHUB_ENV
          echo "${HOME}/.local/share/pnpm" >> $GITHUB_PATH
          pnpm set verify-store-integrity false
          pnpm config set network-timeout 300000
          pnpm install --prefer-offline
          pnpm install-playwright
        shell: sh

      - name: Set NX shas
        run: nx/set-shas

      - name: Check dependencies
        run: pnpm check-dependencies

      - name: Check cycles
        run: node ./scripts/check-cycles.mjs

      - name: Run affected lint
        run: pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=lint

      - name: Run affected build
        run: pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=build

      - name: Run affected tests
        run: |
          export VITEST_XML_REPORT=true
          export VITEST_ENV=node
          pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=test

      - name: Run full tests on main branch
        if: github.ref == 'refs/heads/main'
        run: |
          pnpm nx run-many --target=lint
          pnpm nx run-many --target=build
          VITEST_XML_REPORT=true pnpm nx run-many --target=test --skip-nx-cache

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

  e2e:
    runs-on: ubuntu-latest
    env:
      DX_ENVIRONMENT: ci
      DX_PWA: false
      NODE_OPTIONS: --max-old-space-size=12288

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.1'
          cache: 'pnpm'
          architecture: arm64

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Configure PNPM
        run: |
          echo "PNPM_HOME=${HOME}/.local/share/pnpm" >> $GITHUB_ENV
          echo "${HOME}/.local/share/pnpm" >> $GITHUB_PATH
          echo "${HOME}/.local/share/pnpm/bin" >> $GITHUB_PATH

      - name: Cache PNPM store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm install
          pnpm install-playwright

      - name: Set NX shas
        run: nx/set-shas

      - name: Build affected bundles
        run: pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=bundle --parallel=1

      - name: Run e2e tests
        run: |
          pnpm nx affected --base=${{ github.event.pull_request.base.sha }} --head=${{ github.event.pull_request.head.sha }} --target=e2e --browser=all --parallel=1
        timeout-minutes: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

      - name: Upload playwright artifacts
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: dist/.playwright

  flaky:
    runs-on: ubuntu-latest
    env:
      DX_ENVIRONMENT: ci

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.1'
          cache: 'pnpm'
          architecture: arm64

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Configure PNPM
        run: |
          echo "PNPM_HOME=${HOME}/.local/share/pnpm" >> $GITHUB_ENV
          echo "${HOME}/.local/share/pnpm" >> $GITHUB_PATH
          echo "${HOME}/.local/share/pnpm/bin" >> $GITHUB_PATH

      - name: Cache PNPM store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run flaky tests
        run: ./scripts/run-flaky-tests.sh
        timeout-minutes: 30
