name: Publish DXOS docker containers to GitHub Registry

on:
  workflow_dispatch

jobs:
  docker_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Publish Docker Images
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "${{ secrets.CONTAINER_REGISTRY_TOKEN }}" | docker login https://ghcr.io -u ${{ github.repository_owner }} --password-stdin
        ./common/scripts/docker-build-release.sh dev
