name: CI

on:
  workflow_dispatch:
    inputs:
      verbose:
        description: 'Enable verbose output'
        required: false
        default: 'false'
        type: string
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_VERSION: 20.19.0
      VERBOSE: ${{ inputs.verbose }}

    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .circleci
          file: .circleci/Dockerfile
          push: false
          load: true
          tags: dxos-ci:latest

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Run in Docker container
        run: |
          docker run --rm dxos-ci:latest bash -c '
            # Install dependencies
            pnpm install --frozen-lockfile -w
            # Install specific dependencies needed for NX
            pnpm add -w nx@latest lines-and-columns@latest
            # Checkout code
            git clone https://github.com/dxos/dxos.git /dxos
            cd /dxos
            # Run NX build
            pnpm nx run-many --target=build --all --parallel ${VERBOSE:+--verbose}
          '

      - name: Cache selective dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.pnpm-store
            node_modules/.cache
            node_modules/@dxos
            node_modules/@types
            node_modules/@nx
            node_modules/@effect
            node_modules/@typescript-eslint
          key: ${{ runner.os }}-selective-${{ hashFiles('pnpm-lock.yaml') }}-${{ env.NODE_VERSION }}
          restore-keys: |
            ${{ runner.os }}-selective-${{ env.NODE_VERSION }}-
            ${{ runner.os }}-selective-

      - name: Build with NX
        run: |
          pnpm nx run-many --target=build --all --parallel ${VERBOSE:+--verbose}
        env:
          CI: true
          VERBOSE: ${{ inputs.verbose }}

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            dist
            lib
            build
            .nx
          key: ${{ runner.os }}-build-${{ hashFiles('pnpm-lock.yaml', 'package.json') }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/project.json', 'nx.json', 'workspace.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.NODE_VERSION }}-

      - name: Lint with NX
        run: |
          pnpm nx lint --all --parallel ${VERBOSE:+--verbose}

      - name: Test with NX
        run: |
          pnpm nx test --all --parallel ${VERBOSE:+--verbose}

      - name: Cache test results
        uses: actions/cache@v4
        with:
          path: |
            coverage
            .nyc_output
            .vitest
            .jest
          key: ${{ runner.os }}-test-results-${{ hashFiles('pnpm-lock.yaml', 'package.json') }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/project.json', 'nx.json', 'workspace.json') }}
          restore-keys: |
            ${{ runner.os }}-test-results-${{ env.NODE_VERSION }}-
