name: Socket Publish

on:
  workflow_dispatch:
  push:
    branches:
      - jdw/build-socket

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 20.12.1

      - name: Bundle Composer
        run: pnpm exec nx bundle composer-app
        env:
          DX_ENVIRONMENT: production
          DX_HOST: true
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Checkout Socket
        uses: actions/checkout@v4
        with:
          repository: socketsupply/socket
          ref: master
          path: socket
      
      - name: Setup Socket
        run: |
          cd socket
          ./bin/uninstall.sh
          npm rm -g @socketsupply/socket
          NO_ANDROID=1 npm run relink

      - name: macOS Build
        run: |
          cd packages/apps/composer-app
          ssc build
