name: Socket Publish

on:
  workflow_dispatch:
  push:
    branches:
      - jdw/build-socket

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        # if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Checkout Socket
        uses: actions/checkout@v4
        with:
          repository: socketsupply/socket
          ref: master
          path: socket

      - name: Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install automake
      
      - name: Setup Socket
        run: |
          cd socket && NO_ANDROID=1 npm run relink

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 20.12.1

      - name: Bundle Composer
        run: pnpm exec nx bundle composer-app
        env:
          DX_ENVIRONMENT: production
          DX_HOST: true
          NODE_OPTIONS: --max-old-space-size=8192

      - name: macOS Build
        run: |
          cd packages/apps/composer-app && ssc build
