name: Socket Publish

on:
  workflow_dispatch:
  push:
    branches:
      - jdw/build-socket

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        # if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - name: Bundle Composer
        run: pnpm exec nx bundle composer-app
        env:
          DX_ENVIRONMENT: production
          DX_HOST: true
          NODE_OPTIONS: --max-old-space-size=8192
      
      - name: Checkout Socket
        uses: actions/checkout@v4
        with:
          repository: socketsupply/socket
          ref: master
          path: socket

      - name: Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install automake libtool
      
      - name: Setup Socket
        run: |
          cd socket && NO_ANDROID=1 npm run relink

      - name: macOS Build
        run: |
          cd packages/apps/composer-app && ssc build
