name: TODO Tracker

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to check (optional - will auto-detect if not provided)'
        required: false
        type: string

env:
  DEPOT_TOKEN: ${{ secrets.DEPOT_TOKEN }}

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  track-todos:
    runs-on: depot-ubuntu-24.04-8
    container:
      image: ghcr.io/dxos/gh-actions:24.4.1
      credentials:
        username: dxos-bot
        password: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          lfs: true

      - name: Extract branch
        id: extract_branch
        uses: ./.github/actions/branch

      - name: Setup
        uses: ./.github/actions/setup

      - name: Track TODOs
        run: node scripts/find-todos.mjs --github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_REF: ${{ github.ref }}

      - name: Console Output (for debugging)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Also running console output for debugging..."
          node scripts/find-todos.mjs
