version: 1

runtime:
  client:
    storage:
      persistent: false
      # enum StorageDriver {
      #   RAM = 0;
      #   IDB = 1;
      #   CHROME = 2;
      #   FIREFOX = 3;
      #   NODE = 4;
      #   WEBFS = 5;

      #   // Key storage only
      #   LEVELJS = 11;
      #   JSONDOWN = 12;
      # }
      storageType: 0

  services:
    signaling:
      - server: ws://localhost/.well-known/dx/signal
    ice:
      - urls: stun:kube.dxos.org:3478
        username: dxos
        credential: dxos
      - urls: turn:kube.dxos.org:3478
        username: dxos
        credential: dxos
      - urls: stun:dev.kube.dxos.org:3478
      - urls: turn:dev.kube.dxos.org:3478
        username: dxos
        credential: dxos
        